= How To Install Globus Connect Personal for Linux Using the Command Line

You may install Globus Connect Personal for Linux using only the command line. Before getting started ensure that you have a valid SSH key associated with your Globus account. If you do not have an SSH key, link:../../faq/command-line-interface/#how_do_i_generate_an_ssh_key_to_use_with_the_globus_command_line_interface[see this guide for instructions on generating one]. Once you have an SSH key, follow the instructions here to associate the SSH key with your Globus account.

NOTE: Instructions are also available for link:../globus-connect-personal-linux[installing a Globus Online Personal endpoint using your Web browser].

== Installation
. Download and unpack the Globus Connect Personal for Linux installer:
+
----terminal
$ wget https://s3.amazonaws.com/connect.globusonline.org/linux/stable/globusconnectpersonal-latest.tgz
[output]#--2013-06-07 00:14:10-- https://s3.amazonaws.com/connect.globusonline.org/linux/stable/glob...
Resolving s3.amazonaws.com (s3.amazonaws.com)... 72.21.214.199
Connecting to s3.amazonaws.com (s3.amazonaws.com)|72.21.214.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8291206 (7.9M) [application/x-tar]
Saving to: \`globusconnectpersonal-latest.tgz'

100%[==============================================================================>] 8,291,206 1010K/s in 8.0s

2013-06-07 00:14:18 (1018 KB/s) - \`globusconnectpersonal-latest.tgz' saved [8291206/8291206]#
$ tar xzf globusconnectpersonal-latest.tgz
$ cd globusconnectpersonal-[input]#x.y.z#
----terminal
+
NOTE: In the last line above, replace [uservars]#x.y.z# with the version number from the downloaded file, e.g. globusconnectpersonal-2.0.2.

. Generate a setup key for your endpoint via the Globus command line interface. The example below shows Globus user [uservars]#demodoc# generating a setup key for an endpoint called [uservars]#my-linux-laptop#:
+
----terminal
$ ssh [input]#demodoc#@cli.globusonline.org
Welcome to globusonline.org, demodoc. Type \'help' for help.
$ endpoint-add -n [input]#my-linux-laptop# --gc
[output]#Endpoint ID: b19b3b45-01ae-11e6-a71c-22000bf2d559

Use this setup key when installing Globus Connect Personal: 
    224532bb-8a4b-4d32-8995-e1fb442be98e#
$ exit
----terminal

. Back in your local machine shell run the following commands to complete the installation (note that you will need to copy and paste the setup key generated in step 2 above):
+
----terminal
$ ./globusconnectpersonal -setup [input]#224532bb-8a4b-4d32-8995-e1fb442be98e#
[output]#Configuration directory: /home/demodoc/.globusonline/lta
Contacting relay.globusonline.org:2223
Installing certificate and key
Creating /home/demodoc/.globusonline/lta/gridmap
Done!#
----terminal

Globus Connect Personal is now installed and your Globus endpoint is configured.

== Running Globus Connect
To transfer and share files using Globus, start Globus Connect Personal (and, optionally, activate your endpoint) as follows:

----terminal
$ ./globusconnectpersonal -start &
[output]#[1] 2965#
$ ssh [input]#demodoc#@cli.globusonline.org endpoint-activate [input]#b19b3b45-01ae-11e6-a71c-22000bf2d559#
----terminal

You should now see your endpoint listed (with active credentials) if you run:

----terminal
$ ssh [input]#demodoc#@cli.globusonline.org endpoint-search --scope my-endpoints
[output]#ID                : ea557994-fc2d-11e5-a700-22000bf2d559
Display Name      : demo
Legacy Name       : demodoc#ea557994-fc2d-11e5-a700-22000bf2d559
Owner             : demodoc
Credential Status : n/a
Host Endpoint     : ddb59aef-6d04-11e5-ba46-22000b92c6ec
Host Endpoint Name: Globus Tutorial Endpoint 1

ID                : b19b3b45-01ae-11e6-a71c-22000bf2d559
Display Name      : my-linux-laptop
Legacy Name       : demodoc#b19b3b45-01ae-11e6-a71c-22000bf2d559
Owner             : demodoc
Credential Status : n/a
Host Endpoint     : n/a
Host Endpoint Name: n/a#
----terminal

The status of Globus Connect Personal running in the background can be controlled using the +-status+ or +-trace+ options. The +-trace+ option provides more detailed information:

----terminal
$ ./globusconnectpersonal -status
[output]#Globus Online: connected
Transfer Status: idle#
$ ./globusconnectpersonal -trace
[output]#gridftp 1
#gsissh connected
#gridftp 1
#gsissh connected
#gridftp 1
[...]#
----terminal