---
full_title: "Globus Toolkit 6.0 Release Notes"
short_title: "Release Notes"
---

= Globus Toolkit 6.0 Release Notes

[red]#(CONTENT NEEDS REVIEW)#

== Introduction
The GT development team is pleased to make a new stable release of the Globus Toolkit available for download.

By following the Quickstart guide, you can easily install and setup a full GT environment in minutes.

Highlights of this release include:

Overall

Migrate from CVS to https://github.com/globus/globus-toolkit
Simplified package by eliminating GPT and library flavors
Integrate tests into native package build process
Porting to windows — mingw (partial) and cygwin
Add support for el7 (CentOS 7, RHEL 7)
Add binary package for Mac OS X
Make binaries and scripts more easily relocatable (don’t need to set GLOBUS_LOCATION for most cases)
GridFTP

UDT Support for Wide-Area, Lossy Networks
UDT NAT Traversal, supported by Globus Connect Personal for
S3/HTTP support, allowing GridFTP transfers to and from Amazon S3
DCSC for cross-domain transfers without mutual trust
C Common Libraries

None.
To view details for each component, see Release Notes by Component.

== Obtaining and Installing Software
To download this release, go to the Downloads Page.

For information on installing this release, go to the 6.0 Installation Guide.

=== Java Client API Download

Java client APIs to the GT 6.0 services are available from the jGlobus project.

== Platform Notes
Check out platform-specific installation issues here.

== Documentation
Use the documentation which starts here.

Feel free to offer any suggestions or feedback using JIRA (the "Documentation" project).

== Support
An overview on GT support can be found here.

== Licensing
The Globus Toolkit is distributed and licensed for use under the terms of the Apache License, Version 2.0.

To view the licenses of the 3rd party software used by the developers of the Globus Toolkit, click here.

== Usage Statistics
For full information about usage statistics collected by GT 6.0 and how to opt-out, see Usage Statistics Collection by the Globus Alliance.

== Release Notes by Component
GridFTP
GRAM5
Security

GSI C
SimpleCA
MyProxy
GSI-OpenSSH
Common Runtime Components

XIO
C Common Libraries