---
full_title: "Amazon Web Services S3 Connector"
short_title: "Amazon Web Services S3"
menu_weight: 1
---

= Amazon Web Services S3 Connector
:revdate: April 5, 2017

This connector enables use of a Globus data access interface on an link:https://aws.amazon.com/s3/[AWS S3] storage system. This requires the installation of Globus Connect Server and an additional package that is specific to the AWS S3 storage system called the Amazon S3 DSI.

The AWS S3 connector is a premium feature available only to Globus subscribers, and is thus only available for link:../../globus-connect-server-installation-guide/#managed-endpoint-anchor[Managed Endpoints]. 

== Prerequisites
A functional Globus Connect Server installation is required for installation and use of the AWS S3 connector.  The link:../../globus-connect-server-installation-guide/[Globus Connect Server Installation Guide] provides detailed documentation on the steps for installing and configuring a server endpoint.
Supported Linux Distributions

The AWS S3 DSI is available for the following Linux distributions:

- RHEL 7
- RHEL 6
- CentOS 7
- CentOS 6
- Ubuntu 14.04
- Ubuntu 16.04
- Debian 7
- Debian 8
- SLES 12

=== Supported Globus Connect Server versions
The S3 DSI should be used with the latest version of GCS.

== Installation
Install the package globus-gridftp-server-s3 from the Globus repository.

For RedHat-based systems:

----terminal
# yum install globus-gridftp-server-s3
----terminal

For Debian-based systems:

----terminal
# apt-get install globus-gridftp-server-s3
----terminal

For SLES 11-based systems:

----terminal
# zypper install globus-gridftp-server-s3
----terminal

=== Configuration
The S3 DSI requires the following steps for configuration:

- Configure the S3 DSI
- Create a gridmap to S3 credentials
- Restart the GridFTP server

==== Configure the S3 DSI
Create the file /etc/gridftp.d/gridftp-s3 containing these lines:

----
 threads 2
 load_dsi_module s3
----

==== Create a file containing s3 credentials
The default configuration for the S3 DSI looks in $HOME/.globus/s3 for a
file mapping the current user's ID to S3 access keys. Each user who will
be using the DSI must create such a file with their credentials.

----
 % mkdir -m 0700 -p ~/.globus
 % (umask 077; echo "$(id -un);$S3_ACCESS_KEY_ID;$S3_SECRET_ACCESS_KEY" \
    > ~/.globus/s3
----

==== Restart the gridftp server

----terminal
# service globus-gridftp-server restart
----terminal

== Debugging Tips
To enable a debugging log for the S3 dsi, set the environment
variable GLOBUS_S3_DEBUG "1023,/tmp/s3.log" to enable a highly verbose log
of the DSI. This can be easily done for a gridftp configuration by creating
a file /etc/gridftp.d/s3-debug with the contents

----
 $GLOBUS_S3_DEBUG "1023,/tmp/s3.log"
----

== Basic Endpoint Functionality Test
After completing the installation, you should do some basic transfer tests with your endpoint to ensure that it is working. We document a process for basic endpoint functionality testing here.

NOTE: For legacy AWS S3 Connector, please see link:../legacy/aws-s3-legacy[https://docs.globus.org/premium-storage-connectors/legacy/aws-s3-legacy].