= DETAILS(1)

== NAME

details - View detailed information about a task

== SYNOPSIS

*details* ['OPTIONS'] [-a]

*details* ['OPTIONS'] 'TASKID'...

*details* ['OPTIONS'] label='PATTERN'

== DESCRIPTION

*details* displays detailed information about tasks.  By default, *details*
displays all currently running or pending tasks.  Use the *-a* option to
display all tasks, including completed tasks.  Tasks are sorted by request
time in descending order.

Tasks may be specified by one or more task ids or by a label pattern.  The
'PATTERN' pattern may contain asterisk (+*+) characters for wildcard matching
of labels.
  
If individual task id(s) are specified, tasks will be displayed in the order
given and not sorted. 

== OPTIONS

*-a*::
Show all tasks, including those that have already completed

*-t*:: 
Show subtasks, such as individual file copy operations, of the specified
task(s).  
+
NOTE: This information level is highly internal to Globus Online and the
output, format, and sort order is not guaranteed to remain
backwards-compatible in future releases.

*--retrying*:: 
Only show subtasks that are pending and had a fault.  Only available with -t.

*--succeeded*:: 
Only show subtasks that have succeeded.  Only available with -t.


*-l* 'LIMIT'::
Limit the number of results.  Default: Unlimited

include::include/opt_output.adoc[]

== OUTPUT FIELDS

*bytes_transferred*::
The number of bytes transferred.  Valid for transfer tasks.

*command*::
The original command line, including options, that created this task.


*completion_time*::
The date and time this task finished processing (successfully or unsuccessfully).  

*deadline*::

The date and time of this task's deadline.  If a task has not completed by its
deadline it will be aborted.

*directories*::

The total number of directories and subdirectories added by recursive
directory expansion.  Valid for transfer tasks.

*expansions*::
The number of recursive directories given as input.

*faults*::

The number of errors this task encountered.  Note that certain types of faults
are not fatal (for example, network communication errors) and can be
successfully retried.  A CANCELED or EXPIRED event is not included in this
fault count.  

*files*::
The total number of files in this task.  Valid for transfer tasks.

*label*::
The label (if any) for the task.

*mbits_sec*::

A simplistic calculation of megabits/second based on the start time of the
task and its completion time, if applicable, or the current time.  Valid for
transfer tasks.

*request_time*::
The date and time this task was created

*src_endpoint, dst_endpoint*::
The source and destination logical endpoint names

include::include/task_statuses.adoc[]

*taskid*::
The unique id of the task

include::include/task_types.adoc[]


*tasks_canceled*::
The number of tasks canceled by an operator

*tasks_expired*::
The number of tasks that passed their deadline

*tasks_failed*::

The number of tasks that had a critical failure.  This does not include
canceled or expired tasks. 

*tasks_pending*::

The number of tasks that have not yet completed.  Completed means canceled,
expired, failed, or successful.

*tasks_retrying*::

The number of pending tasks that have had one or more faults while processing.
This is a subset of tasks_pending.  

*tasks_successful*::
The number of tasks that completed successfully

*total_tasks*::
The task's total number of subtasks



== EXAMPLES

Show details of last 5 tasks:

----
details -a -l 5
----

Show details of a transfer task:

----
details a04d9872-aec7-11df-9563-1231380722ca
----

Show details of all transfer tasks with label matching pattern:

----
details label=*data*
----
