= ENDPOINT-MODIFY(1)

== NAME

endpoint-modify - Change attributes of an endpoint

== SYNOPSIS

*endpoint-modify* 'OPTIONS' 'ENDPOINT'

== DESCRIPTION

*endpoint-modify* can set attributes of an endpoint.   One attribute can be
set or unset at a time.  See the options below for details.  Use the empty
string ("") to unset a text attribute.  Run *endpoint-details* to view current
attributes.

The default MyProxy server (regular or OAuth based) for an endpoint is used by
the *endpoint-activate* command.

'ENDPOINT' can use these formats:

include::include/cli_endpoint_unique_id.adoc[]


== OPTIONS

*--display-name* 'DISPLAY_NAME'::

Set the display name.  'DISPLAY_NAME' is unique for all endpoints owned by the
current user, but is not globally unique.  'DISPLAY_NAME' must not contain a
newline character.  Example: "NERSC HPSS", "UChicago RCC Midway cluster"

*--description* 'TEXT'::
Description of the endpoint displayed to users and used in search to
differentiate this endpoint from similarly named endpoints. e.g. "This endpoint
is used to access data from the NERSC HPSS archive".

*--organization* 'TEXT'::
Organization with which this endpoint is associated. e.g. "The University of
Chicago", "NERSC"

*--department* 'TEXT'::
Department with which this endpoint is associated. e.g. "Research Computing
Center, Department of Physics"

*--keywords* 'TEXT'::
Additional text that may be used in search by users to discover this endpoint.
e.g. "UChicago, Midway RCC".  Keywords may be separated by whitespace or
commas.  This entirely replaces the current keyword text.


*--contact-info* 'TEXT'::
Address for an end user to get help using this endpoint.  e.g. address, phone,
etc.

*--contact-email* 'EMAIL'::
Email address for an end user to get help using this endpoint. e.g.
"help@xsede.org"

*--info-link* 'LINK'::
A URL to a webpage that provides more information to end users about using the
endpoint. e.g. "https://bluewaters.ncsa.illinois.edu/data-transfer-doc"



*--public*::

Set public visibility.  Other users can see public endpoints by
running *endpoint-search* or *endpoint-details*.  This does not mean all users
can actually login and access files on the endpoint.

*--private*::

Set private visibility.  By default, newly created endpoints are
private and are only visible to the current user.

*--default-directory* 'DIRECTORY'::

Use DIRECTORY as the initial path for directory listings in the Globus Online
web site.  If this is unset (the default), "`~`" is used.


*--myproxy-oauth-server* 'SERVER'::

Set the default myproxy server (oauth based), in the form host[:port].  The
server should previously have been registered with the Globus Online web site.
Please contact Globus Online support for details.

*--myproxy-server* 'SERVER'::

Set the default myproxy server (regular), in the form host[:port].

*--myproxy-dn* 'DN'::

Set the X.509 subject DN of the myproxy server.  This is required if the
certificate subject does not match the hostname.



*--force-encryption*::
*--no-force-encryption*::

Forces encryption of all network data for transfers to and from the endpoint.
If this is set, all transfer jobs will have the encryption option
automatically turned on regardless of the user's initial submission options.
If this is not set, users can decide whether or not to enable encryption.

*--disable-verify*::
*--no-disable-verify*::

This option indicates that the endpoint does not support computing MD5
checksums, needed for the *--verify-checksum* option of *transfer*.  When this
is set, new job submissions will default to not use the *--verify-checksum*
option.



*--managed-endpoint*::

Set the endpoint subscription ID.  If the current user has more than one
subscription ID, use the *--subscription* option to select the desired
subscription ID.

*--no-managed-endpoint*::

Remove the endpoint subscription ID

*--subscription* 'UUID'::

Specifies the subscription id to use for *--managed-endpoint*



*--network-use* 'LEVEL'::

Set the endpoint's network usage level.  For transfer tasks, the settings from
both the source and destination endpoints are used to calculate appropriate
values for concurrency and parallelism.   
+
This option may only be used on managed endpoints.  If a managed endpoint
becomes unmanaged, the "normal" level will be automatically used.
+
This option may not be set on shared endpoints; a shared endpoint uses the
settings of its host endpoint.
+
Allowed values for 'LEVEL' are:
+
"normal";;
The default setting.  Uses an average level of concurrency and parallelism.
The levels depend on the number of physical servers in the endpoint; use
*endpoint-details* to display the exact values.
+
"minimal";;
Uses a minimal level of concurrency and parallelism.
+
"aggressive";;
Uses a high level of concurrency and parallelism.
+
"custom";;
Uses custom values of concurrency and parallelism set by the endpoint admin.
When setting this level, you must also set the *--max-concurrency*,
*--preferred-concurrency*, *--max-parallelism*, and *--preferred-parallelism*
options.
(Note: S3 endpoints do not support the parallelism options, only concurrency)


*--location* "Automatic" | 'LATITUDE,LONGITUDE'::

Set the endpoint's location to explicit coordinates (in decimal degrees), or
"Automatic", which uses a potentially innaccurate or incomplete GeoIP
database.  The default is "Automatic", but setting it explicitly is
recommended for fixed-location endpoints (See EXAMPLES section).
+
The location information is used for automatic tuning of GridFTP transfer
parameters.
+
May not be set for S3 endpoints or shared endpoints.




== EXAMPLES

Set the location of the "midway" endpoint, using the latitude and longitude of
Midway airport as an example:

----
$ endpoint-modify midway --location "41.79,-87.75"
----

Set the "midway" endpoint to a custom network use setting:

----
$ endpoint-modify midway --network-use custom \
    --max-concurrency 10 --preferred-concurrency 5 \
    --max-parallelism 8 --preferred-parallelism 4
----

Set the current user's endpoint "penguin" as public:

----
$ endpoint-modify penguin --public 
----
