= ENDPOINT-MODIFY(1)

== NAME

endpoint-modify - Change attributes of endpoint(s)

== SYNOPSIS

*endpoint-modify* ['OPTIONS'] 'PATTERN'...

== DESCRIPTION

*endpoint-modify* can set attributes of endpoint(s).   One attribute can be
set or unset against one or more endpoints at a time.  See the options below
for details.  Use the empty string ("") to unset a text attribute.  Run
*endpoint-list -v* to view current attributes.

The default myproxy server (regular or oauth based) for an endpoint can be
used by the *endpoint-activate* command and all commands that attempt auto
activation, such as *scp*.


== OPTIONS

*--public*::

Set public visibility for endpoints.  Public endpoints can be seen by other
users running *endpoint-list -p*.

*--private*::

Set private visibility for endpoints.  By default, newly created endpoints are
private and are only visible to the current user.

*--default-directory* 'DIRECTORY'::

Use DIRECTORY as the initial path for directory listings in the Globus Online
web site.  If this is unset (the default), "`~`" is used.

*--force-encryption*::
*--no-force-encryption*::

Forces encryption of all network data for transfers to and from the endpoint.
If this is set, all transfer jobs will have the encryption option
automatically turned on regardless of the user's initial submission options.
If this is not set, users can decide whether or not to enable encryption.

*--disable-verify*::
*--no-disable-verify*::

This option indicates that the endpoint does not support computing MD5
checksums, needed for the *--verify-checksum* option of *transfer*.  When this
is set, new job submissions will default to not use the *--verify-checksum*
option.

*--myproxy-oauth-server* 'SERVER'::

Set the default myproxy server (oauth based), in the form host[:port].  The
server should previously have been registered with the Globus Online web site.
Please contact Globus Online support for details.

*--myproxy-server* 'SERVER'::

Set the default myproxy server (regular), in the form host[:port].

*--myproxy-dn* 'DN'::

Set the X.509 DN for the *--myproxy-server*.  This is required if the reverse
DNS hostname does not match its host certificate.

*--port-range* 'START_PORT,END_PORT'::

DEPRECATED: Sets the outbound TCP ports used for directory listings.  The
default range is 50000,51000.  The allowed range is 40000-51000.  Anything
outside of this range will time out.
+
NOTE: New versions of Globus GridFTP server support directory listings over
the control channel and do not require data ports for Globus Online use.

== EXAMPLES

Mark the current user's endpoints "foo" and "bar" as public:

----terminal
endpoint-modify --public foo bar
----terminal

Mark all of the current user's endpoints as public:

----terminal
endpoint-modify --public *
----terminal
