= RENAME(1)

== NAME

rename - Quickly rename a file or directory

== SYNOPSIS

*rename* ['OPTIONS'] 'ENDPOINT:OLD-PATH' 'ENDPOINT:NEW-PATH'

== DESCRIPTION

The *rename* command renames a file or directory on an endpoint.  

The old path must be an existing file or directory.  The new path must not yet
exist.  

The new path does not have to be in the same directory as the old path, but
most endpoints will require it to stay on the same filesystem (you can not
rename across a filesystem boundary).

The endpoint name must be entered twice (in the old and new paths) for the
sake of path syntax consistency.

== OPTIONS

*-g*::
Activate the endpoint using your gsi-ssh credential


== EXAMPLES

Rename a directory:

----terminal
rename go#ep1/~/tempdir go#ep1/~/project-foo
----terminal

Alternate, SCP-like home directory path syntax:

----terminal
rename go#ep1:tempdir go#ep1:project-foo
----terminal


== EXIT STATUS

rename returns 0 on success, and 1 if a network or server error occurred.
