= STATUS(1)

== NAME

status - View status of task(s)

== SYNOPSIS

*status* ['OPTIONS'] [-a]

*status* ['OPTIONS'] 'TASKID'...

*status* ['OPTIONS'] label='PATTERN'

== DESCRIPTION

*status* displays basic information about tasks.  By default, all pending
(ACTIVE or INACTIVE) tasks are shown.  If the *-a* option is given, *status*
displays all tasks, including completed tasks.  Tasks are sorted by request
time in descending order.

Status for specific tasks can be obtained by including one or more task ids or
a label pattern.  The 'PATTERN' may contain asterisk ("*") characters for
wildcard matching of labels.

By default, only a few fields are shown for each task.  Use the *-f* option to
select more fields than what are shown by default.  


== OPTIONS

*-l* 'LIMIT'::
Limit the number of results.  Default: Unlimited

*-a*::
Show all tasks, including completed

include::include/opt_output.adoc[]


== OUTPUT FIELDS

*command*::
The original command line, including options, that created this task.

*completion_time*::
The date and time this task finished processing (successfully or unsuccessfully)

*deadline*::
The date and time of this task's deadline.  If a task has not completed by its deadline it will be aborted.

*label*::
The label (if any) for the task.

*request_time*::
The date and time this task was created

include::include/task_statuses.adoc[]

*taskid*::
The unique ID of the task

include::include/task_types.adoc[]


== EXAMPLES

Show all pending tasks:

----
$ status
----

Show last 20 tasks, including completed:

----
$ status -a -l 20
----

Show all tasks containing the label string "data":

----
$ status label=*data*
----

Print just the status and request_time fields of a certain task:

----
$ status -f status,request_time -O csv b9582054-aad4-11df-8cd0-12313806cd95
----
