= ENDPOINT-ADD(1)

== NAME

endpoint-add - Create an endpoint 

== SYNOPSIS

*endpoint-add* -n 'DISPLAYNAME' ['OPTIONS'] 

== DESCRIPTION

*endpoint-add* can create an endpoint with a user specified display name.  The
display name is unique per-user, but it is not globally unique.  The endpoint
UUID is globally unique, generated by the system, and is printed in this
format: "Endpoint ID: <UUID>".

The display name and other endpoint attributes can be changed by the
*endpoint-modify* command.  The *server-add* command can add a GridFTP server
to an endpoint.

A newly created endpoint has a default legacy name of +"user#UUID"+, where
'UUID' is the same as the endpoint's UUID.  The legacy name can be changed by
*endpoint-rename*, but the endpoint's UUID can never be changed.

An endpoint can be used by the *transfer* command to transfer files.  Use the
*endpoint-activate* command to assign a valid security credential to an
endpoint.

An endpoint should be referred to using its UUID or its legacy name.  In
addition, some commands can accept a named bookmark that references the
endpoint.  Use the *bookmark-add* command to create a bookmark.


== OPTIONS


*--gc*::

Create a Globus Connect Personal endpoint and print a setup key.  The setup
key is used to finalize installation of the Globus Connect client software.

*--sharing* 'ENDPOINT/DIRECTORY/'::

Create a Shared Endpoint.  The specified 'ENDPOINT' is the host endpoint, and
the specified 'DIRECTORY' will be the root directory.  
'ENDPOINT' may be a bookmark.


*--s3*::

(BETA) Create an endpoint backed by an Amazon S3 bucket.  This requires a
Managed Endpoint subscription (the *--managed-endpoint* option is required).


*--managed-endpoint*::

This option makes the endpoint a managed endpoint.  This option is required if
the *--s3* option is specified. This option is not permitted with the
*--sharing* option.
+
The *--subscription* option may be used to specify the subscription UUID to
use.   If *--subscription* is not specified, and the user is authorized to add
managed endpoints under only a single subscription, that subscription UUID is
used automatically.


*--subscription* 'UUID'::

Specifies the subscription ID to use with *--managed-endpoint*.


== EXAMPLES

Create a gridftp endpoint called "My Endpoint".  Then, using the endpoint's
global ID, add a server, specifying the scheme, port, and subject:

----
$ endpoint-add -n "My Endpoint"
(prints "Endpoint ID: 55c27fe2-572b-11e5-84dd-22000bb3f45d")

$ server-add -p gsiftp://gridftp.test.com:2811 
    -s "/O=Grid/OU=Globus Test/CN=Test" 
    55c27fe2-572b-11e5-84dd-22000bb3f45d
----


Create a Globus Connect Personal endpoint called "My Laptop" and receive a setup
code:

----
$ endpoint-add --gc -n "My Laptop"
(prints the setup code)
----

== EXIT STATUS

*endpoint-add* will fail to create an endpoint if an endpoint with the same
name already exists.  
