---
full_title: "Command Line Interface (CLI)"
---

= Command Line Interface (CLI)
:revdate: April 6, 2017

[doc-info]*Last Updated: {revdate}*

This CLI provides a convenient shell interface to link:https://globus.org[Globus] APIs, including the Transfer API and the Globus Auth API.

Documentation for the APIs is available at https://docs.globus.org

You can always view CLI help by passing the '–help' flag to a command. That will show you any subcommands and options supported by that command.

Source code is available at https://github.com/globus/globus-cli

== Installation
The Globus CLI is maintained as a python package, built on the link:https://globus.github.io/globus-sdk-python[Globus Python SDK]. Like the SDK, it therefore requires link:https://www.python.org/[Python] 2.7+ or 3.3+. If a supported version of Python is not already installed on your system, see this link:http://docs.python-guide.org/en/latest/starting/installation/[Python installation guide].

=== For macOS Users
For *macOS*, you must install pip first:

----terminal
which pip || sudo easy_install pip
----terminal

=== For All Platforms
To install, run the following commands:

----terminal
which virtualenv || sudo pip install virtualenv
virtualenv "$HOME/.globus-cli-virtualenv"
source "$HOME/.globus-cli-virtualenv/bin/activate"
pip install globus-cli
deactivate
export PATH="$PATH:$HOME/.globus-cli-virtualenv/bin"
echo \'export PATH="$PATH:$HOME/.globus-cli-virtualenv/bin"' >> "$HOME/.bashrc"
----terminal

This will install the CLI and its dependencies into `$HOME/.globus-cli-virtualenv`, and add it to your shell.

See that the CLI is installed:

----terminal
globus --help
----terminal

=== Note on Other Shells

If you shell is not Bash, you will have to add `export PATH="$PATH:$HOME/.globus-cli-virtualenv/bin"` to your shell's initialization file.

=== Updating and Removing
For more info, see the instructions on link:#updating_amp_removing_the_cli[Updating and Removing CLI Versions].

== Getting Started
Installing the `globus-cli` python packge will provide you with the `globus` command. However, most CLI commands will require authentication to Globus services, so start out by getting logged in:

----terminal
$ globus login
[comment]## follow instructions to get setup#
----terminal

You can check that you can correctly authenticate to the Globus APIs with two quick commands.

First, check that you can access Globus Auth:

----terminal
$ globus get-identities \'go@globusid.org'
[output]#ID                                   | Full Name      | Username        | Organization | Email Address
------------------------------------ | -------------- | --------------- | ------------ | ------------------
c699d42e-d274-11e5-bf75-1fc5bf53bb24 | www.globus.org | go@globusid.org | Globus       | noreply@globus.org#
----terminal

Your output should be the same as above. If you are not authenticated, you will see a message similar to:

----terminal
$ globus get-identities \'go@globusid.org'
[output]#Globus CLI Error: A GLobus API Error Occurred.
HTTP status:      401
code:             UNAUTHORIZED
message:          Call must be authenticated#
----terminal

Next, check that you can reach the Globus Transfer API:

----terminal
[comment]## --filter-owner-id is the ID of \'go@globusid.org', fetched above#
$ globus endpoint search \'Globus Tutorial Endpoint' \
    --filter-owner-id \'c699d42e-d274-11e5-bf75-1fc5bf53bb24'
[output]#Owner           | ID                                   | Display Name
--------------- | ------------------------------------ | ---------------------------
go@globusid.org | ddb59aef-6d04-11e5-ba46-22000b92c6ec | Globus Tutorial Endpoint 1
go@globusid.org | ddb59af0-6d04-11e5-ba46-22000b92c6ec | Globus Tutorial Endpoint 2
go@globusid.org | cf9bcaa5-6d04-11e5-ba46-22000b92c6ec | Globus S3 Tutorial Endpoint#
----terminal

If you are not authenticated, you will get an error like the following:

----terminal
$ globus endpoint search \'Globus Tutorial Endpoint' \
    --filter-owner-id \'c699d42e-d274-11e5-bf75-1fc5bf53bb24'
[output]#Globus CLI Error: A Transfer API Error Occurred.
HTTP status:      401
request_id:       1AghTj1F6
code:             AuthenticationFailed
message:          Token is not active#
----terminal

Now we have the endpoint IDs for the tutorial endpoints, and can do a test directory listing:

----terminal
$ globus ls \'ddb59aef-6d04-11e5-ba46-22000b92c6ec:/'
[output]#home
mnt
not shareable
share#
----terminal

Start exploring the CLI!

Use globus `list-commands` to see all of the commands in the CLI, and to get more detailed help for a specific information on a command, run that command with the `--help` flag.

== Updating & Removing the CLI
=== Update
To update your version of the CLI to the latest:

----terminal
source "$HOME/.globus-cli-virtualenv/bin/activate"
pip install -U globus-cli
deactivate
----terminal

=== Uninstall
To remove the CLI:

----terminal
rm -r "$HOME/.globus-cli-virtualenv"
----terminal

You should also edit your `$HOME/.bashrc` and remove the line that reads `export PATH="$PATH:$HOME/.globus-cli-virtualenv/bin"`.

== Globus CLI Examples
For CLI examples, see link:using-the-cli[Using The CLI].


'''
== Hosted Command Line Interface

[doc-info]*Last Updated: May 12, 2016*

You will need an SSH key in order to access the Globus command line interface (CLI). *If you don't already have an SSH key, instructions for creating one are available link:https://docs.globus.org/faq/command-line-interface/#how_do_i_generate_an_ssh_key_to_use_with_the_globus_command_line_interface[here].*

Once you have an SSH key, follow the directions below to associate your SSH key with your Globus account:

. Go to link:https://globusid.org[globusid.org].
. Sign in with your Globus ID account and select "link:https://www.globusid.org/keys[manage SSH and X.509 keys]".
. Click "link:https://www.globusid.org/keys/add[Add a New Key]".
. Enter a descriptive name in the "Alias" field.
. Select "SSH Public key" and copy & paste your public key into the "body" field. Note: On a Mac OS X or Linux/Unix system, your key is usually found in ~/.ssh/id_rsa.pub.
. Click "Add Key" to save.

It will take a few minutes for the SSH key to propagate through the system. You may then access the CLI by typing:

----terminal
$ ssh [input]#<globus_username>#@cli.globusonline.org
[output]#Welcome to globus.org, <globus_username>. Type \'help' for help.#
$ _
----terminal

NOTE: If you receive a "permission denied" error, please ensure that your key files have permissions set to read-only (e.g. on Linux/Mac, run: +chmod 400 ~/.ssh/id_*+)

// For more information about using the CLI, see the guide to link:using-the-cli[Using the CLI] and link:using-the-cli#cli_beyond_the_basics[CLI: Beyond the basics].

=== [text-right next-link]#Next: link:using-the-cli[Using the CLI]#
