---
full_title: "Getting started with the Command Line Interface (CLI)"
---

= Getting started with the Command Line Interface (CLI)
:imagesdir: .
:revdate: May 12, 2016

[doc-info]*Last Updated: {revdate}*

NOTE: This page refers to the current Globus CLI which uses a restricted shell. We are in the process of moving to a different CLI that uses python scripts. For more information on the new CLI and to experiment with a beta version please see https://globus.github.io/globus-cli/.

You will need an SSH key in order to access the Globus command line interface (CLI). *If you don't already have an SSH key, instructions for creating one are available link:https://docs.globus.org/faq/command-line-interface/#how_do_i_generate_an_ssh_key_to_use_with_the_globus_command_line_interface[here].*

Once you have an SSH key, follow the directions below to associate your SSH key with your Globus account:

. Go to link:https://globusid.org[globusid.org].
. Sign in with your Globus ID account and select "link:https://www.globusid.org/keys[manage SSH and X.509 keys]".
. Click "link:https://www.globusid.org/keys/add[Add a New Key]".
. Enter a descriptive name in the "Alias" field.
. Select "SSH Public key" and copy & paste your public key into the "body" field. Note: On a Mac OS X or Linux/Unix system, your key is usually found in ~/.ssh/id_rsa.pub.
. Click "Add Key" to save.

It will take a few minutes for the SSH key to propagate through the system. You may then access the CLI by typing:

----terminal
$ ssh [input]#<globus_username>#@cli.globusonline.org
[output]#Welcome to globus.org, <globus_username>. Type \'help' for help.#
$ _
----terminal

NOTE: If you receive a "permission denied" error, please ensure that your key files have permissions set to read-only (e.g. on Linux/Mac, run: +chmod 400 ~/.ssh/id_*+)

// For more information about using the CLI, see the guide to link:using-the-cli[Using the CLI] and link:cli-beyond-basics[CLI: Beyond the basics].

=== [text-right next-link]#Next: link:using-the-cli[Using the CLI]#
