---
full_title: "Installing the Command Line Interface (CLI)"
short_title: "Installation"
---

= Installing the Command Line Interface (CLI)
:revdate: April 10, 2017

[doc-info]*Last Updated: {revdate}*

The Globus CLI is maintained as a python package, built on the link:https://globus.github.io/globus-sdk-python[Globus Python SDK]. Like the SDK, it therefore requires link:https://www.python.org/[Python] 2.7+ or 3.3+. If a supported version of Python is not already installed on your system, see this link:http://docs.python-guide.org/en/latest/starting/installation/[Python installation guide].

== For macOS Users
For *macOS*, you must install pip first:

----terminal
which pip || sudo easy_install pip
----terminal

== For All Platforms
To install, run the following commands:

----terminal
which virtualenv || sudo pip install virtualenv
virtualenv "$HOME/.globus-cli-virtualenv"
source "$HOME/.globus-cli-virtualenv/bin/activate"
pip install globus-cli
deactivate
export PATH="$PATH:$HOME/.globus-cli-virtualenv/bin"
echo \'export PATH="$PATH:$HOME/.globus-cli-virtualenv/bin"' >> "$HOME/.bashrc"
----terminal

This will install the CLI and its dependencies into `$HOME/.globus-cli-virtualenv`, and add it to your shell.

See that the CLI is installed:

----terminal
globus --help
----terminal

== Note on Other Shells

If you shell is not Bash, you will have to add `export PATH="$PATH:$HOME/.globus-cli-virtualenv/bin"` to your shell's initialization file.

== Updating and Removing
For more info, see the instructions on link:../#updating_amp_removing_the_cli[Updating and Removing CLI Versions].