= Using the Command Line Interface (CLI)
:toc:
:toc-placement: manual
:toclevels: 1
:toc-title:
:revdate: May 12, 2016

[doc-info]*Last Updated: {revdate}*

This guide provides a brief introduction to the Globus command-line interface (CLI). Additional CLI features are discussed in link:../cli-beyond-basics[CLI: Beyond the Basics].

'''
toc::[]

== Prerequisites
To use the CLI you must have a link:http://www.globus.org/SignUp[Globus account] with ssh access enabled. To enable your account for ssh access you must add your ssh public key to your Globus account by link:https://www.globus.org/account/ManageIdentities[visiting the Manage Identities page] and clicking "add linked identity", followed by "Add SSH Public Key". If you do not have an ssh key, follow the directions link:../../faq/command-line-interface/#how_do_i_generate_an_ssh_key_to_use_with_the_globus_command_line_interface[here] to create one.

== CLI Structure
There is no need to install custom client software. CLI users interact with Globus via a secure shell. The general structure of a CLI request is:

----terminal
$ ssh [input]#<username>#@cli.globusonline.org [input]#<command> <options> <params>#
----terminal

where: [uservars]#<username># is your Globus user name, [uservars]#<command># is the Globus command to execute, [uservars]#<options># are the options available for [uservars]#<command>#, and [uservars]#<params># are the parameters passed to [uservars]#<command>#. If desired, gsissh can be used in place of ssh.

== File Transfer
The Globus transfer service provides the +transfer+ command for moving files.

All Globus accounts are provisioned with two endpoints for exploratory use, so as soon as you have an account you should be able to transfer [uservars]#/share/godata/file1.txt# from endpoint [uservars]#go#ep1# to your home directory on [uservars]#go#ep2#, as shown below by user [uservars]#demodoc#:

----terminal
$ ssh [input]#demodoc#@cli.globusonline.org transfer -- [input]#go#ep1:/share/godata/file1.txt go#ep2:\~/myfile.txt#
[output]#Task ID: 9be793ca-5983-12e6-c030-22100b92c261#
$ ssh [input]#demodoc#@cli.globusonline.org status [input]#9be793ca-5983-12e6-c030-22100b92c261#
[output]#Task ID     : 9be793ca-5983-12e6-c030-22100b92c261
Request Time: 2016-10-03 16:08:23Z
Command     : transfer -- go#ep1/share/godata/file1.txt go#ep2/\~/myfile.txt
Label       : n/a
Status      : SUCCEEDED#
$ ssh [input]#demodoc#@cli.globusonline.org ls [input]#go#ep2/~/#
[output]#myfile.txt#
----terminal

== Online Help
You can execute the +help+ command to view the current Globus CLI command set:

----terminal
$ ssh [input]#demodoc#@cli.globusonline.org help
[output]#Type \'<command> -h' for basic help on a command.
Type \'man <command>' for detailed help.

Task Management        Endpoint Management         Other
---------------        -------------------         -----
cancel                 acl-add                     echo 
details                acl-list                    help 
events                 acl-remove                  history
modify                 bookmark-add                identity-details
status                 bookmark-list               man    
wait                   bookmark-remove             profile
                       endpoint-activate           
Task Creation          endpoint-add                                       
-------------          endpoint-deactivate                                
delete                 endpoint-details                                   
rm                     endpoint-modify                                    
transfer               endpoint-remove                                    
                       endpoint-rename                                    
File Management        endpoint-role-add                                  
---------------        endpoint-role-list                                 
ls                     endpoint-role-remove                               
mkdir                  endpoint-search                                    
rename                 server-add                                         
                       server-list                                        
                       server-remove#
----terminal

In addition, +<command> -h+ displays a command syntax summary and +man <command>+ displays the command's manual page.

== Endpoint Activation
Activation is a Globus endpoint user authentication mechanism; it enables endpoint owners to determine who is transferring files. Transfers will only proceed when both the source and destination endpoints are activated. You can practice by activating the Globus endpoints:

----terminal
$ ssh [input]#demodoc#@cli.globusonline.org endpoint-activate [input]#go#ep1#
$ ssh [input]#demodoc#@cli.globusonline.org endpoint-activate [input]#go#ep2#
----terminal

In the following example user demodoc activates NERSC endpoints using the +ssh -t+ option to prevent the passphrase from being echoed to stdout. Activation gives you authorization to the endpoint itself, but you still need to be authorized (have permissions) to the given resources on an endpoint before you can access them through Globus. Being authorized to access an endpoint is separate from being further authorized to access specific resources on and endpoint. Access to a given endpoint is entirely within the endpoint owner's control, so you must contact owners directly to obtain permission to use their endpoints.

----terminal
$ ssh -t [input]#demodoc#@cli.globusonline.org endpoint-activate [input]#nersc#carver#
[output]#Myproxy activation for endpoint: \'nersc#carver'
Using Myproxy server: \'nerscca.nersc.gov'
Enter username (Default: \'demodoc'):
Enter password:
Connection to cli.globusonline.org closed.#
$ ssh -t [input]#demodoc#@cli.globusonline.org endpoint-activate [input]#nersc#hopper#
[output]#Myproxy activation for endpoint: \'nersc#hopper'
Using Myproxy server: \'nerscca.nersc.gov'
Enter username (Default: \'demodoc'):
Enter password:
Connection to cli.globusonline.org closed.#
----terminal

Because [uservars]#\'carver'# and [uservars]#\'hopper'# have been activated using NERSC credentials, and the [uservars]#\'carver'# and [uservars]#\'hopper'# owners have authorized the user to access their endpoints, [uservars]#demodoc# is able to transfer a file:

----terminal
$ ssh [input]#demodoc#@cli.globusonline.org transfer -- [input]#nersc#carver/share/godata/file1.txt nersc#hopper/~/myfile.txt#
[output]#Task ID: 6356aa16-ed20-11df-aa30-1231350018b1#
----terminal

Now, user [uservars]#demodoc# activates the XSEDE endpoint [input]#\'stampede'#. The endpoint owner requires that the user go to the XSEDE OAuth service so that the user's password does not flow through Globus. This requires copying the URL shown in the terminal window to a web browser and following the prompts. Once the user has authenticated on XSEDE's OAuth server, a confirmation message is displayed in the terminal:

----terminal
$ ssh -t [input]#demodoc#@cli.globusonline.org endpoint-activate [input]##xsede#stampede##
[output]#\*\** Please use this URL to activate the endpoint(s) \*\**
https://www.globusonline.org/activate?ep=xsede%23stampede
\*\** Waiting... Press CTRL-C to cancel \*\**
\*\** Credential Received! \***
Connection to cli.globusonline.org closed.#
----terminal

An endpoint can also be activated using +gsissh+:

----terminal
$ gsissh [input]#demodoc#@cli.globusonline.org endpoint-activate -g [input]##ci#pads##
[output]#Credential Subject : /DC=org/DC=doegrids/OU=People/CN=Demo Docuser 595766/CN=576965990/CN=436543765
Credential Time Left: 11:59:54
Activating \'ci#pads'#
----terminal

Endpoints can also be activated inline by specifying the -g option with the +transfer+ command.

//Now that you've familiarized yourself with the CLI you can learn about some of the more powerful features available by reading the +man+ pages and the link:../cli-beyond-basics[Beyond the Basics guide]. As always, please feel free to link:https://www.globus.org/contact-us[contact us] if you have any questions.

=== [text-right next-link]#Next: link:../cli-beyond-basics[CLI: Beyond the Basics]#
