= Endpoint ACL Management
:toc:

Shared endpoints and S3 endpoints have an associated Access Control List
(ACL), and the API provides methods for reading, creating, updating and
deleting access rules in the ACL. The ACL for each endpoint can have at
most 100 access rules.

The owner of the endpoint always has full read and write access to the endpoint.
This is not included as a rule in the ACL, as it is always present and can't
be removed.

NOTE: Access is still subject to the local filesystem or S3 bucket
permissions. Globus ACLs provide an additional layer on top of local
permissions to simplify collaboration among Globus users.

== Document Type

All ACL management resources use the +access+ document type, which represents
a single access rule in the ACL.

NOTE: The id is now a string, to allow for more implementation options for
different types of access rules.

.Access Document Example
------------------------
{
    "DATA_TYPE": "access",
    "id": "12345",
    "principal_type": "user",
    "principal": "bob",
    "path": "/",
    "permissions": "r"
}
------------------------

=== Fields

[cols="1,1,8",options="header"]
|===================
| Field Name     | JSON Type | Description
| DATA_TYPE      | string
                 | Always has value "access" to indicate this document type.
| id             | string
                 | Globally unique id for this access rule.
| principal_type | string
                 | Type of principal that the rule applies to.
                   One of "user", "group", "email",
                   or "all_authenticated_users".
| principal      | string
                 | Name or id of the entity the rule applies to.
                   For type "user", this will be the Globus username.
                   For type "group", this will be the Globus group uuid.
                   For type "email", this will be a user's email address.
                   For type "all_authenticated_users", this is always an
                   empty string.
| path           | string
                 | Absolute path to a directory the access rule applies to.
                   The path must begin and end with a slash, and can't
                   contain un-normalized components "/../" or "/./".
                   GridFTP endpoints and shared endpoints hosted on GridFTP
                   endpoints also support home directory relative paths
                   beginning with "/~/". The path is limited to 2000
                   characters after encoding; in practice this means
                   2000 ascii characters and slightly less when unicode
                   is present and must be encoded.
| permissions    | string
                 | How much permission to grant the principal specified in
                   +principal_type+ and +principal+.
                   Either read-only, specified as "r",
                   or read-write, specified as "rw".
|===================


=== Access Rule Types

==== User Access Rule

User access rules apply to a single Globus user, indicated by Globus username.
The Nexus API provides resources for searching for users by full name and other
attributes.

==== Group Access Rule

Group access rules apply to all Globus users in a Globus group. Groups can
be created and discovered with the Nexus API. In the access rules, they
are indicated by the group id, not by the group name which is non necessarily
unique.

NOTE: Group ids are not validated; it is the responsibility of the client to
ensure the id is correct via the Group API in Nexus. Also if the group is
deleted, the rule will no longer provide any access but will stay in the ACL
until deleted by the user or client application.

==== All Authenticated Users Access Rule

These rules grant access to all Globus users. This can be used to share data
with everyone, but still allows monitoring of how many people are accessing
the data.

==== Email Access Rule

If you're trying to share with someone and don't know their Globus user name or
they don't yet have an account, you may create an "email" access rule. When an
"email" rule is created, Globus sends an email invitation to the email address
specified in principal. Once claimed, the access rule will be replaced by one
with +principal_type+ "user" and +principal+ equal to the username of the
Globus user who claimed the access rule. Each email access rule can be claimed
by only one Globus user account.

Before the email access rule is claimed, it can be manipulated like any other
access rule - the permission can be updated and it can be deleted. If deleted
before claimed, any attempt to claim it will fail with an error.

See the "Claim" section below for details on how to claim an email access rule.
In most cases this will be handled by the user following a link in the
invitation email to the http://www.globus.org[Globus] website.

If the recipient of an email access rule did not receive the email, it's
recommended that the old rule be deleted and a new rule for the same email
and path be added to resend a new invitation. This will revoke the original
invitation which is presumed to have been lost. If the user eventually receives
both, they should attempt to claim the newer one.

NOTE: (NICE TO HAVE) enforce uniqueness on (endpoint, email,
path) for email access rules.


== Common Query Parameters

[cols="1,8",options="header"]
|===================
| Name   | Description
| fields | Comma separated list of fields to include in the response. This can
           be used to save bandwidth on large list respones when not all
           fields are needed.
| format | "json" or "html". Note that the "html" format is subject to change
           and should not be relied upon for programs. It is used to render
           the self-hosted, auto-generated API documentation.
|===================


== Common Errors

NOTE: Current codes are more messy. TODO: update this with the actual codes used
today, and possibly another section with what we want them to be long term.

[cols="1,1,8",options="header"]
|===================
| Code              | HTTP Status  | Description
| EndpointNotFound  |404  | If <endpoint_name> not found
| AccessRuleNotFound|404  | If access rule specified by <id> is not found
| InvalidPath       |400  | If the path specified in an access rule is not
                            valid or too long.
| Conflict          |409  | If <endpoint_name> does not support ACLs.
                            See the +acl_available+ field of +endpoint+ to
                            determine if an endpoint supports ACLs.
| PermissionDenied  |403  | If you do not have permissions to view or modify
                            ACLs on <endpoint_name>.
|===================


== Operations

=== Read All

Get the list of access rules in the ACL for a specified endpoint.

[cols="h,5a"]
|============
| URL
| /endpoint/<endpoint_name>/access_list

| Method
| GET

| Response Body |
------------------------------------
{
    "length": 2,
    "endpoint": "alice#myshare",
    "DATA": [
        {
            "DATA_TYPE": "access",
            "principal_type": "user",
            "path": "/",
            "principal": "bob",
            "id": "12345",
            "permissions": "r"
        },
        {
            "DATA_TYPE": "access",
            "principal_type": "group",
            "path": "/project1",
            "principal": "a2e662ac-d4bc-4ab7-aceb-8a12d2205326",
            "id": "743565",
            "permissions": "rw"
        }
    ],
    "DATA_TYPE": "access_list"
}
------------------------------------
|============


=== Read One

Get a single access rule for a specified endpoint by id.

[cols="h,5a"]
|============
| URL
| /endpoint/<endpoint_name>/access/<id>

| Method
| GET

| Response Body | Access document (see above).
|============


=== Create

Create a new access rule. The response contains the id of the newly created
rule in the +access_id+ field.

[cols="h,5a"]
|============
| URL
| /endpoint/<endpoint_name>/access

| Method
| POST

| Request Body | Access document to add to the endpoint's ACL (see above).
| Response Body|
---------------------------------------------------
{
    "code": "Created",
    "resource": "/endpoint/epname/access",
    "DATA_TYPE": "access_create_result",
    "request_id": "abc123",
    "access_id": 12345,
    "message": "Access rule created successfully."
}
---------------------------------------------------
|============

==== Errors

[cols="1,1,8",options="header"]
|===================
| Code     | HTTP Status | Description
| Conflict | 409   | If the endpoint ACL already has the maximum of 100 access
                     rules.
| Conflict | 409   | (NICE TO HAVE) If an +email+ access rule with the same
                     (+principal+, +path+) already exists in the endpoint's
                     ACL.
|===================


=== Update

Update the permissions on an existing access rule. Other fields (besides
+DATA_TYPE+ which must always be present) may be omitted. If the id is present
it must match the id in the URL.

NOTE: This may support updating +path+ or other fields in the future, so
clients should make sure to use the correct value for the other fields
or omit them entirely.

NOTE: If an +email+ access rule has been claimed since the client fetched
it and become a +user+ access rule, this will update the +user+ access rule,
which has the same id. Because the other fields are ignored, no error will
be raised if they are included in the request, even though they no longer
match.

[cols="h,5a"]
|============
| URL
| /endpoint/<endpoint_name>/access/<id>

| Method
| PUT

| Request Body
| Access document

| Response Body |
-------------------------------------------------------------------
{
    "message": "Access rule '123' permissions updated successfully",
    "code": "Updated",
    "resource": "/endpoint/user#ep1/access/123",
    "DATA_TYPE": "result",
    "request_id": "ABCdef789"
}
-------------------------------------------------------------------
|============


=== Delete

Delete a single access rule, specified by id.

NOTE: If an +email+ access rule has been claimed since the client fetched
it and become a +user+ access rule, this will delete the +user+ access rule,
which has the same id.

[cols="h,5a"]
|============
| URL
| /endpoint/<endpoint_name>/access/<id>

| Method
| DELETE

| Request Body  | Empty
| Response Body |
-------------------------------------------------------------------
{
    "message": "Access rule '123' deleted successfully",
    "code": "Deleted",
    "resource": "/endpoint/user#ep1/access/123",
    "DATA_TYPE": "result",
    "request_id": "ABCdef789"
}
-------------------------------------------------------------------
|============


=== Claim

Claim an email access rule as the authenticated user. The email access rule
will be converted to a user access rule. Returns the user access rule, with an
additional +endpoint_name+ field which can be used to redirect the user to
that endpoint with the access rule path displayed in a file browser.

Once claimed, the user who claimed the access rule can continue to call this
method and get the same success response. This can be used to generate
the redirect URL if the user loads the link from the email again
after claiming the access rule.

NOTE: The access rule id does not change when claiming, but the
+principal_type+ and +principal+ will change to "user" and
"<username of claimant>".

NOTE: The owner of the endpoint (creator of the email access rule)
can't claim it for themselves.

[cols="h,5a"]
|============
| URL
| /claim_access/<token>

| Method
| POST

| Response Body |
------------------------------------
{
    "DATA_TYPE": "claim_response",
    "endpoint_name": "alice#myshare",
    "id": "12345",
    "principal_type": "user",
    "principal": "bob",
    "path": "/",
    "permissions": "r"
}
------------------------------------
|============

==== Errors

[cols="1,1,8",options="header"]
|===================
| Code             | HTTP Status | Description

| Conflict | 409
| If <token> has already been claimed by a different user.

| Conflict | 409
| If the authenticated user is the endpoint owner.

| EndpointNotFound | 404
| If the endpoint containing the access rule has been deleted.

| AccessRuleNotFound | 404
| If the owner of the endpoint has deleted the access rule
  (basically revoking the email invitation).

| BadRequest | 400
| If <token> is invalid, e.g. if the user's email client
  corrupts it or if the end got chopped off. This won't
  catch all possible corruptions - AccessRuleNotFound
  may be returned in some cases.
|===================



== Change History

=== May 30

- List illegal path components in +path+ fields description
- Add PermissionDenied common error
- Make "all_authenticated_users" principal empty string instead of null
- Add note about not checking nexus group ids and deleted groups
- Remove claim error for token referencing non email acl
- Improve email acl description
- Misc wording improvements/typo fixes

=== May 29

- Mark uniqueness for email access rules as a "nice to have".

=== May 27

- Add Create
- Require uniqueness for email access rules on (ep, email, path).

=== May 16

- Make claim idempotent - if the user who claims the access rule calls again,
  return the same success result.
- Specify that the access rule id does not change when claiming. This makes
  the delete and update behavior simpler to understand and document.
- Change claim result to access rule with +endpoint_name+ added.
- Document behavior of operations delete and update email access rules in
  case of concurrent claim.
- Re-document NotFound errors for claim, which are not obvious based on the
  common errors because of the difference in URL structure.
- Use BadRequest for invalid tokens

=== May 14

- Change claim to accept a token as input, and not require the endpoint name
- Remove filtering on Read All, it's overly complex and nobody is using it
- Added note about 2000 character path limit and how encoding affects this

=== May 13

- Update Claim docs
- Add detailed description of each access rule type (especially email).
- Remove 'status' field
- Add Common Errors section
- Update Read All with filtering docs
