= Authorization

== Overview

All applications follow a basic pattern when accessing Globus-enabled resources
using OAuth 2.0.

At a high level, you'll need to follow four steps:

[qanda]
Register your app to receive credentials.::

Visit the link:https://auth.globus.org/p/projects[Client Registration Page] to obtain OAuth 2.0 credentials such
as a client ID and client secret that are used to identify your application to
Globus Auth.

Obtain one or more access tokens from Globus Auth::

Before your application can access private data on a Globus-enabled resource
server, it must obtain an `access token` that grants access to those resources. A
single access token is valid for a particular resource server's API, but it
can grant varying degrees of access to  APIs. A variable parameter called
`scope` controls the set of resources and operations that an access token
permits. During the access-token request, your
application sends one or more values in the scope parameter.  There are
several ways to make this request, and they vary based on the type of
application you are building. For example, a JavaScript application might
request an access token using a browser redirect, while an
application installed on a device that has no browser uses direct HTTP requests.
Some requests require an authentication step where the user logs in to Globus
Auth using one of their `identities`. After logging in, the user is asked whether they
are willing to grant the permissions that your application is requesting. This
process is called user consent.  If the user grants the permission, Globus Auth
sends your application an access token (or an
authorization code that your application can use to obtain an access token).
If the user does not grant the permission, the server returns an error.  It is
generally a best practice to request the minimum scopes your application needs
to properly function.

Send the access token to an API.::

After an application obtains an access token, it sends the token to a
resource server API in an HTTP authorization header. Access tokens are
valid only for a particular resource server and the set of operations and
resources described in the scope of the token request. For example, if an access
token is issued for the Globus Transfer API, it does not grant access to the
XSEDE User Profile API. You can, however,send the same access token to a
resource server multiple times for similar operations.

Refresh the access token, if necessary.::

Access tokens have limited lifetimes. If your application needs access to a
resource server beyond the lifetime of a single access token, it can obtain a
refresh token. A refresh token allows your application to obtain new access
tokens.

== Obtaining authorization - Supported OAuth2 Grant Types

Globus Auth Supports the following OAuth2 grant types (detailed below):

* link:https://tools.ietf.org/html/rfc6749#section-4.1[Authorization Code Grant] (Most secure, **preferred**)
* Dependent Token Grant (Custom extension grant, used by resource servers)
* link:https://tools.ietf.org/html/rfc6749#section-4.3[Resource Owner Password Credentials Grant] (Required by certain non web-based clients)
* link:https://tools.ietf.org/html/rfc6749#section-4.2[Implicit Grant] (Limited to specific, trusted apps)

These grants all share the same HTTP endpoints:

**Authorization:** https://auth.globus.org/v2/oauth2/authorization

**Token:** https://auth.globus.org/v2/oauth2/token

=== Authorization Code Grant (preferred)

link:https://tools.ietf.org/html/rfc6749#section-4.1[Authorization Code Grant]: For obtaining an access token, via
browser redirection, for a web server-based client to access a resource server.

**Preparing to start the OAuth 2.0 flow**

You will need:

- The client_id and client_secret from your client registration.

- The scopes your client is requesting.

**Redirecting the user to the OAuth 2.0 server**

Construct a URL for the OAuth2 authorization endpoint `https://auth.globus.org/v2/oauth2/authorization` with the following parameters:

[options="header"]
|==========================
|Parameter |Values |Description
|response_type| `code`| Determines whether Globus Auth returns an authorization code. For the authorization code grant, this value is always `code`
|client_id| The client ID you obtained when registering your client.| Identifies the client that is making the request.
The value passed in this parameter must exactly match the value issued for your client on  registration.
|redirect_uri| One of the redirect_uri values you registered for your client.| Determines where the response is sent.
The value of this parameter must exactly match one of the values listed for this client in the registration system. (including the http or https scheme, case, and trailing '/').
|scope| Space-delimited set of permissions that the application requests.| Identifies the access that your application is requesting.
The values passed in this parameter inform the consent screen that is shown to the user and the number of access tokens returned.
|state| Any string| Provides any state that might be useful to your application upon receipt of the response.
Whatever value you send here will be returned to your application unmodified. To mitigate against cross-site request forgery (CSRF), it
is strongly recommended to include an anti-forgery token in the state, and confirm it in the response. link:http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html[See here] for further suggestions on how to use the state parameter.
|access_type| online or offline| Indicates whether your application needs to access resources when the user is not present at the browser.
If access_type is offline, your application will be issued a refresh token along with the access token the first time it exchanges an authorization code for a token.
|============================

An example URL is shown below, with line breaks and spaces for readability.

 https://auth.globus.org/v2/oauth2/authorization?
   scope=urn%3Aglobus%3Aauth%3Ascope%3Aauth.globus.org%3Aview_identities+openid+email+profile
   state=security_token%3D138r5719ru3e1%26url%3Dhttps://oa2cb.example.com/myHome&
   redirect_uri=https%3A%2F%2Foauth2-login-demo.example.com%2Fcallback&,
   response_type=code&
   client_id=d430e6c8-b06f-4446-a060-2b6b2bc3e54a

After you create the request URL, redirect the user to it.

**Handling the OAuth 2.0 server response**

The OAuth 2.0 server responds to your application's access request by redirecting the user's browser
to the `redirect_uri` specified in the request.

If the user approves the access request, then the response contains an authorization code.
If the user does not approve the request, the response contains an error message.
All responses are returned to your application on the query string, as shown below:

An error response:

`https://oauth2-login-demo.example.com/callback?error=access_denied`

A successful authorization code response:

`https://oauth2-login-demo.example.com/callback?code=P7q7W91a-oMsCeLvIaQm6bTrgtp7`

IMPORTANT: If your response endpoint renders an HTML page, any resources on that page will be able to see the authorization
code in the URL. Scripts can read the URL directly, and all resources may be sent the URL in the Referer HTTP header.
Carefully consider if you want to send authorization credentials to all resources on that page (especially
third-party scripts such as social plugins and analytics). To avoid this issue, we recommend that the server
first handle the request, then redirect to another URL that doesn't include the response parameters.

After the web server receives the authorization code, it can exchange the authorization code for one or more access tokens.

To exchange an authorization code for an access token, POST to the `https://auth.globus.org/v2/oauth2/token` endpoint, with
an Authorization header containing an HTTP Basic Auth header for your client_id and client_secret, and including the
following field:

[options="header"]
|==================
|Field | Description
|code | The authorization code returned from the previous authorization request.
|redirect_uri | The same value you sent in the previous authorization request.
|grant_type | As defined in the OAuth 2.0 specification, this field must contain a value of `authorization_code`.
|===================

The actual request might look like the following:

    POST /v2/oauth2/token HTTP/1.1
    Host: auth.globus.org
    Content-Type: application/x-www-form-urlencoded
    Authorization: Basic NDFjYTIwM2QtNzcwMy00NDYxLWFiNGItNjVhNjA0YjE2NjE5OjxDTElFTlRfU0VDUkVUPg==

    code=P7q7W91a-oMsCeLvIaQm6bTrgtp7&
    redirect_uri=https://oauth2-login-demo.example.com/callback&
    grant_type=authorization_code

A successful response to this request contains the following fields:

[options="header"]
|==============
|Field | Description
|access_token | The token that can be used to access resources.
|scope | Space-separated list of scopes the access token authorizes.
|resource_server | The resource server for which the access_token token is intended.
|expires_in | The remaining lifetime of the access token.
|token_type | Identifies the type of token returned. At this time, this field
will always have the value bearer.
|refresh_token | A token that may be used to obtain a new access token. Refresh
tokens are valid until the user revokes access. This field is only present if
the authorization request asked for offline access.
|id_token | A JWT containing details about the user as defined in the
link:https://openid.net/specs/openid-connect-core-1_0.html#IDToken[OpenIDConnect specification.]
Note: Currently, this field is always included by default, but soon it will only be present if the
'openid' scope was requested during the authorization request. If your application requires an id_token
you SHOULD request openid scopes during the authorization request.
|state | The state parameter your client application provided during the authorization request.
|other_tokens | If the client requested scopes that span multiple resource servers, this field will be present, and
it will contain an array of access token responses containing separate tokens for each resource server.
|===============

NOTE: The scope named first in the authorization request (excepting openid scopes)
      will determine the access token returned in the top level of the response object.

A successful response is returned as a JSON object, similar to the following:

    {
        "access_token": "tggaKq69-qJiDRHp5oPW_lllll5syWfZ...",
        "resource_server": "transfer.api.globus.org",
        "expires_in": 3600,
        "token_type": "bearer",
        "scope": "urn:globus:auth:scope:transfer.api.globus.org:monitor_ongoing",
        "refresh_token": "auqmwrC5qb841p9QsxqwbPgABuiDqUUJ",
        "id_token": "eyJ0eXAiOiJKV1QiLA0KICJh...",
        "state": "provided_by_client_to_prevent_replay_attacks",
        "other_tokens": [
            {
                "access_token": "E3SfxOvlvsQ49lTn6cA0RGfRXHcwy85q...",
                "resource_server": "auth.globus.org",
                "scope": "urn:globus:auth:scope:auth.globus.org:view_identities",
                "expires_in": 3600,
                "refresh_token": "IlLACxpsG53v2zIuGCNPkoJXSF8gHbu8",
                "token_type": "bearer"
            },
            {
                "access_token": "OCsTf8AMydkPXTsv4stzT2QK5MA_S3a3...",
                "resource_server": "groups.api.globus.org",
                "scope": "urn:globus:auth:scope:nexus.api.globus.org:groups",
                "expires_in": 3600,
                "refresh_token": "TgwS5_BEFLsZbED42-agjfcriH0-pIee",
                "token_type": "bearer"
            },
            {
                "access_token": "oreTykUqQZfXXMqa5Zr9GoHaJsyF1AGX...",
                "resource_server": "atmosphere.jetstream.xsede.org",
                "scope": "urn:globus:auth:scope:atmosphere.jetstream.xsede.org:manage_data",
                "expires_in": 3600,
                "refresh_token": "H-qpG4yMQqkfGLhwjHYy_73TY2PSSAVh",
                "token_type": "bearer"
            }
        ]
    }

=== Refresh Token Grant

If your application requires access beyond the lifetime of a single access token, it can request
offline access, and then use a refresh token to obtain fresh access tokens. Refresh tokens will
remain valid indefinitely if they are being used, but they expire after six months of inactivity.
They can also be explicitly revoked by a user.

POST request to https://auth.globus.org/v2/oauth2/token, with an HTTP Basic
Authorization header containing your client_id and client_secret.
The request must include the following parameters:

[options="header"]
|===================
|Field | Description
|refresh_token | The refresh token returned from the authorization code exchange.
|grant_type | As defined in the OAuth 2.0 specification, this field must contain a value of refresh_token.
|===================

Such a request will look similar to the following:

    POST /v2/oauth2/token HTTP/1.1
    Host: auth.globus.org
    Content-Type: application/x-www-form-urlencoded
    Authorization: Basic NDFjYTIwM2QtNzcwMy00NDYxLWFiNGItNjVhNjA0YjE2NjE5OjxDTElFTlRfU0VDUkVUPg==

    refresh_token=6BMfW9j53gdGImsiyUH5kU5RsR4zwI9lUVX-tqf8JXQ&
    grant_type=refresh_token

As long as the refresh_token has not expired or been revoked the response
includes a new access token. A response from such a request is shown below:

    {
      "access_token":"fFBGRNJru1FQd44AzqT3Zg...",
      "refresh_token": "6BMfW9j53gdGImsiyUH5kU5RsR4zwI9lUVX-tqf8JX",
      "expires_in":3920,
      "token_type":"Bearer",
    }

=== Implicit Grant

link:https://tools.ietf.org/html/rfc6749#section-4.2[Implicit Grant]: For obtaining an access token, via browser
redirection, for a Javascript client running in a browser.

Similar to the Authorization Code grant, except a token is returned directly to the browser.

This flow is not recommended, because it is less secure than the Authorization Code grant.

=== Resource Owner Password Credentials Grant

link:https://tools.ietf.org/html/rfc6749#section-4.3[Resource Owner Password Credentials Grant] : For obtaining an access
token for a non-browser-based client (e.g., command line, mobile, or
desktop application).

NOTE: This feature will only work with certain identity providers that are configured
      to support non-browser-based authentication based on username and password.

=== Verifying identity (via OpenID Connect ID Token)

Globus Auth's OAuth2 grants accept the following OpenID Connect scopes:

* openid: Requests that an OpenID Connect id_token be returned as part
of the
https://www.google.com/url?q=https://tools.ietf.org/html/rfc6749%23section-5.1&sa=D&ust=1459362629124000&usg=AFQjCNGUaPR7rbD_uRrLLMjM6Q-r9dlGxQ[OAuth2
Access Token Response], with the following claims:

** sub: The Globus Auth identity id of the effective identity of the
logged in Globus account. This effective may be the primary identity, or
the appropriate linked identity if this client requires an identity from
a particular provider.
** iss: The URL
"https://www.google.com/url?q=https://auth.api.globus.org&sa=D&ust=1459362629125000&usg=AFQjCNEqtyMLYHS0ZeGw9hPoQjTydW7P8Q[https://]https://www.google.com/url?q=https://auth.api.globus.org&sa=D&ust=1459362629126000&usg=AFQjCNHyBtz4q2_ZNRvmMxFc4Y8QwQu8CA[auth.globus.org]"
** at_hash: Per OpenID Connect specification.
** aud: Per OpenID Connect specification.
** exp: Per OpenID Connect specification.
** iat: Per OpenID Connect specification.
** nonce: Per OpenID Connect specification.

* email: Adds the following claim in the id_token:

** email: The email address associated with the identity provided in the
"sub" claim.

* profile: Adds the following claim in the id_token:

** name: The identity's full name (e.g. Jane Doe) in displayable form.
** preferred_username: The identity username for the effective identity
id provided by the ‘sub' claim.

These claims are being made by Globus Auth (iss), on behalf of an
identity provider, about an identity (sub, name, email) that has been
provisioned by the identity provider with Globus Auth, and authenticated
by the identity provider via Globus Auth.

In order to verify the signature of the id_token, you can use the our public
keys at https://auth.globus.org/jwk.json