---
menu_weight: 1
---

= Globus Auth Developer Guide
:toc:
:toclevels: 3
:numbered:

== Developing an Application Using Globus Auth

Developing an application that uses Globus Auth for authentication and/or authorization begins with registering an application client at TODO. Globus Auth supports registering two basic forms of clients:

- _Confidential clients_ are clients that are capable of keeping client credentials secret. An example of this would be an application that runs on a web server backend. Any client that _can_ be confidential _should_ be confidential for the protection of its users. Confidential clients must authenticate all calls to Auth as described here (TODO: Link)
- _Non-confidential_ or _native_ applications. Use this client type for CLI apps or other native applications. Native apps must use PKCE (see below).

=== Obtaining Authorization

Globus Auth is fully spec compliant OAuth 2 implementation. It is recommended that developers use an off-the-shelf OAuth 2 library (TODO: Link to libraries section, if that's a thing in adoc?). Below is a description of the basic authorization flow using the authorization code grant (https://tools.ietf.org/html/rfc6749#section-4.1).

1. Authorization request (https://tools.ietf.org/html/rfc6749#section-4.1.1). The application client constructs a link to an authorization page and directs the user to it. The url is `https://auth.globus.org/v2/oauth2/authorize` with the following URL encoded query params:
	- `client_id`. The UUID of the client application.
	- `redirect_uri`. The URI the user will be redirected back to for the authorization response. Must be pre-registered for this client.
	- `scope`. A space or comma separated list of scopes the application is requesting access to.
	- `state`. An opaque value that is returned to the client in the authorization response. The client should use this value to prevent cross-site request forgery as described in https://tools.ietf.org/html/rfc6749#section-10.12.
	- `response_type`. Value must be `code`.

If the application client is a native app the request must also contain a `code_challenge` and `code_challenge_method` as described in the PKCE section below.

The user is prompted to authenticate, and to consent to giving the client application access to the requested scopes if they have not previously consented.

2. Authorization response (https://tools.ietf.org/html/rfc6749#section-4.1.2). If the user successfully authenticates and consents they will be returned to the `redirect_uri` included in the authorization request, with the following included as URL encoded query params:
	- `code`. The authorization code the client application will use to exchange for access/refresh tokens.
	- `state`. The value the client provided in the authorization request.

3. Access token request (https://tools.ietf.org/html/rfc6749#section-4.1.3). To exchange the `code` for an access token, a `POST` is made to `https://auth.globus.org/v2/oauth2/token` with the following URL encoded query params:
	- `grant_type`. Value must be `authorization_code`.
	- `code`. The code received in the authorization response.
	- `redirect_uri`. Must be identical to the value sent in the authorization request.
	- `client_id`. Once again, the UUID of the client application.

If the application client is confidential it must authenticate this call using its client credentials. If the client is a native app it must instead include a `code_verifier` parameter as described in the PKCE section below.

4. Access token response (https://tools.ietf.org/html/rfc6749#section-4.1.4). TODO: describe response including our custom extensions.

=== Client Authentication

=== PKCE

== Integrating Globus Auth Features

E.g, identity linking

== Developing a Resource Server

== Adding an Identity Provider
Supported protocols: …

Identity providers must supply a provider_specific_id (explain what that’s all about)

== Publically Available Scopes
auth:view_identities
transfer:all
offline_acces
Openid+email+profile

== Features for Managing Flows
 authentication_hint, login_hint, etc

== Identity Sets

=== The Globus Auth Identity Set Model at a Glance

=== Does My App Need to Set-Aware?
 
== Managing Projects
Admins are co-equal

== Handling Tokens

=== Caching

== Libraries and Resources
 
=== Using the Globus SDK
 
=== OAuth2 Libraries

=== Sample Applications Using Globus Auth
