---
menu_weight: 1
---

= Globus Auth Developer Guide
:toc:
:toclevels: 3
:numbered:

== Developing an Application Using Globus Auth

A Globus Auth App is used to authenticate users and/or to obtain access to other services. At a very high level, the development cycle consists of:

1. Registering an application client at https://developers.globus.org.
2. Obtaining authorization. Applications request access to _scopes_ using a standard OAuth 2 flow.
3. Using tokens to authenticate to services.

=== Registering an Application

For the most part the process of registering an application is explained on the registration page itself (TODO: Make this actually be true). However, one aspect that is worth highlighting is the two basic kinds of clients that are available for registration:

- _Confidential clients_ are clients that are capable of keeping client credentials secret. An example of this would be an application that runs on a web server backend. Any client that _can_ be confidential _should_ be confidential for the protection of its users. Confidential clients must authenticate all calls to Auth as described here (TODO: Link). This is the type of application you will get if you leave the _Will be used by a native application_ checkbox unchecked.
- _Non-confidential_ or _native_ applications. Use this client type for CLI apps or other native applications. Native apps must use PKCE (see below). This is the type of client you will get if you check the _Will be used by a native application_ checkbox.

=== Obtaining Authorization

Globus Auth is fully spec compliant OAuth 2 implementation. It is recommended that developers use an off-the-shelf OAuth 2 library (TODO: Link to libraries section, if that's a thing in adoc?). Below is a description of the basic authorization flow using the authorization code grant (https://tools.ietf.org/html/rfc6749#section-4.1).

1. Authorization request (https://tools.ietf.org/html/rfc6749#section-4.1.1). The application client constructs a link to an authorization page and directs the user to it. The URL is `https://auth.globus.org/v2/oauth2/authorize` with the following URL encoded query params:
	- `client_id`. The UUID of the client application.
	- `redirect_uri`. The URI the user will be redirected back to for the authorization response. Must be pre-registered for this client.
	- `scope`. A space or comma separated list of scopes the application is requesting access to. If refresh tokens are needed, include the `offline_access` scope.
	- `state`. An opaque value that is returned to the client in the authorization response. The client should use this value to prevent cross-site request forgery as described in https://tools.ietf.org/html/rfc6749#section-10.12.
	- `response_type`. Value must be `code`.
	- If the application client is a native app the request must also contain a `code_challenge` and `code_challenge_method` as described in the PKCE section below.
	- All parameters must be URL encoded.
	- Example of an app requesting access to Globus Transfer and the Globus Auth Identities API with refresh tokens: `https://auth.globus.org/v2/oauth2/authorize?client_id=69ba5e62-7285-45db-952d-e0bb73b5eac7&scope=urn%3Aglobus%3Aauth%3Ascope%3Atransfer.api.globus.org%3Aall%20urn%3Aglobus%3Aauth%3Ascope%3Aauth.globus.org%3Aview_identities%20offline_access&response_type=code&redirect_uri=https%3A%2F%2Fwww.example.org%2Fmy_app%2Flogin&state=g6l14b2xlgx4dtce8d2ja714i`

2. The user is prompted to authenticate, and to consent to giving the client application access to the requested scopes if they have not previously consented (if they have already consented this screen is bypassed).

3. Authorization response (https://tools.ietf.org/html/rfc6749#section-4.1.2). If the user successfully authenticates and consents they will be returned to the `redirect_uri` included in the authorization request, with the following included as URL encoded query params:
	- `code`. The authorization code the client application will use to exchange for access/refresh tokens.
	- `state`. The value the client provided in the authorization request.

4. Access token request (https://tools.ietf.org/html/rfc6749#section-4.1.3). To exchange the `code` for an access token, a `POST` is made to `https://auth.globus.org/v2/oauth2/token` with the following URL encoded query params:
	- `grant_type`. Value must be `authorization_code`.
	- `code`. The code received in the authorization response.
	- `redirect_uri`. Must be identical to the value sent in the authorization request.
	- `client_id`. Once again, the UUID of the client application.
	- If the application client is confidential it must authenticate this call using its client credentials. If the client is a native app it must instead include a `code_verifier` parameter as described in the PKCE section below. TODO: Link to relevant sections.

5. Access token response (https://tools.ietf.org/html/rfc6749#section-4.1.4). The token response is described in the following section.

=== Using Tokens

The following is an example response from the request above: (TODO: Formatting)

{
	"access_token": <access-token-for-globus-transfer>,
	"id_token": <id-token>,
	"expires_in": 172800, 
	"resource_server": "transfer.api.globus.org", 
	"token_type": "Bearer", 
	"state": "g6l14b2xlgx4dtce8d2ja714i",
	"scope": "urn:globus:auth:scope:transfer.api.globus.org:all",
	"refresh_token": <refresh-token-for-globus-transfer>,
	"other_tokens": [
		{
			"access_token": <access-token-for-globus-auth>,
			"expires_in": 172800,
			"resource_server": "auth.globus.org",
			"token_type": "Bearer",
			"state": "g6l14b2xlgx4dtce8d2ja714i",
			"scope": "urn:globus:auth:scope:auth.globus.org:view_identities",
			"refresh_token": <refresh-token-for-globus-auth>}
	],
}

Globus Auth, unlike most OAuth 2 implementations, supports providing access to multiple different resource servers, and can therefore return multiple access/refresh tokens in the same response. In order to conform to standards the token response for the first requested scope looks like that of any other standards compliant OAuth 2 server, and any additional tokens are included in the `other_tokens` array.

After receiving the response the application client should do the following:
- Verify that it received the expected scopes.
- Verify that the `state` parameter matches what was sent in the authorization request.
- Store the token(s) for future use, along with their expiry time. Application clients should always inspect the `expires_in` value (in seconds) of all received tokens; it may differ from one request to the next.

Access tokens are then used to authenticate against services by including them in the `Authorization` header of HTTP requests, e.g:

`Authorization: Bearer <access-token-for-globus-transfer>`

When an access token is nearing its expiry time the application needs to retrieve a new one, either by performing another authorization flow as described above (except this time the user won't be prompted for consent again), or by performing a refresh token grant. TODO: Describe refresh token grant.

Refresh tokens are long lived credentials and should never be sent over the wire except when doing a refresh token grant against Globus Auth.

TODO: Link to section explaining id tokens.

=== Client Authentication

=== PKCE

== Integrating Globus Auth Features

E.g, identity linking

== Developing a Service



== Adding an Identity Provider
Supported protocols: …

Identity providers must supply a provider_specific_id (explain what that’s all about)

== Publically Available Scopes
auth:view_identities
transfer:all
offline_acces
openid+email+profile

== Features for Managing Flows
 authentication_hint, login_hint, etc

== Identity Sets

=== The Globus Auth Identity Set Model at a Glance

=== Does My App Need to Set-Aware?
 
== Managing Projects
Admins are co-equal

== Handling Tokens

=== Caching

== Libraries and Resources
 
=== Using the Globus SDK
 
=== OAuth2 Libraries

=== Sample Applications Using Globus Auth
