= Auth API Reference
:toc:

== Contents

* link:general[General] -
  general information about the Auth API
* link:endpoint_activation[Endpoint Activation] -
  associate user credentials with an endpoint
* link:task_submit[Task Submission] - submit transfer and
  delete tasks
* link:task[Task Management] - monitor and cancel
  background transfer and delete tasks
* link:file_operations[File Operations] - foreground filesystem
  operations, including directory listing (ls), creating directories (mkdir),
  and renaming files (rename)
* link:endpoint[Endpoint Management] -
  create, update, and delete endpoint definitions and servers
* link:endpoint_search[Endpoint Search] -
  find endpoints matching a search query, by display_name and other
  endpoint fields
* link:endpoint_roles[Endpoint Roles] -
  control which users have different administrator rights or 'roles' on an
  endpoint
* link:endpoint_bookmarks[Endpoint Bookmarks] -
  list, create, rename, and delete bookmarks for an endpoint and path
* link:acl[Endpoint ACL Management] -
  view and modify access rules on endpoints that support an ACL
* link:advanced_endpoint_management[Advanced Endpoint Management] -
  endpoint administrators can monitor and operate on tasks to and from their
  endpoints
* link:change_history[Change History]

== General

The Globus Auth API has a set of common conventions that it uses
throughout, as described in the following subsections.

=== Base URL

All Globus Auth API interactions are
link:https://tools.ietf.org/html/rfc6749#section-1.6[TLS-secured] with the host auth.globus.org.
Therefore, URLs to Globus Auth resources begin with https://auth.globus.org/.

=== Versioning

All public Globus Auth resource URL paths are prefixed by `/v2/`. For
example:

    GET https://auth.globus.org/v2/api/identities/2982f207-04c0-11e5-ac60-22000b92c6ec

Globus Auth API clients can assume the syntax and semantics of the
resources defined in this specification will not change in an
incompatible manner. However, the resources may be extended, as long as
such extensions are backward compatible. For example:

* The Globus Auth API may be extended with additional resources.
* Resource URLs may be extended to support additional query parameters.
* JSON documents used by resource requests and responses may contain
additional fields. Clients should ignore any fields they do not
recognize.

Clients SHOULD NOT use Globus Auth resource URL paths that are prefixed by
`/p/`, as these are private, internal resources that may change at any
time without warning.

(Globus Auth Version 1 was an API known as "Globus Nexus" or "Globus
Graph", which was only available for select uses outside Globus.)

=== API Endpoints

Unless otherwise noted, all REST calls are authenticated using the
HTTP Authorization header. Clients will need to include either a
link:https://tools.ietf.org/html/rfc6750[Bearer Token] (i.e. access token)
or link:https://tools.ietf.org/html/rfc7617[Basic Auth] credentials in the
Authorization header of the request.

Globus Auth will return will return HTTP 401 Unauthorized for any call
that is missing the relevant header information, or if the access token
has expired or been revoked, unless it is specifically noted that the
call requires no authorization or some other form of authorization. It
is recommend that resource owner APIs do the same.

==== Including associated resources ("side-loading")

A resource request can have an "include" query parameter, followed by a
list of fields that specify what associated resources should be included
in the response. For example:

    GET /v2/api/identities/2982f207-04c0-11e5-ac60-22000b92c6ec?include=identity_provider

will respond not just with requested identity resource document, but
also the associated identity_provider resource document.

==== CORS

https://auth.globus.org supports link:http://en.wikipedia.org/wiki/Cross-origin_resource_sharing[CrossOrigin Resource Sharing (CORS)]
to allow any client to directly access the Globus Auth API.

//URL trailing /
//^^^^^^^^^^^^^^^^^^^^^

//A trailing / on a URL path is not significant. Globus Auth will
//interpret URLs with and without a trailing / in the same way.

=== /v2/api/identities resources

Resource type: identity

[options="header"]
|===================
|Field | Type | Description
|id | UUID | Globus Auth issued identity id, guaranteed to uniquely identify a single
identity, even if the identity username associated with the identity is
changed or re-used by the identity provider. An id will never be
re-used. *This field is visible to all clients.*
|username|String|The username of the identity.

The identity username is guaranteed to be unique amongst all Globus Auth
identities at any given time. However, since identity providers can
change or re-use usernames the following caveats apply:

* The identity username associated with a given identity id is NOT
guaranteed to remain constant over time.
* A single identity username MAY be associated with different identity
ids over time

If identity category is ssh-public-key, the identity username is the
hash of the public key. (TBD: Define hash algorithm and encoding.)
Otherwise, the identity username is defined by the issuing identity
provider.

*This field is visible to all clients.*

|status | String enum | One of:

* "unused", indicating that no user has proven ownership of this
identity by authenticating with it. Resource servers may assign
permissions to an unused identity. (See GET /v2/api/identities/<name>.)
* "used", indicating that a user has proven ownership of this identity.
The identity will typically, but not necessarily, be associated with a
Globus Account.
* `private`, indicicating that the user has restricted visibility of their
identity.
* `closed", indicating that this identity is no longer valid, typically
because the provider has revoked it and perhaps reused the identity
username. When an identity is closed, it will be removed from all Globus
accounts, and end-users can no longer authenticate with this identity.
Resource servers MAY remove any permissions associated with a closed
identity, though since it is removed from all Globus accounts it will
never be included in a token's identities list, so will never result in
matching a permission.

|email | Email | String

Identity provider specified email address for this identity.

This email address may be used by Globus Auth, clients and resource
servers for email notifications related to this identity.

Globus Auth provides no guarantees about the email address, including
whether the email address has been verified, or if emails sent to this
address will be successfully delivered.

|name | String | Identity provider specified display name (e.g., user's full name) for
this identity.

|organization | String | The name of the organization this identity is associated with.
This may be set by the provider or, if the provider does not set it, by the user
themselves.
|==================================

==== GET /v2/api/identities/<id>

Responds with an identity resource type document for the identity with
the specified <id>.

The response may not include all fields, depending on the identity's
visibility policy.  However, the identity id, category, and name fields
are always visible to all clients.

==== GET /v2/api/identities?identity_ids=<list-of-identity-ids>

Returns a list of identity resource type documents for the comma
separated list of identity ids.

If the identity_id does not exist, it is not in the list…

An identity documents may not include all fields, depending on the
identity's visibility policy.

==== GET
/v2/api/identities?usernames=<list-of-identity-names>

Returns a list of identity resource type documents for the comma
separated list of identity ids.

WARNING: An identity username must not be used as the unique identifier
for an identity, because an identity provider may reuse an identity
username over time. Clients must always use an identity id as the unique
identifier when persisting an identity in its own records (e.g., in an access
control policy).

If a field in an identity resource is not visible to the client (e.g.,
due to that identity's visibility policy), that field will have a value
of null.

Example request:

    GET /v2/api/identities?usernames=webapptester1%40globusid.org,webapptester2%40globusid.org HTTP/1.1
    Host: auth.globus.org
    Authorization: Bearer A7oU1xJ8-ddvRiMf-ZFDvXb

Example response:

    {
      "included": {
        "identity_providers": [
          {
            "id": "41143743-f3c8-4d60-bbdb-eeecaba85bd9",
            "name": "Globus ID"
          }
        ]
      },
      "identities": [
        {
          "username": "webapptester1@globusid.org",
          "status": "used",
          "name": "Jane Tester",
          "id": "e9873f94-032a-11e6-afde-cb613ccc97a9",
          "identity_provider": "41143743-f3c8-4d60-bbdb-eeecaba85bd9",
          "organization": "Globus",
          "email": "webapptester1@example.com"
        },
        {
          "username": "webapptester2@globusid.org",
          "status": "private",
          "name": null,
          "id": "e987941c-032a-11e6-afdf-7b65304db5f1",
          "identity_provider": "41143743-f3c8-4d60-bbdb-eeecaba85bd9",
          "organization": null,
          "email": null
        }
      ]
    }

=== API for Resource Servers

Globus Auth provides a set of API resources for use only by resource
providers.

==== Token Introspection (POST /v2/oauth2/token/introspect)

This can only be used by a resource server, authorized using that
resource server's client identifier and client secret.

This resource conforms to the
link:https://www.google.com/url?q=https://tools.ietf.org/html/rfc7662&sa=D&ust=1459362629167000&usg=AFQjCNE4XOZ2Si4HXEsT5HWm_bwUCVKuhw[RFC
7662], OAuth 2.0 Token Introspection.

When a resource server receives a request from a client, it must
validate the access token included in the request (<request access
token>), and learn more information about the authorization granted by
this request access token. The resource server does so by performing an
HTTP POST on /v2/oauth2/token/introspect, with parameters sent as
"application/x-www-form-urlencoded" data as defined in
[https://www.google.com/url?q=http://www.w3.org/TR/2014/REC-html5-20141028/&sa=D&ust=1459362629169000&usg=AFQjCNFhrPEvarVy18hPhYRTd_T1i2KxPA[W3C.REC-html5-20141028]].

Request parameters are:

[options="header"]
|===================
|Parameter | Description
|token | The request access token on which this request is performing introspection.
|include | Request optional fields be included in the response. Currently the only supported value is `identities_set`, which will include the list of all
identities ids (primary and linked) that are associated with this Globus Auth account.
|=================

This request's Authorization header must contain resource server's
client identifier (client_id) and client secret (client_secret) in a
base64-encoded "Basic Authorization" scheme.

The response to this POST is an
https://www.google.com/url?q=https://tools.ietf.org/html/rfc7662&sa=D&ust=1459362629171000&usg=AFQjCNHaeyBUgdetJ9zYyXb_T5AxWDOhpQ[RFC
7662] compliant JSON document with the following fields:

Resource type: token/introspect

[options="header"]
|===================
|Field | Type | Description
|active | Bool | False if the token has expired or been revoked, true otherwise.
|scope | Space-separated List of Strings | List of scopes to which this access token authorizes access.
|sub | UUID | An effective identity id belonging to the account associated with this access token. This effective identity is either the primary identity of
the account, or if the client requires an identity issued by a
particular identity provider, then it may be the appropriate linked
identity from the account.
|username | String | The identity username for the effective identity id provided by the sub field.
|name | String/null | The display name for the effective identity of this token, typically a
full name. May be null, if the user has restricted their identity
visibility.
|email* | String/null | The email address associated with the effective identity of this token.
May be null, if the user has restricted their identity visibility.
|client_id | UUID | The Globus Auth issued client id of the client to which this token was issued.
|aud | List of strings | Identifier of the audiences for whom this token is intended. This will include both the resource server DNS name
and the client_id of the client to which this token was issued. In order to avoid a 'confused deputy' attack, clients and resource servers SHOULD validate that they are among the intended
audience for a token.
|iss | String | String representing the issuer of this token, which will always be
`https://auth.globus.org`. Note: During the transition from Globus Nexus to Globus Auth, legacy
tokens will have iss set to `https://nexus.api.globusonline.org`.
|exp | Timestamp | Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating when this token will expire.
|iat |Timestamp | Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating when this token was originally issued.
|nbf | Timestamp |Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating when this token is not to be used before.
|identities_set* [OPTIONAL] | List of UUIDs | A list of all identities ids (primary and linked) that are associated
with this Globus Auth account, which are visible to this resource
server. For performance reasons, this field is only included when the client
requests it with the parameter include=identities_set in the POST body.
|=======================

WARNING: Some identity providers reuse identity usernames, so over time
an identity username may map to different identity ids. Clients must use
the identity id as the persistent identifier of an identity.

* = Not part of RFC7662, Globus Auth-specific extension fields.

If the <request access token> does not exist, or was issued by Globus
Auth for use with a different resource server, then the HTTP response
will be 401 Unauthorized.

Example request:

        POST /v2/oauth2/token/introspect HTTP/1.1

        Host: auth.globus.org

        Accept: application/json

Content-Type: application/x-www-form-urlencoded

        Authorization: Basic MmZkYTQxNDktODJmZi00OTM3LT

        token=A7oU1xJ8-ddvRiMf-ZFDvXb&include=identities_set

Example response:

    HTTP/1.1 200 OK

    Content-Type: application/json

    {
        "active": true,
        "scope": "urn:globus:auth:scope:service.example.com:all",
        "client_id": "d430e6c8-b06f-4446-a060-2b6b2bc3e54a",
        "sub": "2982f207-04c0-11e5-ac60-22000b92c6ec",
        "username": "user1@example.com",
        "aud": "server.example.com",
        "iss": "https://auth.globus.org/",
        "exp": 1419356238,
        "iat": 1419350238,
        "nbf": 1419350238,
        "identities_set": [
            "2982f207-04c0-11e5-ac60-22000b92c6ec",
            "3982f207-04c0-11e5-ac60-22000b92c6ed"
        ],
        "name": "Joe User",
        "email": "user1@example.dom"
    }

NOTE: Globus Auth uses POST rather than GET in accordance with
    RFC7662 because of security concerns with passing an access token as
    part of a URL. An access token is a bearer token, so great care must be
    taken to ensure its confidentiality. However, web servers, proxies, and
    clients routinely log URLs. If URLs contain access tokens, and the logs
    are not properly sanitized or kept sufficiently confidential, they
    become a potential target for an attacker. By using a POST with the
    <request access token> included in the request body, the access token is
    not included in the URL.

===== Dependent Token Grant (POST /v2/oauth2/token)

This can only be used by a resource server, authorized using that
resource server's client identifier and client secret.

When a resource server receives a request from a client, after
validating the access token included in the request (<request access
token>) via link:#h.wh7c5vauquo4[token introspection (POST
/v2/oauth2/token/introspect)], the resource server may need to retrieve
dependent access tokens that allow this resource server to act as a
client to other resource servers on behalf of the client. The resource
server does so by performing a Globus Auth "Dependent Token Grant",
which is an
https://www.google.com/url?q=https://tools.ietf.org/html/rfc6749%23section-4.5&sa=D&ust=1459362629207000&usg=AFQjCNHTauLReWKZtkzxV_PeVBmHsee8Pg[OAuth2
Extension
Gran]https://www.google.com/url?q=https://tools.ietf.org/html/rfc6749%23section-4.5&sa=D&ust=1459362629208000&usg=AFQjCNFJB2wM921oz2y52Ak0FSf0hi0q9Q[t].

In conformance with the OAuth2 standard, the resource server does so by
performing an HTTP POST on /v2/oauth2/token, with parameters sent as
"application/x-www-form-urlencoded" data as defined in
[https://www.google.com/url?q=http://www.w3.org/TR/2014/REC-html5-20141028/&sa=D&ust=1459362629209000&usg=AFQjCNGOpgK7QE_QmvSP_4cw07rvH_oa9A[W3C.REC-html5-20141028]].

Request parameters are:

options="header"]
|===================
|Parameter | Value | Description
|grant_type | `urn:globus:auth:grant_type:dependent_token` | Custom OAuth2 extension grant type
|token | <request access token> | The
|access_type | `online` or `offline` (default: `online`) |
If `offline`, include any refresh tokens to which the resource server is entitled.
Whether or not refresh tokens are included depends on whether the scope policies allow it.
|==================

This request's Authorization header must contain resource server's
client identifier (client_id) and client secret (client_secret) in a
base64-encoded "Basic Authorization" scheme.

Example request:

   POST /v2/oauth2/token HTTP/1.1
        Host: auth.globus.org
        Content-Type: application/x-www-form-urlencoded
        Authorization: Basic <Resource Server's Client Credentials>

   grant_type=urn:globus:auth:grant_type:dependent_token&token=A7oU1xJ8-ddvRiMf-ZFDvXb

The response will be a JSON document containing an array of OAuth2
standard
https://www.google.com/url?q=https://tools.ietf.org/html/rfc6749%23section-5.1&sa=D&ust=1459362629212000&usg=AFQjCNHRcoOSgfcymFXxnouwGm5G6KN_Kw[access_token
response documents]. The number of tokens returned and their scopes are
pre-determined by the scope dependencies registered with Globus Auth by
the resource server administrators. The resource server does not have
the ability to request particular scopes when using this grant type.

For example, if the above request was made by the
transfer.api.globus.org resource server upon receipt of a request to its
urn:globus:auth:scope:service.example.com:all scope, and that scope is
configured to require dependent scopes of
urn:globus:auth:scope:groups.api.globus.org:check_membership and
urn:globus:auth:scope:auth.globus.org:view_identities scopes, then an
example response would be:

    HTTP/1.1 200 OK

    Content-Type: application/json

    [
        {
            "access_token": "r5qwkEz0lWJdpdknlDBmndC2G7wpTSOk...",
            "resource_server": "auth.globus.org",
            "scope":
    "urn:globus:auth:scope:auth.globus.org:view_identities",
            "expires_in": 3600,
            "refresh_token": "kUKDtLe_xDA4Qxd-ZI-rcFqrBlJj7zXx",
            "token_type": "bearer"
        },
        {
            "access_token": "7ZdPhhvija1MUDw6koBYgAAGnbrU79qF...",
            "resource_server": "groups.api.globus.org",
            "scope":
    "urn:globus:auth:scope:groups.api.globus.org:check_membership",
            "expires_in": 3600,
            "refresh_token": "dPVJBKAUs0x8UW4zhgQWv6snDmo2X72E",
            "token_type": "bearer"
        }
    ]

5.6. Web Browser Resources
~~~~~~~~~~~~~~~~~~~~~~~~~~

Globus Auth provides the following resources intended to be used from
web browsers.

5.6.1. https://auth.globus.org/v2/web/logout
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

When  a web application that that uses Globus Auth via a Authorization
Code Grant, after doing whatever cleanup it needs to do (e.g., delete
access tokens), it should redirect the user's web browser to
https://www.google.com/url?q=https://auth.globus.org/v2/web/logout&sa=D&ust=1459362629216000&usg=AFQjCNGitbsuBdVTFWapFysXB03Sj7ykQA[https://auth.globus.org/v2/web/logout].
Globus Auth will delete any cookies it dropped in the browser, so that
subsequent Authorization Code Grants will require re-authentication with
an identity provider.

To control the behavior of the page, clients can pass the following
query parameters:

* client_id=<client-id>
* redirect_uri=<http-url>
* redirect_name=<link-text>

Passing client_id will make the logout page header "Logged out of
<client-display-name>". For example, if the client display name that was
registered with Globus Auth for the specified <client-id> is "Example
App", the logout page header will be "Logged out of Example App"

If redirect_uri and redirect_name parameters are provided, the bottom of
the logout page will display "Continue to <link-text>", which is linked
to <http-url>. ^link:#cmnt11[[k]]^

6. References
-------------

* [OIDC]  N. Sakimura, N., J. Bradley, J., M. Jones, M., B. de Medeiros,
B., C. Mortimore, C., "OpenID Connect Core 1.0", November 8, 2014,
<https://www.google.com/url?q=http://openid.net/specs/openid-connect-core-1_0.html&sa=D&ust=1459362629223000&usg=AFQjCNG5tNSAl-FNYdb6Ed1iFgRq0H0lUg[http://openid.net/specs/openid-connect-core-1_0.html]>.
* [REFEDS-RS]  "REFEDS Research and Scholarship Entity Category, Version
1.2", November 2014,
<https://www.google.com/url?q=https://refeds.org/category/research-and-scholarship/&sa=D&ust=1459362629224000&usg=AFQjCNE0amJhPemYWRTjMurZfeu0rCkq6g[https://refeds.org/category/research-and-scholarship/]>.
* [RFC6749]  Hardt, D., Ed., "The OAuth 2.0 Authorization Framework",
RFC 6749, DOI 10.17487/RFC6749, October 2012,
<https://www.google.com/url?q=http://www.rfc-editor.org/info/rfc6749&sa=D&ust=1459362629226000&usg=AFQjCNG-AA8XlkuwAbjcvWFnsakz6J8SOw[http://www.rfc-editor.org/info/rfc6749]>.
* [RFC7159]  Bray, T., Ed., "The JavaScript Object Notation (JSON) Data
Interchange Format", RFC 7159, DOI 10.17487/RFC7159, March 2014,
<https://www.google.com/url?q=http://www.rfc-editor.org/info/rfc7159&sa=D&ust=1459362629228000&usg=AFQjCNEHK_8xA2XyOP6I-x8V2QZhrHpcPg[http://www.rfc-editor.org/info/rfc7159]>.
* [RFC7231]  Fielding, R., Ed. and J. Reschke, Ed., "Hypertext Transfer
Protocol (HTTP/1.1): Semantics and Content", RFC 7231, DOI
10.17487/RFC7231, June 2014,
<https://www.google.com/url?q=http://www.rfc-editor.org/info/rfc7231&sa=D&ust=1459362629230000&usg=AFQjCNGCxi5gbKGD7OqteHSsuYgGIFXf5A[http://www.rfc-editor.org/info/rfc7231]>.
* [RFC7662]  Richer, J., Ed., "OAuth 2.0 Token Introspection", RFC 7662,
DOI 10.17487/RFC6749, October 2015,
<https://www.google.com/url?q=https://www.rfc-editor.org/info/rfc7662&sa=D&ust=1459362629231000&usg=AFQjCNGQd4Y3sjKMlwubnLiVBaO9HMxnIg[https://www.rfc-editor.org/info/rfc7662]>.
* [W3C.REC-html5-20141028]  Hickson, I., Berjon, R., Faulkner, S.,
Leithead, T., Navara, E., 0'Connor, E., and S. Pfeiffer, "HTML5", World
Wide Web Consortium Recommendation REC-html5-20141028, October 2014,
<https://www.google.com/url?q=http://www.w3.org/TR/2014/REC-html5-20141028&sa=D&ust=1459362629232000&usg=AFQjCNGfPwc9yrZvCJAjpXt--NOvkWsxTw[http://www.w3.org/TR/2014/REC-html5-20141028]>.