= EVENTS(1)

== NAME

events - View event log of a task

== SYNOPSIS

*events* ['OPTIONS'] 'TASKID'

== DESCRIPTION

*events* displays events for a task.  Events are sorted by time in ascending
order.

NOTE: Tasks older than one month may no longer have event log history.  An
error is returned if this data is no longer available.

== OUTPUT FIELDS

Not all fields are shown by default.  Use the *-f* option to select which
fields to display.

*bytes*::
Bytes transferred.  Valid for PROGRESS and SUCCEEDED events.

*code*::
The type of the event, in string format.

*description*::
A human readable description of the event code

*details*::
Additional information about the event

*mbps*::
Megabits per second.  Valid for PROGRESS and SUCCEEDED events.

*parent_taskid*::
The parent's ID, or n/a if the task is a top-level task

*taskid*::
The unique ID of the task

*time*::
The time of the event


== OPTIONS

*-l* 'LIMIT'::

Limit the number of results to the most recent N.  The maximum limit is 1000
because of sorting efficiency.  Default: Unlimited

*--faults*::

Show only error events 

include::include/opt_output.adoc[]


== EXAMPLES

Show the most recent events for a task:

----
events -l 10 4bc8990e-b47c-11df-92d2-12313807462b
----

Show all fault events for a task:

----
events --faults 4bc8990e-b47c-11df-92d2-12313807462b
----
