= SCP(1)

== NAME

scp - Simple transfer command that has syntax similiar to SCP

== SYNOPSIS

*scp* ['OPTIONS'] 'source:source_file' 'dest:dest_path'

*scp* ['OPTIONS'] *-r* 'source:source_dir' 'dest:dest_dir'

== DESCRIPTION

Globus Online's *scp* command provides a simple way to copy a file or
directory between servers.  'source' and 'dest' must be logical endpoint
names.

*scp* can activate endpoints using gsi-ssh or automatically use the endpoints'
default myproxy configuration.  Use the *endpoint-activate* command for manual
endpoint activation.

By default, *scp* creates a transfer task and waits for the task to complete.
Type <CTRL-C> to cancel the task.  

Use the *-D* option or type "bg<ENTER>" to create a detached task that runs in
the background.  You may use other Globus Online commands, like *status* and
*wait*, to check the status of the task at any time.   

NOTE: If the task is not backgrounded and the SSH connection is broken, the
*scp* task will be automatically canceled.

User relative paths may be specified as "`~/path`" or "`path`".  Absolute
paths are specified as "`/path`".

SCP's directory semantics are different than the *transfer* command: the
*transfer* command will always place files in a pre-determined directory; the
*scp* command (like UNIX cp and scp) will check whether the target is an
existing directory or not.  

== OPTIONS

=== Standard SCP Options

*-r*::

Transfer directory recursively.  The source path must be a directory.  The
destination path must either not yet exist or be a directory.  The destination
directory will be created if it does not exist.

*-v*::
Enable verbose output.  Show endpoint and credential details.

=== Globus Online Extensions

*-g*::
Use your gsi-ssh proxy credential to activate the source and destination
endpoints.  You must be using gsi-ssh, not regular ssh.

// include::include/opt_deadline.adoc[]

// include::include/opt_label.adoc[]

// include::include/opt_encrypt.adoc[]

// include::include/opt_preserve_mtime.adoc[]

// include::include/opt_verify_checksum.adoc[]


*--delete*::

Delete extraneous files (and directories) in the destination directory.  For
recursive directory transfers only.  For example, SCP of /some/source/dir to
/tmp will ensure /tmp/dir is a perfect clone of /some/source/dir.  All other
files in /tmp outside of /tmp/dir are left alone.

*-D*::
Create a detached (background) task and exit.

// include::include/opt_synclevel.adoc[]


== EXAMPLES

Transfer a directory using gsi-ssh for activation:

----
scp -g -r tiger:/projects/myproject-dir bear:/tmp
----

Transfer a file from a home directory:

----
scp my_endpoint_1:file1.txt my_endpoint_2:/tmp
----


== EXIT STATUS

If *-D* is used, scp returns 0 if the task was successfully created.  If *-D*
is not used, scp returns 0 if the task completes successfully or non zero if
the task has a fatal error, fails to complete by the deadline, or is canceled.
