---
menu_weight: 2
short_title: Globus Connect
---
:toc-placement: manual
:toc:
:toclevels: 1
:toc-title:

= FAQs: Globus Connect

toc::[]

== How does Globus Connect Personal work?
link:https://www.globus.org/globus-connect-personal[Globus Connect Personal] uses GSI SSH to maintain a control connection to Globus and await commands. Globus manages transfers to and from the Globus Connect Personal endpoint. Note that file data is still always transferred directly between Globus Connect Personal and a GridFTP server for maximum speed – it is not proxied through Globus.

== What is the difference between Globus Connect Personal and Globus Connect Server?
Use link:https://www.globus.org/globus-connect-personal[Globus Connect Personal] to enable file transfer to and from your personal machine (laptop or desktop.) A Globus Connect Personal endpoint is intended to be used only by a single user. link:https://www.globus.org/globus-connect-server[Globus Connect Server] enables system administrators to turn shared resources such as campus clusters and lab servers into a Globus endpoint. If it is made publicly visible, a Globus Connect Server endpoint can be used by multiple Globus users.

== Are transfers between Globus Connect Personal endpoints possible?
Yes. You must be a link:https://www.globus.org/researchers/plus-plans[Globus Plus] user to transfer files between two Globus Connect Personal endpoints. If the two endpoints are owned by different Globus users, both users must be Globus Plus users. You account may be upgraded to Globus Plus if your institution subscribes to a link:https://www.globus.org/provider-plans[Globus Provider plan].

NOTE: You do not need to be a Plus user to transfer files between a link:https://www.globus.org/globus-connect-personal[Globus Connect Personal] endpoint (e.g. on your laptop) and a link:https://www.globus.org/globus-connect-server[Globus Connect Server] endpoint (e.g. on your lab server or campus cluster). Globus Connect Personal can execute a transfer as long as either the source or destination endpoint has a routable IP address (which is the case for almost all Globus Connect Server endpoints).

== How do I specify paths on Globus Connect Personal running on Windows?
link:https://www.globus.org/globus-connect-personal[Globus Connect Personal] on Windows will translate a path beginning with /~/ into your home directory, e.g. [uservars]#C:\Users\Anatoly\#. To access paths and drives outside of your home directory, use the syntax +/drive_letter/path+, for example [uservars]#/C/xinfo# lists the C:\xinfo directory.

== 