---
menu_weight: 5
short_title: Subscriptions
---
:toc-placement: manual
:toc:
:toclevels: 1
:toc-title:

= FAQs: Subscriptions

toc::[]

== How much does Globus cost?
Globus is free for researchers at non-profit institutions to use for file transfer, thanks to the generous support of sponsors who fund our research.

As a non-profit institution, our goal from day one has been to make Globus a self-sustaining service, so that we can continue to serve the needs of academic and non-profit research organizations for many years to come. Most of our funding is intended for research and early software development, not to cover operation, support, and ongoing evolutionary improvement of the service. As usage grows, our costs have grown and we decided that charging a usage-based subscription fee for additional features that go beyond file transfer is the best way to ensure that we can continue to provide a high-quality research data management service.

To this end, certain Globus features are available only by subscribing to a link:http://www.globus.org/providers/provider-plans[Globus Provider plan]. Such features include the ability to share files directly from existing storage, access to data publication functionality, and performing various administrative tasks for Globus endpoints at your institution. Globus Provider plans also offer higher levels of support from the Globus team, with priority response times.

If you are a commercial user, you may use Globus by signing up for a link:https://www.globus.org/providers/provider-plans#commercial-pricing[commercial Provider plan]. We are unable to offer the service free of charge to commercial users, but believe that you will find Globus provides valuable capabilities at a reasonable price. Thanks!

== How do I add a managed endpoint to my Provider subscription?
NOTE: The commands below must be run on the Globus command line interface (CLI). Please read link:../../cli/using-the-cli/[this page] to configure your account to access the Globus CLI.

You can add a managed endpoint via the link:../../cli/using-the-cli/[Globus command line interface] by running the following command:

----terminal
$ endpoint-add <username>#<endpoint-name> --managed-endpoint
----terminal

For example, if user [uservars]#demodoc# wishes to add a managed endpoint called [uservars]#onecluster# then the user must run:

----terminal
$ endpoint-add demodoc#onecluster --managed-endpoint
----terminal

Please ensure that [uservars]#<username># has subscription management rights, otherwise the command will fail. Note that a subscription manager can only create endpoints under their own account.

You must have a current link:https://www.globus.org/providers/provider-plans[Globus Provider plan] to be granted subscription management rights. If your Globus account does not have subscription management rights, please contact support@globus.org so that we may enable your account. If you do not have a Globus Provider plan please link:https://www.globus.org/providers/signup[contact us to sign up].

== How do I convert an existing endpoint into a managed endpoint?
NOTE: The commands below must be run on the Globus command line interface (CLI). Please read this article to configure your account to access the Globus CLI.

You can convert an existing endpoint into a managed endpoint via the Globus command line interface by running the following command:

----terminal
$ endpoint-modify --managed-endpoint <username>#<endpoint-name>
----terminal

For example, if user [uservars]#demodoc# wishes to flag the endpoint [uservars]#zerocluster# as a managed endpoint then the user must run:

----terminal
$ endpoint-modify --managed-endpoint demodoc#zerocluster
----terminal

Please ensure that [uservars]#<username># has subscription management rights, otherwise the command will fail. Note that a subscription manager can only create endpoints under their own account.

You must have a current link:https://www.globus.org/providers/provider-plans[Globus Provider plan] to be granted subscription management rights. If your Globus account does not have subscription management rights, please contact support@globus.org so that we may enable your account. If you do not have a Globus Provider plan please link:https://www.globus.org/providers/signup[contact us to sign up].