= Globus Resource Provider Guide
:revnumber: 0.0.2c
:toc:
:toc-placement: manual
:toclevels: 3
:numbered:

// Define some attributes to reuse in-line
:website: http://www.globus.org/
:gridftp: http://toolkit.globus.org/toolkit/docs/latest-stable/gridftp/
:researchers: http://www.globus.org/researchers/
:providers: http://www.globus.org/providers/
:provider_plans: http://www.globus.org/providers/provider-plans/
:sign_up: http://www.globus.org/signup/
:support: http://support.globus.org/anonymous_requests/new/
:transfer: http://www.globus.org/xfer/StartTransfer#/

// Other sites
:myproxy: http://grid.ncsa.illinois.edu/myproxy/

[doc-info]*Last Updated: {docdate}*

toc::[]

== Introduction

Globus allows you, as a resource provider, to easily offer reliable, secure,
high-performance research data management capabilities to your users
and their collaborators, directly from your own storage.
Globus is software as a service (SaaS), enabled by the cloud and
designed to let users manage their research files,
regardless of number and size,
as effortlessly as they manage their photos with popular cloud-based services.
Globus lets you provide authorized users web, command line, and REST interfaces
for listing, transferring, replicating, and sharing
directories and files on your Globus-connected storage resources.
If you are new to Globus, you can learn more about Globus
capabilities and benefits from the
{researchers}[researcher]
and
{providers}[resource provider] overview pages.

This guide is written primarily for system administrators of multi-user Linux
systems who want to optimize the connection of their resources
to the Globus ecosystem and take full advantage of the resource data
management capabilities Globus offers.
Administrators who are new to Globus, as well as those with
considerable experience, should all find helpful information in this
document.

Starting with the basics, this guide covers the initial
installation of
_Globus Connect Server_ and the creation of a Globus _endpoint_ that
lets authorized users transfer files between your storage and other
Globus endpoints.
The Globus Connect Server installation
downloads
(1) Globus versions of 'GridFTP', 'MyProxy', and 'OAuth for MyProxy';
(2) scripts for set up/configuration and integration into the Globus
ecosystem; and
(3) other Globus-maintained dependency packages needed to make the
preceding function.
The initial installation, also referred to as the default installation,
authorizes endpoint users via password-based authentication that
uses MyProxy and relies on the PAM modules configured in
+/etc/pam.d/login+--the same ones used by the +login+ command.

Progressing from the initial foundation,
additional configuration options and
advanced deployment scenarios
for your Globus endpoint
are described,
covering a range of authentication, optimization, and premium
features.
Later sections discuss
endpoint maintenance,
tools for monitoring your Globus deployment,
creating an endpoint on Amazon S3,
enabling Globus Plus for your users,
and various avenues for getting help.
Appendices contain comprehensive reference materials
and technical descriptions that go beyond the installation and
configuration instructions found in the main sections of the guide.

.[go-icon-pp]#Provider Plan Features#
[NOTE]
====
Globus can be used for file transfer by
non-profit research and educational institutions free-of-charge.
Usage-based {provider_plans}[Provider Plan subscriptions] are available for
commercial users and for non-profit institutions who want to
use premium features.
The Provider Plan subscriptions help ensure that Globus can
continue to serve the research data management needs of
non-profit users for many years to come.

Some premium Globus features described in this guide are only available to
Provider Plan subscribers.
====

== Globus Connect Server Prerequisites

Before you install Globus Connect Server on your system you should
confirm that the prerequisites listed in this section are met.
If they are not, the installation will not be successful.
Please {support}[submit a support ticket] if you have problems understanding
or satisfying the prerequisites.

=== Supported Linux distributions
Globus Connect Server is currently supported on the following Linux
distributions:

- CentOS 5, 6, and 7
- Debian 6 and 7
- Fedora 19 and 20
- Red Hat Enterprise Linux 5, 6, and 7
- Scientific Linux 5, 6, and 7
- SuSE Linux Enterprise Server 11sp3
- Ubuntu 10.04 LTS, 12.04 LTS, 14.04 LTS and 14.10

=== Administrator privileges
You must have administrator (root) privileges on your system
to install Globus Connect Server;
`sudo` can be used to perform the installation.

=== System time synchronization
Ensure that `ntpd`, or another daemon for synchronizing
with standard time servers, is running on your system.

=== Internet-accessible system
Your system must be accessible from the Internet.
More specifically, your organization's public Domain Name Service
(DNS) must have a record pointing to a public IP address
that is assigned or forwarded to the system where you will be installing
Globus Connect Server.

To check accessibility, first execute this command
on the system where
you plan to install Globus Connect Server:
----terminal
$ hostname -f
----terminal
Confirm that a fully qualified domain name (FQDN) of the form
+'xxx.yyy.zzz'+
(with 2 dots) or
+'www.xxx.yyy.zzz'+ (with 3 dots) is returned.

Next, use a public DNS server operated by a different organization to
verify that the returned FQDN is publicly resolvable.
More concretely, run this command,
where 'xxx.yyy.zzz' is
the output of your earlier +hostname -f+ command and +'8.8.4.4'+
specifies one of Google's public DNS servers:
----terminal
$ nslookup 'xxx.yyy.zzz' 8.8.4.4
----terminal
Verify that you [underline]#do not# get
a message of the form: +`** server can't find xxx.yyy.zzz: NXDOMAIN'+.

Some sites use network address translation (NAT) with a private
internal IP, private internal DNS, and a public DNS tied to a public
IP that gets forwarded to the private IP by the firewall/router.
Globus can be successfully installed at these sites, but requires
additional configuration beyond what is covered in the default
Globus Connect Server installation.
Please see
[yellow-background]#add pointer to later text in guide or direct them to
email support#
if your site uses NAT.

=== Open TCP ports
If your system is behind a firewall, some TCP ports must be open for
Globus to work.
The default Globus Connect Server installation requires these TCP
ports be open:

- Port 2811 inbound from 184.73.189.163 and 174.129.226.69
- Port 7512 inbound from 174.129.226.69
- Port 2223 outbound to 184.73.255.160
- Ports 50000--51000 inbound and outbound to/from Any

Non-default installations have slightly different requirements and
advanced configuration options also allow other port settings.
Please refer to Appendix
[yellow-background]#?the one on firewalls and maybe also on
MyProxy/OAuth authentication ?#
for further information.

=== Globus account for your organization
You will need a master Globus account for your organization that is
distinct from your personal Globus account.
The Globus username associated with the master account should be
something your users will recognize so they can easily
find endpoint(s) administered by your organization.
For example, the University of Chicago Research Computing Center has
`ucrcc' as their master Globus username.

If your organization doesn't already have a master Globus account,
create one using the form at
{sign_up}[globus.org/signup].
If the link takes you to your personal Globus dashboard rather than to
the blank sign up form,
you can access the form by
selecting +Log Out+ from the pull-down menu attached to your
personal username in the upper right corner of the dashboard window,
and then selecting +Sign Up+ from the top menu bar of the Sign In page.

=== No previously installed Globus components
Globus components previously installed on your system must be
removed before a new Globus Connect Server installation is
started.

If the directory +/etc/gridftp.d+ exists on your system,
please refer to the section
[yellow-background]#fix link to "Removing previously installed Globus
components"#.

== Globus Connect Server Installation and Endpoint Creation
Globus Connect Server lets you quickly and easily set up a
Globus endpoint on your system,
enabling authorized users to transfer files between your storage and other
Globus endpoints.
This section covers the installation of Globus Connect Server and
the set up of a Globus endpoint with the default configuration--the
recommended starting point for new resource providers.
You will be able to fine-tune this configuration later without doing a
reinstall.

Before continuing, it is important to confirm that the prerequisites
detailed in the previous section [yellow-background]#add link#
have been met.

=== Install Globus Connect Server
Skip to the appropriate section for your Linux distribution and
follow the instructions to install Globus Connect Server
on your system.

==== CentOS, Fedora, Red Hat Enterprise Linux, Scientific Linux
First, add the Globus Connect Server repository to your package management
system:
----terminal
$ sudo curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
$ sudo rpm --import http://www.globus.org/ftppub/globus-connect-server/RPM-GPG-KEY-Globus
$ sudo yum install globus-connect-server-repo-latest.noarch.rpm
----terminal

Next, if you are running
CentOS 5, Red Hat Enterprise Linux 5, or Scientific Linux 5,
add the additional required repository:
----terminal
$ sudo curl -LOs http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm
$ sudo yum install epel-release-5-4.noarch.rpm
----terminal

Finally, install Globus Connect Server:
----terminal
$ sudo yum install globus-connect-server
----terminal

==== SuSE Linux Enterprise Server
First, add the Globus Connect Server repository to your package management
system:
----terminal
$ sudo curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
$ sudo rpm --import http://www.globus.org/ftppub/globus-connect-server/RPM-GPG-KEY-Globus
$ sudo zypper install globus-connect-server-repo-latest.noarch.rpm
----terminal

Next, retrieve and install the additional required repositories:
----terminal
$ sudo zypper ar http://download.opensuse.org/repositories/Apache/SLE_11_SP3/Apache.repo
$ sudo zypper ar http://download.opensuse.org/repositories/Apache:/Modules/Apache_SLE_11_SP3/Apache:Modules.repo
$ sudo rpm --import http://download.opensuse.org/repositories/Apache/SLE_11_SP3/repodata/repomd.xml.key
$ sudo rpm --import http://download.opensuse.org/repositories/Apache:/Modules/Apache_SLE_11_SP3/repodata/repomd.xml.key
$ sudo zypper remove libapr1
----terminal

Finally, install Globus Connect Server:
----terminal
$ sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-Globus
$ sudo zypper install globus-connect-server
----terminal

==== Debian, Ubuntu
First, add the Globus Connect Server repository to your package management
system:
----terminal
$ sudo curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo_latest_all.deb
$ sudo dpkg -i globus-connect-server-repo_latest_all.deb
$ sudo apt-get update
----terminal

Then, install Globus Connect Server:
----terminal
$ sudo apt-get install globus-connect-server
----terminal

=== Create Globus Endpoint
Before creating your Globus endpoint,
edit the Globus Connect Server configuration file, installed at
+/etc/globus-connect-server.conf+,
and make two changes so that authorized users can find and access your endpoint.
Specifically, in the +[Endpoint]+ section of the file,
(1) set +Name+ to something that identifies your resource,
such as the system hostname or a descriptive term that is well-known within
your organization, and
(2) set +Public+ to +'True'+.
For example:
----
[Endpoint]
Name = hpc-15
Public = True
----

After editing the configuration file, run:
----terminal
$ sudo globus-connect-server-setup
----terminal

When prompted, enter the Globus username and password for your
organization's master Globus account.
When the +globus-connect-server-setup+ command completes, your Globus
endpoint is ready to be accessed by users with logins on your system.

=== Access Globus Endpoint

You (or any user on your system who has signed up for a Globus account)
can access the Globus endpoint
you just created by navigating to the Globus {transfer}[Transfer Files]
page and using the Globus pattern-match capabilities to find your
endpoint.
Enter either your organization's Globus username or the resource name
you chose in the configuration file ('hpc-15' in the example above)
in the 'Endpoint' box, then select the full endpoint name from the
list of matches.
You will be asked to authenticate to access the endpoint; enter the
username and password you use to log in to your system to complete the
authentication.

== Globus Connect Server Configuration

<Tell them then can change config & rerun command to
change config after initial install>

In the initial (default) installation of Globus Connect Server,
you edited two configuration options in the
+/etc/globus-connect-server.conf+ file,
the +Name+ and +Public+ options in the +[Endpoint]+ section.
You probably noticed that there are many, many other options
that can be configured.
This section of the guide covers some of the most common configuration
options; see the full reference for the Globus Connect Server
Configuration file in Appendix [yellow-background]#add link#.

<note, probably want to use words, not names of options, as section
headings>

<note, originally had advanced config options here too... maybe need
it back if some topics from deployment get migrated back here>

=== Name
x

=== Public
x

=== Authentication
(might move this into previous section)
<Add reference to how-things-work appendix, and there include or point
back to the diagrams that show the different routes used w/ various
authentication schemes.>

<Note that default was MyProxy & PAM.  Maybe section for it in case
they change then want to go back.>

==== Using MyProxy and OAuth
x

==== Single Sign-On with InCommon/CILogon
x

==== Using an Existing MyProxy Server
x

=== RestrictedPaths
x

=== [go-icon-pp]#Sharing#
also Sharing restricted paths, SharingStateDir, etc.

== Advanced Deployment Scenarios
This section covers some of the more advanced deployment scenarios.

<Ruth: still need to sort out what will go here & what may go in
previous section>

=== Performance Optimizations
x

==== Configuring multiple IO servers
x

=== Miscellaneous
<what belongs here & what moves back to config section?>


==== Customizing Filesystem Access
x

==== [go-icon-pp]#Enabling Sharing on GridFTP Servers#
(do we want this? - how is it different than enabling sharing)

==== Setting up an anonymous endpoint
x

==== Using a host certificate for GridFTP


== Maintaining Endpoint(s)

=== Creating a managed endpoint
<what do they need to do after getting a PP?>

=== Finding out about new releases
<subscribe to email, support twitter feed, ...>
< and what to do if they have questions>

=== Continuity of service when new release installed
<what do they need to tell their users, if anything.  when will
in-progress transfers be interrupted (never?).  Help them understand &
plan>

=== How to install software updates to your endpoint
The Globus team is improving the Globus Connect Server software all
the time, occasionally, you should update your software to get all the
latest bug fixes and improvements.  <Edit these for reality>
% apt-get update globus-connect-server
% yum update globus-connect-server
% rpm --update globus-connect-server

=== Removing previously installed Globus components

Issue the commands shown below for your Linux distribution
to remove previously installed Globus components:

////
Internal note:
Because terminal blocks allow formatting within them, you have to 
be careful to escape characters correctly or the rendered text will
be incorrect. The commands should be:
$ sudo yum remove \*globus\*
$ sudo yum remove \*myproxy\*
$ sudo zypper remove \*globus\*
$ sudo zypper remove \*myproxy\*
$ sudo apt-get purge ".*globus.*"
$ sudo apt-get purge ".*myproxy.*"
////

.Red Hat Enterprise Linux, CentOS, Scientific Linux, Fedora
----terminal
$ sudo yum remove \\*globus\*
$ sudo yum remove \\*myproxy\*
----terminal

.SuSE Linux Enterprise Server
----terminal
$ sudo zypper remove \\*globus\*
$ sudo zypper remove \\*myproxy\*
----terminal

.Debian, Ubuntu
----terminal
$ sudo apt-get purge ".\*globus.\*"
$ sudo apt-get purge ".\*myproxy.*"
----terminal

== [go-icon-pp]#Management Console#

== [go-icon-pp]#Usage Reporting#

== [go-icon-pp]#Installing an S3 endpoint#
https://www.globus.org/amazon-web-services/s3-endpoint-configuration

== [go-icon-pp]#Enabling Globus Plus for Users#

== Generating and Monitoring Log Files

== Getting Help

=== Troubleshooting Common Problems
where to find most relevant log files, other things that will help you
use these venues more effectively..

=== Other Resources

==== FAQs
x

==== Documentation
x

==== Community Forums
x

==== Support Tickets
x

== Additional Capabilities

See us about skinned sites, mass storage, ...


:numbered!:

[appendix]
== Firewalls

Add information about what ports are open and why.
Also, note the configuration options that can be used to change the defaults.
And, for the one that only needs to be open during install (and
debugging, tell them they can close it, but may need to be opened
later).
And, maybe some troubleshooting of issues that arise if the ports
aren't open (or put that in separate section of Troubleshooting part).

<cut/paste to sort out later>
This content should be about the how to, maybe with a little why.
Most of the why would be in main body of guide.  Will need to tease
out content in these posts & decide now to place it in the outline (or
modify outline).

https://support.globus.org/entries/23861366-Using-Globus-Connect-Server-with-Firewalls
https://support.globus.org/entries/20999723-What-ports-does-Globus-Connect-Server-need-open-

note that next one is about GCP but included as admins may have to
help their users.

https://support.globus.org/entries/20999718-What-ports-does-Globus-Connect-Personal-need-open-

[appendix]
== Globus Connect Server I/O Nodes

More detailed description of software that is included in the I/O node
package.
Any other useful information for configuring distinct I/O nodes, e.g.
shared file system configuration.
Reference for configuring using the command line tools:
https://support.globus.org/entries/24028833-Command-Line-Tools-for-Configuring-Globus-Connect-Server-I-O-Nodes

[appendix]
== Globus Connect Server ID Nodes

More detailed description of software that is included in the ID node
package.
Any other useful information for configuring an node, e.g. pointers to
MyProxy reference documentation.
Reference for configuring using the command line tools:
https://support.globus.org/entries/24030266-Command-Line-Tools-for-Configuring-a-Globus-Connect-Server-ID-Node

[appendix]
== Globus Connect Server Web Nodes

More detailed description of software that is included in the Web node
package.
Any other useful information for configuring a Web node, e.g. optimal
Apache config options.
Reference for configuring using the command line tools:
https://support.globus.org/entries/24032757-Command-Line-Tools-for-Configuring-a-Globus-Connect-Server-Web-Node

[appendix]
== Globus Connect Server Configuration Reference

https://support.globus.org/entries/24005071-Globus-Connect-Server-Configuration-File-Reference


[appendix]
== Globus Connect Server Man Page
<include>

[appendix]
== Overview of Globus Operations
Brief description of how the SaaS operates, including:
How we ensure reliability (retries, timeouts, etc.)
What information we store, and for how long
  The objective here is to assuage user privacy concerns
Our policy and process for identifying/mitigating threats
...



[appendix]
== Globus Research Data Management Workflows

Detailed description an end-to-end file transfer session using globus,
including the endpoint authentication workflows (using MyProxy and
OAuth).
https://support.globus.org/entries/27825216-Globus-Connect-Server-Authentication-Authorization-Flows
Detailed description of how sharing works



[glossary]
== List of Terms
endpoint::
  add definition here
Globus Connect Server::
  add definition
GridFTP::
  GridFTP is an extension of the standard File Transfer Protocol (FTP)
  for high-speed, reliable, and secure data transfer.
  See the {gridftp}[GridFTP documents] for more information.
MyProxy::
  MyProxy is open source software for managing X.509 Public Key
  Infrastructure (PKI) security credentials (certificates and private
  keys).
  See the {myproxy}[MyProxy website] for more information.
OAuth for MyProxy::
  OAuth for MyProxy provides an OAuth-compliant REST web interface to
  the MyProxy service for providing user certificates to Globus.
  See the 'OAuth' section of the {myproxy}[MyProxy webpage] for more
  information.

