= Globus Resource Provider Guide
:revdate: May 12, 2016
:toc:
:toc-placement: manual
:toclevels: 3
:numbered:

// Define some attributes to reuse in-line
:website_url: http://www.globus.org/
:gridftp_url: http://toolkit.globus.org/toolkit/docs/latest-stable/gridftp/
:researchers_url: http://www.globus.org/researchers/
:providers_url: http://www.globus.org/providers/
:provider-plans_url: http://www.globus.org/providers/provider-plans/
:signup_url: http://www.globus.org/app/SignUp/
:transfer_url: http://www.globus.org/app/transfer/
:contact-us_url: http://www.globus.org/contact-us/

// Other sites
:myproxy_url: http://grid.ncsa.illinois.edu/myproxy/
:ec2_url: http://aws.amazon.com/ec2/
:s3_url: http://aws.amazon.com/s3/

[doc-info]*Last Updated: {revdate}*

toc::[]

== Introduction

Globus allows you, as a resource provider, to easily offer reliable, secure,
high-performance research data management capabilities to your users
and their collaborators, directly from your own storage.
Globus is software-as-a-service (SaaS), enabled by the cloud and
designed to let users manage their research files,
regardless of number and size,
as effortlessly as they manage their photos with popular cloud-based services.
Globus lets you provide authorized users with web, command line, and REST interfaces
for listing, transferring, replicating, and sharing
directories and files on your Globus-connected storage resources.
You can learn more about Globus capabilities and benefits from the
link:{researchers_url}[researcher]
and
link:{providers_url}[resource provider] overview pages.

This guide is written primarily for system administrators of multi-user Linux
systems who want to take full advantage of Globus capabilities and optimize 
the connection of their resources to the Globus service.
Administrators who are installing Globus for the first time, as well as those with
considerable experience, should all find helpful information in this
document.

Starting with the basics, this guide covers the initial
installation of
_Globus Connect Server_ and the creation of a Globus server
xref:endpoint-anchor[endpoint] that
lets authorized users transfer files between your storage and other
Globus endpoints.
The Globus Connect Server installation downloads
(1) Globus versions of 
xref:gridftp-anchor[GridFTP], 
xref:myproxy-anchor[MyProxy], and 
xref:oauth-for-myproxy-anchor[OAuth for MyProxy];
(2) scripts for set up/configuration and integration into the Globus service; 
and (3) Globus-maintained dependency packages needed by the other components.

.[go-icon-pp]#Provider Plan Features#
[NOTE]
====
Globus file transfer is free-of-charge for non-profit research and educational use.
Some premium Globus features described in this guide are only available to
link:{provider-plans_url}[Provider Plan] subscribers.

Subscriptions help ensure that Globus can
continue to serve the research data management needs of
non-profit users for many years to come.
====

== Globus Connect Server Prerequisites

[IMPORTANT]
The prerequisites listed in this section must be met before you 
begin to install Globus Connect Server on your system.
link:{contact-us_url}[Contact us] if you have problems understanding
or satisfying the prerequisites.

=== Supported Linux distributions
Globus Connect Server is currently supported on the following Linux
distributions:

- CentOS 5, 6, and 7
- Debian 7 and 8
- Fedora 22 and 23
- Red Hat Enterprise Linux 5, 6, and 7
- Scientific Linux 5, 6, and 7
- SuSE Linux Enterprise Server 11sp3
- Ubuntu 12.04 LTS, 14.04 LTS, 15.10, and 16.04 LTS

=== Administrator privileges
You must have administrator (root) privileges on your system
to install Globus Connect Server;
`sudo` can be used to perform the installation.

=== System time synchronization
Your system must be running `ntpd` or another daemon for synchronizing with standard time servers.

=== Globus account for your organization
You must have a Globus xref:organization-account-anchor[organization account] 
that is distinct from your personal Globus account.

=== Internet-accessible system
Other hosts on the Internet must be able to initiate connections to the system where you will be installing Globus Connect Server.
If your system is behind a network address translation (NAT) firewall/router, you cannot use the 
default configuration to install Globus--please see the configuration instructions in 
the xref:nat_section[NAT/firewall] section.
Otherwise, perform the checks shown below to confirm that your system meets the default accessibility requirements.
If you are installing on an link:{ec2_url}[Amazon EC2] instance, 
you can skip ahead to the xref:open-tcp-ports_section[Open TCP ports] section.

Your network administrator may be able to offer assistance if you run into problems, or 
link:{contact-us_url}[contact us].

==== Check hostname local DNS resolution
Execute this command
on the system where you plan to install Globus Connect Server:
----terminal
$ hostname -f
----terminal
Confirm that a fully qualified domain name (FQDN) is returned (e.g., 'ep1.transfer.globus.org' ).

==== Check hostname external DNS resolution
Use a public DNS server operated by a different organization to
verify that the returned FQDN is publicly resolvable.
More concretely, you can use `nslookup` to check that your server's 
FQDN resolves against one of Google's public DNS servers:
----terminal
$ nslookup [input]#'ep1.transfer.globus.org'# 8.8.4.4
----terminal
If you get a message of the form '"** server can't find ep1.transfer.globus.org: NXDOMAIN"',
your system's hostname is not resolvable via public DNS and you need to 
address the issue before continuing with the installation. 


[[open-tcp-ports_section]]
=== Open TCP ports
If your system is behind a firewall, select TCP ports must be open for Globus to work.
You may need to coordinate with your network or security administrator to open the ports.

The TCP ports that must be open for the default Globus Connect Server installation, 
together with brief descriptions of each, are listed here:

- Port 2811 inbound from 184.73.189.163 and 174.129.226.69
* Used for GridFTP control channel traffic. 
- Ports 50000--51000 inbound and outbound to/from Any
* Used for GridFTP data channel traffic. 
* The use of the default port range is strongly recommended (you can read why xref:data_channel_traffic[here]).
* Data channel traffic is sent directly between endpoints--it is not relayed by the Globus service.
- Port 2223 outbound to 184.73.255.160
* Used to pull certificate information from the Globus service.
- Port 443 outbound to 174.129.226.69 and nexus.api.globusonline.org
* Used to communicate with the Globus service via its REST API.
* nexus.api.globusonline.org is a CNAME for an Amazon 
link:http://aws.amazon.com/elasticloadbalancing/[ELB]; IP addresses 
in the ELB are subject to change.
- Port 80 outbound to 192.5.186.47
* Used to pull Globus Connect Server install packages from the Globus repository.
- Port 7512 inbound from 174.129.226.69
* Used for MyProxy traffic.
* Needed if your server will run MyProxy service.
- Port 443 inbound from Any
* Used for OAuth traffic.
* Needed if your server will run OAuth service.
* OAuth traffic comes directly from clients using your OAuth service--it is not relayed by the Globus service.


[[install_section]]
== Globus Connect Server Installation and Endpoint Creation
This section covers the installation of Globus Connect Server and
the set up of a Globus server endpoint with the default configuration--the
recommended starting point for new resource providers.
You will be able to fine-tune this configuration later without doing a
reinstall.

Before continuing, it is important to confirm that the prerequisites
detailed in the link:#globus_connect_server_prerequisites[previous section]
have been met.

=== Install Globus Connect Server
Skip to the appropriate section for your Linux distribution and
follow the instructions to install Globus Connect Server
on your system.

==== CentOS, Fedora, Red Hat Enterprise Linux, Scientific Linux
First, add the Globus Connect Server repository to your package management
system:

----terminal
$ sudo curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
$ sudo rpm --import http://toolkit.globus.org/ftppub/globus-connect-server/RPM-GPG-KEY-Globus
$ sudo yum install globus-connect-server-repo-latest.noarch.rpm
----terminal

Next, if you are running CentOS 5, Red Hat Enterprise Linux 5, or Scientific Linux 5, add the additional required repository and install yum-priorities:

----terminal
$ sudo curl -LOs http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm
$ sudo yum install epel-release-5-4.noarch.rpm
$ sudo yum install yum-priorities
----terminal

Now, if you are running CentOS 6+, Red Hat Enterprise Linux 6+, or Scientific Linux 6+, install yum-plugin-priorities:

----terminal
$ sudo yum install yum-plugin-priorities
----terminal

Finally, install Globus Connect Server:
----terminal
$ sudo yum install globus-connect-server
----terminal

==== SuSE Linux Enterprise Server
First, add the Globus Connect Server repository to your package management
system:
----terminal
$ sudo curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
$ sudo rpm --import http://toolkit.globus.org/ftppub/globus-connect-server/RPM-GPG-KEY-Globus
$ sudo zypper install globus-connect-server-repo-latest.noarch.rpm
----terminal

Next, retrieve and install the additional required repositories:
----terminal
$ sudo zypper ar http://download.opensuse.org/repositories/Apache/SLE_11_SP3/Apache.repo
$ sudo zypper ar http://download.opensuse.org/repositories/Apache:/Modules/Apache_SLE_11_SP3/Apache:Modules.repo
$ sudo rpm --import http://download.opensuse.org/repositories/Apache/SLE_11_SP3/repodata/repomd.xml.key
$ sudo rpm --import http://download.opensuse.org/repositories/Apache:/Modules/Apache_SLE_11_SP3/repodata/repomd.xml.key
$ sudo zypper remove libapr1
----terminal

Finally, install Globus Connect Server:
----terminal
$ sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-Globus
$ sudo zypper install globus-connect-server
----terminal

==== Debian, Ubuntu
First, add the Globus Connect Server repository to your package management
system:
----terminal
$ sudo curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo_latest_all.deb
$ sudo dpkg -i globus-connect-server-repo_latest_all.deb
$ sudo apt-get update
----terminal

Then, install Globus Connect Server:
----terminal
$ sudo apt-get install globus-connect-server
----terminal

=== Create Globus Endpoint
Before creating your Globus server endpoint,
choose a suitable second part for your xref:endpoint-name-anchor[endpoint name]. 
Then, edit the Globus Connect Server configuration file, +/etc/globus-connect-server.conf+,
and set +Name+ to your choice (_geosciences_ in the example shown), and +Public+ to _True_.
These two changes in the +[Endpoint]+ section of the file will allow authorized users to find and access your endpoint.
----
[Endpoint]
Name = geosciences
Public = True
----

After editing the configuration file, run:
----terminal
$ sudo globus-connect-server-setup
----terminal

When prompted, enter the Globus username and password for your
xref:organization-account-anchor[Globus organization account].
When the +globus-connect-server-setup+ command completes, your Globus
endpoint is ready to be accessed by users with logins on your system.

=== Access Globus Endpoint

You (or any user on your system who has signed up for a Globus account) should now be able to 
access the Globus endpoint you just created by navigating to the Globus 
link:{transfer_url}[Transfer Files] page. 
We recommend that you confirm your endpoint is functioning properly by performing some test transfers, as described 
xref:test_basic_endpoint_functionality[here].

=== Update Globus Endpoint

The set of software components that make up Globus Connect Server are improved and released on an ongoing basis. 
To take advantage of the lastest features we encourage you to update your local installation from the Globus repository regularly. 
The steps for doing an update are found xref:update_section[here].

== Globus Connect Server Configuration

During the initial (default) installation of Globus Connect Server,
you edited two configuration options in the
+/etc/globus-connect-server.conf+ file,
the +Name+ and +Public+ options in the +[Endpoint]+ section.
You probably noticed that there are many, many other options
that can be configured.
This section of the Globus Resource Provider Guide briefly covers a few of the most commonly changed
options in the +globus-connect-server.conf+ file. After updating settings in the 
+/etc/globus-connect-server.conf+ file you must run the 
`globus-connect-server-setup` command (as root) before the settings
will take effect on your endpoint.

[NOTE]
A detailed 
description of every option can be found in the 
link:https://github.com/globus/globus-connect-server/blob/master/source/globus-connect-server.conf[globus-connect-server.conf] source file on github.

=== [Globus] section

==== +User+ and +Password+ options
These options can be used to set the username and password
of the Globus user that will be used when creating or updating
the endpoint definition.

=== [Endpoint] section

==== +Name+ option
This sets the name of the endpoint.

==== +Public+ option
This determines if the endpoint is publicly visible to all Globus users.

==== +DefaultDirectory+ option
This sets the default directory that users will be sent to when
first accessing an endpoint.

=== [Security] section

==== +IdentityMethod+ option
This option has three legal values: MyProxy, OAuth, and CILogon. For a graphical overview of the authentication flows each of these methods use, see link:../authorization-authentication-guide/[here].
If you wish to use MyProxy as your endpoint's identity method, then
you need to be sure to specify the +Server+ option in the [MyProxy]
section. If you wish to use OAuth as your endpoint's identity method, 
then you need to be sure to specify the +Server+ option in the [OAuth]
section, and may also need to specify the +Server+ option in the [MyProxy]
section if you are using MyProxy on the server to provide authentication 
for the OAuth service. If you are using CILogon, then you will also need to
specify the +CILogonIdentityProvider+ option in the [Security] section.

==== +CILogonIdentityProvider+ option
This option specifies the identity provider to use with CILogon. 
See https://cilogon.org/ for a list of valid providers. Be sure to also set "IdentityMethod=CILogon" in the [Security] section of the config file if you intend to use CILogon for your endpoint.

=== [GridFTP] section

==== +Server+ option
This option specifies the hostname of the GridFTP server. This should
match the hostname of the server except, possibly, if NAT is being used. Can
be left blank if you don't want to configure a GridFTP server on this host. If a GridFTP service is to be run on this server, then the default value of "Server = %(HOSTNAME)s" is suitable to most cases, so long as the configured hostname on the server matches the public FQDN that is going to be used for the server.

==== +ServerBehindNAT+ option
This option specifies that the server is behind a NAT firewall/router. See the xref:nat_section[NAT] section 
for details.

==== +RestrictPaths+ option
This option is used to both enable and/or disable specified file paths for all Globus users that are authorized to use this endpoint. By default, all paths are enabled for access. 

==== [go-icon-pp]#+Sharing+ option#
This is a boolean value that determines if sharing is enabled on this particular endpoint. This option is only used on a xref:managed-endpoint-anchor[managed endpoint], and will be ignored otherwise. 

==== [go-icon-pp]#+SharingRestrictPaths+ option#
This option is used to both enable and/or disable specified file paths for all Globus users that are authorized to use this xref:shared-endpoint-anchor[shared endpoint]. By default, all paths are enabled for access. NOTE: When accessing a shared endpoint through Globus, the SharingRestrictPaths option can only set further access restrictions to the endpoint owner's local unix file system permissions. Globus does not and can not override the local unix file system permissions. This option is only used on a xref:managed-endpoint-anchor[managed endpoint], and will be ignored otherwise.

==== +RequireEncryption+ option
This boolean value determines if encryption will be forced for the GridFTP server being configured on this host. Please note that, if set to True, transfers will fail if they are attempted without encryption. 

=== [MyProxy] section

==== +Server+ option
This option specifies the hostname of the MyProxy server. If you are running
the MyProxy server on this host, then this should match the hostname of this server 
except, possibly, if NAT is being used. If you are using a MyProxy server on a 
different host, then use the hostname of that host. Can be left blank if you don't 
want to configure a MyProxy server at all. If the MyProxy service for the endpoint is to be run on this server, then the default value of "Server = %(HOSTNAME)s" is suitable to most cases, so long as the configured hostname on the server matches the public FQDN that is going to be used for the server. Be sure to also set "IdentityMethod=MyProxy" in the [Security] section of the config file if you intend to use MyProxy for your endpoint.

==== +ServerBehindNAT+ option
This option specifies that the server is NATed. See the xref:nat_section[NAT] section 
for details.

=== [OAuth] section

==== +Server+ option
This option specifies the hostname of the OAuth server. If you are running
the OAuth server on this host, then this should match the hostname of this server 
except, possibly, if NAT is being used. If you are using an OAuth server on a 
different host, then use the hostname of that host. Can be left blank if you don't 
want to configure an OAuth server at all. If the OAuth service for the endpoint is to be run on this server, then the default value of "Server = %(HOSTNAME)s" is suitable to most cases, so long as the configured hostname on the server matches the public FQDN that is going to be used for the server. Be sure to also set "IdentityMethod=OAuth" in the [Security] section of the config file if you intend to use OAuth for your endpoint.

==== +ServerBehindNAT+ option
This option specifies that the server is NATed. See the xref:nat_section[NAT] section 
for details.

[[nat_section]]
== NAT/Firewall support and configuration
The Globus Connect Server package provides configuration tools for several related services to enable administrators to easily configure a Globus endpoint. The globus-connect-server.conf file controls how the services used by Globus are configured, and includes configuration options to manage firewall-related configuration of services. Each service provided by the Globus Connect Server packages may be configured separately as described below.

Note that the descriptions below include examples of Globus Connect Server service configurations only. Configuring the firewalls themselves to allow the ports and host connections is not discussed. See the xref:open-tcp-ports_section[Open TCP ports] section for a discussions of 
the ports used by Globus Connect Server.

=== Configuring I/O Nodes
Globus Connect Server I/O nodes provide a GridFTP service to Globus. Options related to firewalls in the [GridFTP] section of the configuration file are: Server, ServerBehindNAT, IncomingPortRange, OutgoingPortRange, and DataInterface.

By default, Globus Connect Server configures the GridFTP server assuming that incoming TCP connections are allowed to port 2811, and the range 50000-51000 on the GridFTP server node.

==== Using GridFTP behind a NAT Firewall
To use a GridFTP behind a NAT firewall, set the Server option to the public name of the GridFTP server, and set the ServerBehindNAT option to True. This causes globus-connect-server-io-setup to generate GridFTP configuration for the node even if the Server name doesn't match the node's local hostname. This requires that the GridFTP server is visible from Globus at the address associated on the public internet with the name that is the Server value.

==== NAT Firewall Example
As an example, this configures the GridFTP server to run on the current host, using public-gridftp.example.org as its public name and listening on port 22811 instead of the default 2811. In order for this to work, the NAT firewall must allow connections to TCP port 22811 and the range 50000-51000 on the I/O node. By default, the Server name is used to construct the data interface name as well, but this behavior can be changed (see Using GridFTP with a Particular Data Interface).

----
[GridFTP]
Server = public-gridftp.example.org:22811
ServerBehindNAT = True
----

==== Using GridFTP with Firewall Port Restrictions
To use a GridFTP server with a firewall with incoming and/or outgoing port restrictions, use the IncomingPortRange and OutgoingPortRange configuration options. The former restricts the TCP port range that the GridFTP server listens on for ephemeral connections to a port range. The OutgoingPortRange restricts the TCP source port range that the GridFTP server uses when creating outgoing data connection sockets. For both of these items, the syntax of the port range is startport,endport (e.g., 50000,51000).

==== Port Restrictions Example
As an example, this configures the GridFTP server to listen for TCP connections on ports from 4000 to 5000 instead of the default 50000 to 51000. This will require configuration on the firewall to allow those ports to connect directly to the I/O node.

----
[GridFTP]
Server = public-gridftp.example.org:22811
IncomingPortRange = 4000,5000
----

==== Using GridFTP with a Particular Data Interface
The GridFTP server can also be configured to use a different IP address for its incoming data connections by setting the DataInterface option in the configuration file. By default, the GridFTP server will use the same IP address as that associated with the Server value. This can be altered, for example, to create a limited-use endpoint that uses a high-speed interconnect between I/O resources, but is not generally accessible from the internet.

==== Data Interface Example
As an example, this configures the GridFTP server to listen for TCP data connections on gig-e.example.org.

----
[GridFTP]
Server = public-gridftp.example.org:22811
DataInterface = gig-e.example.org
----

=== Configuring an ID Node
The Globus Connect Server ID node provides a MyProxy service. This service generates short-lived credentials which are used to authenticate with the GridFTP server. Globus may be configured to access this service directly, or access it via a web-based OAuth interface. This is chosen by the presence or absence of an [OAuth] section in the globus-connect-server.conf file.

By default, the MyProxy service listens on TCP port 7512. It makes no outgoing TCP connections. Like the GridFTP servers on the I/O nodes, the [MyProxy] section contains Server and ServerBehindNAT configuration options, which function like the ones in the GridFTP section.

If the MyProxy service is not being used directly by the Globus service (that is, if a OAuth server is being used), then the MyProxy service need only be reachable by the Web node and, during initial configuration, by the I/O nodes. No other nodes will require access the MyProxy service in normal operation.

==== Using MyProxy behind a NAT Firewall
To use a MyProxy server behind a NAT firewall, set the Server option to the public name of the MyProxy server, and set the ServerBehindNAT option to True. This causes globus-connect-server-id-setup to generate MyProxy configuration for the node even if the Server name doesn't match the node's local hostname. If you are configuring an OAuth server, the Server option must be accessible from the Web node and I/O nodes (during configuration); otherwise, it must be accessible from Globus.

==== NAT Firewall Example
As an example, this configures the MyProxy server to run on the current host, using public-myproxy.example.org as its public name and listening on port 17512 instead of the default 7512. In order for this to work, the NAT firewall must allow connections to the TCP port 17512 on the ID node.

----
[MyProxy]
Server = public-myproxy.example.org:17512
ServerBehindNAT = True
----

=== Configuring a Web Node
The Globus Connect Server Web node provides OAuth service to Globus. There are a few configuration options related to firewalls in the [OAuth] section of the configuration file. These are Server and ServerBehindNAT.

Unlike the other service nodes, the Web node is somewhat less configurable, as it relies on an external Apache server to accept TCP connections. Configuring the Apache server to listen on a different TCP port is out of scope of this note. The Server value may only contain a hostname, and the port 443 (https) is used. Globus does not support OAuth servers on alternate ports.

==== Using OAuth behind a NAT Firewall
To use an OAuth server behind a NAT firewall, set the Server option to the public name of the OAuth server, and set the ServerBehindNAT option to True. This causes globus-connect-server-web-setup to generate OAuth configuration for the node even if the Server name doesn't match the node's local hostname. This requires that the OAuth server is visible from Globus at the address associated on the public internet with the name that is the Server value.

==== NAT Firewall Example
As an example, this configures the OAuth server to run on the current host, using public-oauth.example.org as its public name. In order for this to work, the NAT firewall must allow connections to TCP port 433 on the web node.

----
[OAuth]
Server = public-oauth.example.org
ServerBehindNAT = True
----

== Generating and Monitoring Log Files

[[gridftp_server_log_files]]
=== GridFTP Server Log Files

On recent versions of Globus Connect Server, the GridFTP log is located at:

`/var/log/gridftp.log`

On recent versions of Globus Connect Server, the configuration settings 
for the GridFTP log file are found at:

`/etc/gridftp.d/globus-connect-server-gridftp-logging`

On older versions of Globus Connect Server, logging for the GridFTP service is
 not enabled by default. In order to enable logging, it is necessary to specify 
the appropriate options in the GridFTP configuration files. One way to do this 
would be to create a text file named:

`/etc/gridftp.d/globus-connect-server-gridftp-logging`

Next, place the following options into the file:

----
log_single /var/log/gridftp.log
log_level ERROR,WARN
----

After saving the file, restart the GridFTP server with this command:

----terminal
$ sudo service globus-gridftp-server restart
----terminal

At this point, the GridFTP server will log all ERROR and WARN events to the
 `/var/log/gridftp.log` file. Additional details concerning logging for the 
GridFTP server are available in the `globus-gridftp-server` man page link:man/globus-gridftp-server/[here].

[[myproxy_server_log_files]]
=== MyProxy Server Log Files

By default, the MyProxy server logs events to the LOG_DAEMON facility. This 
means that, by default, MyProxy events will be found in the following locations:

*CentOS, Fedora, Red Hat Enterprise Linux, Scientific Linux:*

`/var/log/messages`

*Debian/Ubuntu:*

`/var/log/syslog`

*SuSE Linux Enterprise Server:*

`/var/log/messages`

Please note that if the logging location for the LOG_DAEMON facility has been 
changed from the default in your syslogd config, then MyProxy events may be found 
in a different location. For further details concerning MyProxy please see the
 link:http://toolkit.globus.org/toolkit/docs/latest-stable/myproxy/[MyProxy Admin Guide].

=== MyProxy Delegation Service (myproxy­-oauth) Log Files

Events for myproxy­-oauth will be logged to the apache log file directory. By 
default, this will be found at the following locations:

*CentOS, Fedora, Red Hat Enterprise Linux, Scientific Linux:*

`/var/log/httpd/`

*Debian/Ubuntu:*

`/var/log/apache2/`

*SuSE Linux Enterprise Server:*

`/var/log/apache2/`

For further info on the MyProxy Delegation Service see the 
link:https://github.com/globus/globus-toolkit/blob/globus_6_branch/myproxy/oauth/source/README.md[README].

== Getting Help

=== Troubleshooting Common Problems
This section describes some basic tests you can run when you experience problems with a transfer or an endpoint.
These tests can help you narrow down the potential causes of the issue and simplify troubleshooting. 

[[test_basic_endpoint_functionality]]
==== Test Basic Endpoint Functionality
An important verification of endpoint health is to confirm that the endpoint is able to successfully participate in transfers from and to other endpoints.
Globus maintains two test endpoints, go#ep1 and go#ep2, that are always available for users to access when checking the functionality of their own endpoints.
First, attempt to transfer the contents of the `/share/godata/` directory on the go#ep1 endpoint to your own endpoint. 
After that, attempt to transfer those same files to the `/~/` directory on the go#ep2 endpoint. 
If these tests both succeed, then your endpoint is functional and able to serve as the destination and the source of transfers. 
For more detailed instructions on how to use the Globus service to transfer files, see link:https://www.globus.org/researchers/getting-started[here].

==== Verify globus-gridftp-server Service 
Another important check on servers hosting a Globus endpoint is to verify that the 
globus-gridftp-server service has properly started and is running. 
To do this, first use the `ps` command to see if there is an instance of globus-gridftp-server running:

----terminal
# ps aux | grep globus-gridftp-server
root       604  0.0  0.7  97924  7312 ?        Ss   14:18   0:00 /usr/sbin/globus-gridftp-server -c /etc/gridftp.conf -C /etc/gridftp.d -pidfile /var/run/globus-gridftp-server.pid -no-detach -config-base-path /
----terminal

If you do not see an instance of globus-gridftp-server running, then the service has not started. You can try to start it by executing the `globus-connect-server-setup` command and then checking to see if an instance of globus-gridftp-server appears in the `ps` output. If you still don't see an instance of globus-gridftp-server running after issuing the `globus-connect-server-setup` command, you can take a look in the xref:gridftp_server_log_files[logs] for clues as to what might be wrong.

If there is an instance of globus-gridftp-server running, you can then check to see if you can connect to it locally via the `telnet` command: 

----terminal
# telnet 127.0.0.1 2811
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
220 ip-172-31-31-13.us-west-2.compute.internal GridFTP Server 7.26 (gcc64, 1433516164-85) [Globus Toolkit 6.0.1428430525 GCS-4.0.18] ready.
----terminal

If there is an instance of globus-gridftp-server running, but you can't connect locally, then there is probably a local firewall rule on the server that is interfering with your attempt to connect.

If you are successful with the local telnet connection, then try telnet again using the public FQDN associated with your server and see if that works. If you're not able to connect when using the public FQDN, then you may have a firewall issue or a name resolution issue that is preventing you from being able to connect properly.

==== Verify myproxy-server Service 
Another important check on servers hosting a Globus endpoint that use MyProxy for endpoint authentication is to verify that the 
myproxy-server service has properly started and is running. 
Note that not all endpoints use the MyProxy service, so this check is only useful if your endpoint uses MyProxy for endpoint authentication.
To run this check, first use the `ps` command to see if there is an instance of myproxy-server running:


----terminal
# ps aux | grep myproxy-server
root       602  0.0  0.1 110812  1112 ?        S    14:18   0:00 /usr/sbin/myproxy-server -s /var/lib/myproxy -c /var/lib/globus-connect-server/myproxy-server.conf -s /var/lib/globus-connect-server/myproxy-ca/store
----terminal

If you do not see an instance of myproxy-server running, then the service has not started. You can try to start it by executing the `globus-connect-server-setup` command and then checking to see if an instance of myproxy-server appears in the `ps` output. If you still don't see an instance of myproxy-server running after using the `globus-connect-server-setup` command, you can take a look in the xref:myproxy_server_log_files[logs] for clues as to what might be wrong.

If there is an instance of myproxy-server running, you can then check to see if you can connect to it locally via the `telnet` command:

----terminal
# telnet 127.0.0.1 7512
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
type something here and hit enter
VERSION=MYPROXYv2
RESPONSE=1
ERROR=authentication failed
Connection closed by foreign host.
----terminal

If there is an instance of myproxy-server running, but you can't connect locally, then there is probably a local firewall rule on the server that is interfering with your attempt to connect. 

If you are successful with the local telnet connection, then try telnet again using the public FQDN associated with your server and see if that works. If you're not able to connect when using the public FQDN, then you may have a firewall issue or a name resolution issue that is preventing you from being able to connect properly.

[[globus_help_resources]]
=== Globus Help Resources

==== Documentation Website
This website (link:https://docs.globus.org[docs.globus.org]) contains a wealth of information about configuring and using the Globus service. Many common issues can be resolved quickly by browsing our link:../faq[frequently asked questions] and reading the relevant guides and link:../how-to[how-to's]. We recommend consulting these resources first when looking for fast resolution to any issue you are having with the Globus service. 

==== Mailing Lists
If you use Globus, then participating in one or more of the public email lists is an excellent way to keep in touch with your peers in the Globus Community. For questions about managing your Globus deployment, e.g. installing software for a Globus endpoint, configuring your firewall, and integrating your institution’s identity system, subscribe to the admin list. For other inquiries and discussions, try the user or developer lists. For more information on mailing lists and how to subscribe, click https://www.globus.org/mailing-lists[here].

==== Globus Support
Questions or issues that pertain to 
Globus Connect Server installation
or to any client or service that is 
used in the Globus software-as-a-service (SaaS) or platform-as-a-service (PaaS) offering
can be directed to the Globus support team by submitting a 
link:{contact-us_url}[ticket].
link:{provider-plans_url}[Provider Plan] subscriptions include a guaranteed support service level.

When submitting a link:{contact-us_url}[ticket] for an issue with Globus Connect Server, please 
include the endpoint name, a description of your issue, and screenshot/text 
dumps of any errors you are seeing.
Please also include the output of the following commands, run as root, 
from the server hosting the GCS endpoint:

----terminal
uname -a
ifconfig
ping $(hostname -f)
cat /etc/issue
cat /etc/gridftp.d/*
cat /etc/gridftp.conf
globus-gridftp-server --version
grep -v "\^$\|^;" /etc/globus-connect-server.conf
----terminal

[[sharing_section]]
== Sharing
=== Description
Sharing makes it easier for an endpoint's users to grant and control access to their data stored on the endpoint. A more detailed description of the benefits and features of sharing can be found link:https://www.globus.org/data-sharing[here].

To illustrate let's consider a case in which Adam, who is employed by ABC University and is the admin of the abcu#ep1 endpoint, wants to enable sharing on his endpoint for some of his users - such as Bob, Sue, etc. - so as to allow them to share with their collaborators (e.g. Ann) who do not have local accounts.  In this case, Adam has decided that he wants to allow users to share out of the "globus" directory in their home directory and nowhere else.

=== Requirements
Sharing can only be enabled on a link:http://docs.globus.org/resource-provider-guide/#managed-endpoint-anchor[managed endpoint]. Only organizations with a link:https://www.globus.org/providers/provider-plans[Provider Plan] are able to create managed endpoints.

For Adam to be able to enable sharing on his abcu#ep1 endpoint he will first need to be sure that ABC University has a provider plan with Globus.

=== Make an endpoint managed
Instructions for how an organization with a provider plan can promote an existing endpoint to managed status can be found link:https://docs.globus.org/faq/subscriptions/#how_do_i_convert_an_existing_endpoint_into_a_managed_endpoint[here].

After ensuring that ABC University has a provider plan with Globus, Adam will
next need to make his endpoint managed. To do this he will log in to the Globus
CLI server using the "abcu" Globus account (instructions for how to do this can
be found link:http://docs.globus.org/cli/[here]) and he will then execute the following command:

----terminal
$ endpoint-modify --managed-endpoint abcu#ep1
----terminal

=== How to enable and disable sharing in Globus Connect Server
To enable sharing on a managed endpoint, "Sharing = True" must be set in the [GridFTP] section of the /etc/globus-connect-server.conf file. Once this option is set, and the globus-connect-server-setup command is run to effect the configuration change, a managed endpoint will have sharing enabled. Similarly, setting "Sharing = False" will disable sharing on the endpoint. Note: This configuration option will have no effect on an endpoint that is not managed.
Looking back to our use case with Adam, he will next need to log in (as root) to the server hosting the abcu#ep1 endpoint. He will then edit the /etc/globus-connect-server.conf file so as to set "Sharing = True" in the [GridFTP] section.

=== How to control sharing in Globus Connect Server
==== Controlling *what* can be shared
It is possible to control which file system paths on the endpoint are allowed for sharing via the "SharingRestrictPaths" option, which is also in the [GridFTP] section of the /etc/globus-connect-server.conf file. Remember, after making changes to the /etc/globus-connect-server.conf file it is necessary to run the ‘globus-connect-server-setup' command before those changes will take effect. Additional details about these configuration options can be found xref:gridftp_section[here] and also in the link:https://github.com/globus/globus-connect-server/blob/master/source/globus-connect-server.conf[globus-connect-server.conf] file itself.

==== Controlling *who* can share
Recall that our use case with Adam required that sharing be enabled for only certain users. At this point sharing is enabled for all users on the server hosting the abcu#ep1 endpoint. By editing the SharingUsersAllow, SharingGroupsAllow, SharingUsersDeny, and SharingGroupsDeny options in the [GridFTP] section of the /etc/globus-connect-server.conf file, Adam can restrict which local users on the server are allowed to create shares on the abcu#ep1 endpoint. By default, when no value is set for any of these options, GCS will allow sharing for all local user accounts. Any users or groups listed in the SharingGroupsDeny or SharingUsersDeny options will not be allowed to share. If any value is set for SharingUsersAllow or SharingGroupsAllow, then only users and groups explicitly listed in these options will be allowed to share.

[NOTE]
Any user who is listed in both the SharingUsersAllow and SharingUsersDeny options, or that has a group memberships such that the user is covered by both the SharingGropsAllow and SharingGroupsDeny options, will not be allowed to share.

Since Adam only wants to allow certain users to be able to share, he has decided to create a local unix group on his system and adds the users he wants to allow to share to that unix group. Adam thus creates the globus_sharing_allow unix group and then adds Bob's local user account to that group. Adam then edits his /etc/globus-connect-server.conf file and sets "SharingGroupsAllow = globus_sharing_allow". Adam next runs the globus-connect-server-setup command so that his configuration changes will take effect. With this change made, now all users who are members of the globus_sharing_allow group - such as Bob - will be able to share. Sue, who Adam has not yet added to the globus_sharing_allow group, is still unable to share. To address this, Adam adds Sue's local user account to the globus_sharing_allow group and Sue is then able to share. 

=== How to create and manage shares
Instructions for how to create and manage access to a share on a managed endpoint can be found link:../how-to/share-files/[here].

=== Details on effective share permissions
The share permissions you grant to a Globus user are just one part of the puzzle in determining that user's actual level of access to a shared endpoint. To accurately determine the effective permissions that a user will have to a share we must also consider local file system permissions. In the case of a shared endpoint, all users accessing the share have the same local file system permissions as the local user that was used to activate on the endpoint to create the share. When considering the effective permissions that a user has to a share, it is important to remember that the most restrictive of the Globus permissions and the local file system permissions will determine access.

==== Local user creating a shared endpoint

To illustrate with an example, let's consider Bob who wants to create a share on endpoint abcu#ep1. Bob has a local account on the server hosting abcu#ep1 with username of bob_local. Bob's Globus account is bob_globus. When Bob wants to create his share hosted by abcu#ep1, he will log into the Globus website using his bob_globus credentials. He will then activate on the abcu#ep1 endpoint using his bob_local credentials. At that point, Bob can create his share. Let's say Bob creates a share named bob_globus#myshare, which points to the /home/bob_local/globus directory. Now, Bob can assign share permissions to other users that he wants to have access to his share. He can give Globus users read or write permissions to the share as he desires. 

==== Local user sharing with another local user

Let's say that Bob gives Sue - who has a Globus account of sue_globus and a local account of sue_local - read and write access to the share. Now, if Sue wants to access the bob_local#myshare share, she will log into the Globus website using her sue_globus credentials. At this point, Sue's ability to access the bob_local#myshare share depends on both the share permissions that Bob granted the sue_globus Globus user to the share, as well as the file system permissions that the local bob_local account has to the file system that the share points to. Even if Sue has read and write access at the share level, she still won't - for example - be able to write to the share if the bob_local local user doesn't have write permissions at the file system level in the file system space that the share points to. Notice that the permissions (or lack thereof) for the sue_local account played no role in determining Sue's access to the share. 

==== Local user sharing with a non local user

Along the same lines let's consider what happens when Bob grants share access to Ann, who has a Globus account of ann_globus - and no local account on the server. For this example let's say that Bob grants the ann_globus account read and write access to the bob_local#myshare share - which are the same permissions that he granted Sue. As sue_globus and ann_globus have identical share permissions, they now have identical levels of access to the share. 

==== Summary

To sum up, both the share permissions granted to a Globus user, as well as the file system rights of the local user that the Globus user (who owns the share) activated on the endpoint with when the share was created, must be taken into account when determining effective permissions to a share. 

== [go-icon-pp]#Management Console#
The management console, available on xref:managed-endpoint-anchor[managed endpoints], 
provides a graphical web interface that can be used to monitor endpoint activity and to 
identify and troubleshoot faults that may indicate underlying infrastructure issues. 
An organization's link:{provider-plans_url}[Provider Plan] 
support contact(s) decide who has access to the management console. 

You can read about the details and benefits of the management console link:../management-console-guide/[here].

:numbered!:

[appendix]
[[data_channel_traffic]]
== Understanding Data Channel Traffic
The data channel is where Globus Connect Server actually transmits the data that is 
being moved between endpoints. The default port range used for data channel connections 
is TCP 50000 to 51000. We strongly recommend that all endpoints be configured to use the 
default data port range, as this will provide maximum compatibility with other
endpoints that are also configured to use the default data port range and have
their firewall rules configured to allow traffic in this range. If your endpoint 
uses a non-default data port range, then you are - in effect - requiring other 
sites to potentially have to create additional firewall rules in order to be able
to communicate properly with your endpoint. Many sites will not want to do this, 
which will thus limit the ability of your endpoint to interoperate with the majority 
of endpoints which are configured to use the default port range. 

If two endpoints (ep1 and ep2) are to be able to successfully conduct
transfers, then those endpoints must each be able to connect to each other
in their configured data port ranges. For example, consider the following:

Globus Connect Server ep1 uses data port range 40000 to 41000 

Globus Connect Server ep2 uses data port range 50000 to 51000

When two Globus Connect Server endpoints attempt to conduct a transfer, the endpoint 
that will be the recipient in that transfer picks out a port (or ports) in its configured 
data port range that it will listen on to receive the the transfer from the sender endpoint. 
This port value gets communicated back from the receiver endpoint to the sender endpoint 
via GridFTP control channel data mediated by the Globus service, which both the sender and 
recipient are listening to on port 2811. Once the sender endpoint receives the data port 
range info for the recipient endpoint, it then initiates an outbound connection to the 
recipient to that port (or ports) on the recipient to conduct the actual data transfer. 

To illustrate, consider the case of ep1 and ep2 mentioned above. If ep1 wanted to send ep2 a 
file, then ep2 would pick out a port (or ports) in its configured data port range of 50000 to 
51000. For the sake of example let's say that port 50021 has been chosen. This value would 
then get communicated from ep2 to ep1, via the Globus service through the GridFTP control channel 
that both ep1 and ep2 are listening to. At that point, ep1 would then initiate a 
connection out to port 50021 on ep2. 

To further illustrate, consider again the case of ep1 and ep2 mentioned above. If ep2 wanted 
to send ep1 a file, then ep1 would pick out a port (or ports) in its configured data port 
range of 40000 to 41000. For the sake of example let's say that port 40331 has been chosen. 
This value would then get communicated from ep1 to ep2, via the Globus service through the GridFTP 
control channel that both ep1 and ep2 are listening to. At that point, ep2 would 
then initiate a connection out to port 40331 on ep1.

It is also important to consider what happens in cases where one endpoint is a Globus Connect 
Server endpoint and the other endpoint is a Globus Connect Personal endpoint. In such cases, 
the Globus Connect Personal endpoint will always initiate the connection to the Globus 
Connect Server endpoint for the transfer. Thus, it will always be the Globus Connect Server 
endpoint that picks the port (or ports) on which it will listen for that connection. This is the 
case irrespective of which endpoint is the sender or the recipient. As discussed previously, this 
information gets communicated from the Globus Connect Server endpoint to the Globus Connect 
Personal endpoint via the Globus service. 

After looking at the example given we can see that, in terms of firewall rules, the outbound
rules for ep1 must allow it to connect outbound to ep2 on ep2's configured data port range if 
ep1 is to be able to send files to ep2. In terms of inbound rules, the firewall rules for 
ep1 must be configured to allow it to accept inbound connections on its own configured data 
port range for it to be able to receive files from other endpoints. The firewall rules for the 
data port range of any endpoint will be similar, and must allow outbound connections to the 
configured data port range of a remote endpoint for the local endpoint to be able to send files to 
the remote endpoint, and must allow inbound connections to the configure data port range of the 
local endpoint for that endpoint to be able to receive files from other endpoints.

As illustrated, an endpoint must be able to receive inbound connections on its own configured 
data port range, as well as be able to make outbound connections to the data port range of any 
endpoint it wishes to communicate with. If all Globus Connect Server admins pick their own 
custom port ranges, then this quickly leads to a situation in which site firewall policies 
become littered with custom rules for these various port ranges and endpoints. However, if 
everyone uses the default data port range, then firewall rules are much more predictable and 
manageable. It is for this reason that we recommend that everyone use the default data port 
range for their endpoint. Those who use a custom data port range may find that they have 
problems with their endpoint being able to communicate with other endpoints, for the reasons 
detailed above. Those using custom data port ranges may also find that the admins of other 
sites and endpoints may not be willing to set up custom firewall rules to accommodate custom 
data port range choices.

[appendix]
== Globus Connect Server Configuration Packages
Globus Connect Server is delivered as a set of packages that may be used to configure and update services for use on a Globus endpoint. The most commonly used package is globus-connect-server. It is used to configure all services for a Globus endpoint on a server and creates configuration files for the various services based on a common Globus endpoint configuration file. Using the default configuration file will configure and enable all services needed to create a single-server endpoint (see configuration file example link:https://github.com/globus/globus-connect-server/blob/master/source/globus-connect-server.conf[here]).

The configuration file is parsed by globus-connect-server-setup (man page link:http://globus.github.io/globus-connect-server/globus-connect-server-setup.html[here]), which is run when an endpoint is initially created or its configuration is updated. This file is also parsed by globus-connect-server-cleanup (man page link:http://globus.github.io/globus-connect-server/globus-connect-server-cleanup.html[here]), which is run when it is desired to clean up the old endpoint configuration on the server. Both of these commands work by calling various component scripts that are sub-packages of the globus-connect-server package.

In addition to the consolidated globus-connect-server package, there are sub-packages, each with their own configuration programs which operate on the Globus Connect Server configuration file. Each sub-package operates on one of the services as described below, and depends on the packages needed to configure that service. The sub-packages are:

- globus-connect-server-io may be used to install a Globus GridFTP server that implements a file transfer service.
- globus-connect-server-id may be used to install a Globus MyProxy server that implements an identity provider service.
- globus-connect-server-web may be used to install a MyProxy OAuth server that integrates the MyProxy service with a branded web interface.

Installing one of these sub-packages does not configure the services. The administrator must run the setup program associated with that package in order to actually do the configuration. Likewise, when one of the sub-packages is removed, it does not disable the service that it was used to configure; this is done by running the cleanup program associated with the sub-package.

=== Globus Connect Server I/O

The *globus-connect-server-io* package configures a GridFTP server. The main actions executed by this package during setup and cleanup are described below. This package depends on the authorization callouts, MyProxy (client side) programs, and the GridFTP server program.

globus-connect-server-io-setup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-io-setup.html[here])

- Fetch a certificate from the Globus Connect CA and write GridFTP configuration to use it
- Write GridFTP configuration to enable sharing (note: sharing may only be enabled on managed endpoints with a valid 
link:{provider-plans_url}[Provider Plan] subscription)
- Fetch MyProxy trust roots (if configured to use a MyProxy server)
- Write GridFTP configuration for authorization callouts
* If using CILogon, install CILogon CA and CRLs in the globus-connect-server certificate directory and add a cron job to refresh the CRL
* If using a remote MyProxy server, fetch the MyProxy service certificate and trust roots and install them into the globus-connect-server certificate directory
- (Re)start the GridFTP server
- Enable the GridFTP server to start on reboots
- Bind the GridFTP server to a Globus endpoint

globus-connect-server-io-cleanup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-io-cleanup.html[here])

- Remove Globus Connect CA certificate if used
- Remove GridFTP service configuration
- Remove the Globus endpoint binding
- Remove CILogon CRL cron job
- Stop the GridFTP service
- Disable the GridFTP service

Please see the command line tools for managing an I/O node configuration for more information.

=== Globus Connect Server Identity

The *globus-connect-server-id* package is used to configure a MyProxy identity service. This service can be configured as an identity provider using system passwords or as a certificate store for certificates generated elsewhere. The default configuration method for Globus Connect Server is as an identity provider. As an identity provider it will generate short-lived certificates for users if they are able to authenticate with their login password. As a certificate store, certificates are generated by some process outside of MyProxy and may be added to the store by the normal MyProxy Commands. This package depends on the MyProxy server and globus-simple-ca.

globus-connect-server-id-setup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-id-setup.html[here])

- Fetch a certificate from the Globus Connect CA and write MyProxy server configuration to use it
- Set up the MyProxy CA if acting as an identity provider
- (Re)start the MyProxy server
- Enable the MyProxy server to start on reboots

globus-connect-server-id-cleanup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-id-cleanup.html[here])

- Stop the MyProxy CA service
- Disable the MyProxy CA service

=== Globus Connect Server Web

The *globus-connect-server-web* package is used to configure a MyProxyOAuth identity service. This service provides a web interface to a MyProxy service, which may be running on the same node or elsewhere. This web interface may be customized by adding site-specific style sheets and images to make it conform to the look of the organization running the service.

globus-connect-server-web-setup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-web-setup.html[here])

- Enable mod_ssl and the default SSL site if needed
- Copy the OAuth site configuration to /etc/httpd/conf.d (rpm) or /etc/apache2/conf.d (deb)
- Restart the web server
- Enable the web server to start on reboots

globus-connect-server-web-cleanup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-web-cleanup.html[here])

- Disable mod_ssl and the default SSL site if we enabled it during setup
- Remove the OAuth site configuration file from /etc/httpd/conf.d or /etc/apache2/conf.d
- Restart the web server

[appendix]
[[update_section]]
=== How to update a Globus Connect Server install
The Globus team is improving the Globus Connect Server software all
the time, occasionally, you should update your software to get all the
latest bug fixes and improvements.

If you are using a version of Globus Connect Server released prior to GT 6,
then please see our upgrade instructions xref:upgrade_section[here].

If you are using a Globus Connect Server version based on GT 6 or later, then
follow these instructions to update your install:

.Red Hat Enterprise Linux, CentOS, Scientific Linux, Fedora
----terminal
$ sudo yum update \\*globus\* \\*myproxy\* \\*gsi-openssh\*
----terminal

.SuSE Linux Enterprise Server
----terminal
$ sudo zypper refresh
$ sudo zypper up \\*globus\* \\*myproxy\* \\*gsi-openssh\*
----terminal

.Debian, Ubuntu
----terminal
$ sudo apt-get update
$ sudo apt-get install --only-upgrade ".\*globus.\*" ".\*myproxy.\*" ".\*gsi-openssh.*"
----terminal

After updating your packages, be sure to restart the services and ensure that the update takes full effect by running:
----terminal
$ sudo globus-connect-server-setup
----terminal

[appendix]
[[upgrade_section]]
=== Upgrading from an older (<GT6) version of Globus Connect Server

If you have an old Globus Connect Server install that you want to upgrade, 
be sure to remove the old Globus Connect Server packages and config, as well 
as to delete your endpoint definition so that it can be recreated cleanly 
during the new install:

.All Distributions
----terminal
$ sudo globus-connect-server-cleanup
----terminal

After cleaning up your old endpoint definition (if appropriate) remove the old Globus packages like so:

.Red Hat Enterprise Linux, CentOS, Scientific Linux, Fedora
----terminal
$ sudo yum remove \\*globus\*
$ sudo yum remove \\*myproxy\*
----terminal

.SuSE Linux Enterprise Server
----terminal
$ sudo zypper remove \\*globus\*
$ sudo zypper remove \\*myproxy\*
----terminal

.Debian, Ubuntu
----terminal
$ sudo apt-get purge ".\*globus.\*"
$ sudo apt-get purge ".\*myproxy.*"
----terminal

Finally, ensure that you remove old config that might still be left behind after removing the packages:

.All Distributions
----terminal
$ sudo rm /etc/globus-connect-server.conf 
$ sudo rm -r /etc/grid-security 
$ sudo rm -r /var/lib/globus-connect-server
$ sudo rm /etc/gridftp.conf
----terminal

At this point, your environment is clean and you can follow the instructions 
xref:install_section[here] to put down a clean install of Globus Connect Server to recreate 
and upgrade your endpoint.

[appendix]
[[myproxy_identity_provider_section]]
=== Configuring an endpoint to use the MyProxy identity provider
To configure an endpoint to use the MyProxy identity provider, set "IdentityMethod = MyProxy" in the [Security] section of the config file and set the +Server+ option in the [MyProxy] section to the hostname of the MyProxy server to be used for the endpoint. The default settings in the +/etc/globus-connect-server.conf+ file will configure an endpoint to use MyProxy as the identity provider. If the servers on your endpoint are using NAT, then be sure to reference the xref:nat_section[NAT] section for additional configuration details.

[appendix]
[[oauth_identity_provider_section]]
=== Configuring an endpoint to use the OAuth identity provider
To configure an endpoint to use the OAuth identity provider, set "IdentityMethod = OAuth" in the [Security] section of the config file and set the +Server+ option in the [OAuth] section to the hostname of the OAuth server to be used for the endpoint. If the servers on your endpoint are using NAT, then be sure to reference the xref:nat_section[NAT] section for additional configuration details. If you wish to use OAuth then you may wish to consider these additional options as well:

- You may wish to use a CA issued ssl/tls server certificate for your web server. The exact details for setting this up will vary depending on the format that your CA provides your certificate to you in, your apache web server configuration, as well as the OS and version you are using. In all cases you'll need to edit your apache configuration to set the "SSLCertificateFile" directive to point at the cert file you were issued by your CA. You may also need to set the "SSLCertificateKeyFile" and "SSLCertificateChainFile" directives as well, depending on the format of your certificate and the instructions you received from your CA concerning how to install the cert.

- You may wish to use a custom logo or custom CSS to give your OAuth page a look and feel more consistent with your organization. You can configure a custom CSS by setting the +Stylesheet+ option in the [OAuth] section of the +/etc/globus-connect-server.conf+ file to the file containing the style sheet you wish to use. You can set a custom logo by setting the +Logo+ option in the [OAuth] section of the +/etc/globus-connect-server.conf+ file to the image file of the logo you wish to use.

[appendix]
[[cilogon_identity_provider_section]]
=== Configuring an endpoint to use the CILogon identity provider
To configure an endpoint to use the CILogon identity provider, set "IdentityMethod = CILogon" in the [Security] section of the config file and set the +CILogonIdentityProvider+ option in the [Security] section to the name of the CILogon provider to be used with the endpoint. See https://cilogon.org/ for a list of valid providers. 

An endpoint configured in this way will attempt to map the CILogon credential to a local account on the server hosting the endpoint by matching it with a local account with the same account name as provided in the InCommon eduPersonPrincipalName (ePPN) given with the CILogon credential. Organizations participating in CILogon must make certain that their Shibboleth server releases the ePPN attribute to CILogon for this to work. To check if an identity provider is supplying the ePPN check link:https://cilogon.org/secure/testidp/[here]. 

[appendix]
[[s3_setup_section]]
=== [go-icon-pp]#Setting up an endpoint on Amazon S3#
Organizations with
link:{provider-plans_url}[Provider Plan] subscriptions can set up 
link:{s3_url}[Amazon S3]-based 
endpoints.  Instructions are provided at the following link:

https://www.globus.org/amazon-web-services/s3-endpoint-configuration

[appendix]
=== Setting Endpoint Network Use Options
Globus transfer uses configured network use levels and location of an endpoint to determine performance parameters to set on transfers against the endpoint. Administrators of endpoint may override the default values to best suit their deployment and needs. The configuration settings from source and destination endpoints are used to determine the concurrency and parallelism options used for a given transfer, thus leveraging the available transfer capacity, without overwhelming smaller capacity endpoints during transfers with larger capacity endpoints. 

The location parameter is used to determine the distance and hence expected latency between the two endpoints, and is used in the automatic tuning of the transfers. By default the value of location parameter is automatically determined by Globus, but can be set by the endpoint administrator to explicit coordinates (in decimal degrees). This parameter cannot be set for S3 endpoints or shared endpoints. 

Network use is set to “Normal” level by default. An administrator of a managed endpoint can set the network use levels for transfers against their endpoint. Endpoints that have multiple physical servers, and good end to end connectivity (network and storage) can set higher network use to ensure that Globus uses the bandwidth available, while smaller deployments can set this to lower levels.

Three preset options are provided for the endpoint administrator, which have the following values:

[options="header"]
|=========================
|Option |Value
|Minimal |MaxConcurrency = 1

PreferredConcurrency = 1

MaxParallelism = 1

PreferredParallelism = 1
|Normal (Default) |MaxConcurrency = number of servers * 4

PreferredConcurrency = number of servers * 2

MaxParallelism = 8

PreferredParallelism = 4
|Aggressive |MaxConcurrency = number of servers * 8

PreferredConcurrency = number of servers * 4

MaxParallelism = 16

PreferredParallelism = 4
|=========================

*Note:* S3 endpoints do not support parallelism options, only concurrency. 

In addition to above, an administrator can choose the "Custom" option that lets them set absolute values for both concurrency and parallelism. All these options have a limit of 64 for MaximumConcurrency and MaximumParallelism. These values can be modified by using the —network-use option on endpoint-modify command in the Globus CLI. 

For a given transfer, the concurrency is calculated as the smallest value across the MaximumConcurrency values of both endpoints, and the maximum of the PreferredConcurrency of both endpoints. Parallelism is also calculated similarly, with an additional consideration for transfers with high latency (trans-oceanic transfers) where the parallelism is set to minimum of the Maximum Parallelism value set for both endpoints.

[glossary]
== Glossary
[[access-manager-anchor]]Access Manager::
  The access manager role grants the ability to control read and/or write access permissions for 
  other Globus users on a shared endpoint. You can read a more in-depth discussion link:https://globus.org/blog/access-manager-role-shared-endpoints[here].
[[endpoint-anchor]]Endpoint::
  This is general term used to refer to a specific service that Globus can use to perform 
  file transfers and other functions. For example:
* I transferred files to the endpoint
* I created a share for you on the endpoint
* The endpoint's file system is fast
[[endpoint-definition-anchor]]Endpoint Definition::
  This term refers to the metadata about the endpoint, stored as an object in the 
  Globus.org database, used to simplify using and referring to the 
  xref:endpoint-anchor[endpoint] for 
  users. Examples of such metadata include the hostname, port, OAuth server, default directory, 
  etc... Much of the information in the endpoint definition is sent to Globus when the 
  globus-connect-server-setup command is run.
[[endpoint-name-anchor]]Endpoint Name::
  The name of your endpoint uniquely identifies it among all Globus endpoints 
  and allows others to search for and find your endpoint via the Globus service. A full endpoint 
  name takes the form of: ORGANIZATION_ACCOUNT_NAME#UNIQUE_SHORT_NAME.
  As indicated, the first part of an endpoint's full name is the name of the
  xref:organization-account-anchor[organization account] that was used to 
  create the endpoint. The first part of the endpoint name will be the same for all endpoints 
  in your organization. The second part of the endpoint name will be unique 
  within your organization. It is a good idea choose something that describes
  the purpose of the endpoint as the second part of the endpoint name;
  doing so makes it easier for users to find the particular endpoint they are looking for. 
  For example, if ABC University (with an organization account name of "abcu") had a geosciences-related endpoint, 
  they might name it abcu#geosciences.
[[gridftp-anchor]]GridFTP::
  GridFTP is an extension of the standard File Transfer Protocol (FTP)
  for high-speed, reliable, and secure data transfer.
  See the link:{gridftp_url}[GridFTP documents] for more information.
[[managed-endpoint-anchor]]Managed Endpoint::
  A managed endpoint is an xref:endpoint-anchor[endpoint] that is covered under a 
  link:https://www.globus.org/providers/provider-plans[provider plan] and 
  allows advanced features (like xref:sharing_section[sharing]) to be enabled. To convert an existing 
  endpoint into a managed endpoint see this link:../faq/subscriptions/#how_do_i_convert_an_existing_endpoint_into_a_managed_endpoint[writeup]. 
[[myproxy-anchor]]MyProxy::
  MyProxy is open source software for managing X.509 Public Key
  Infrastructure (PKI) security credentials (certificates and private
  keys).
  See the link:{myproxy_url}[MyProxy website] for more information.
[[oauth-for-myproxy-anchor]]OAuth for MyProxy::
  OAuth for MyProxy provides an OAuth-compliant REST web interface to
  the MyProxy service for providing user certificates to Globus.
  See the 'OAuth' section of the link:{myproxy_url}[MyProxy webpage] for more
  information.
[[organization-account-anchor]]Organization Account::
  This is a regular Globus account, but it will be used for a specific purpose for you organization.  It will be used to create and manage endpoints for your organization. It is a good idea to pick an account name that is easily recognized as being associated with your endpoints, as the name of your Organization account will be the first part of the endpoint name for every endpoint created for your organization. For example, ABC University might create the organization account of "abc" or “abc”, which would allow them to create the endpoint abc#myhpcmachine in the organization account.  Please do not choose account names that correspond to copyrighted or trademarked terms unless your organization has rights to those terms. 
[[shared-endpoint-anchor]]Shared Endpoint::
  A shared endpoint enables a particular folder to be shared with other Globus users. Only 
  authorized users of a managed endpoint may create shared endpoints. One or more shared endpoints 
  may be created on a xref:managed-endpoint-anchor[managed endpoint]. The shared endpoint owner can 
  grant read/write permissions and assign the xref:access-manager-anchor[access manager] role for the shared endpoint.


