= Globus Resource Provider Guide
:revnumber: 0.0.2c
:toc:
:toc-placement: manual
:toclevels: 3
:numbered:

// Define some attributes to reuse in-line
:website: http://www.globus.org/
:gridftp: http://toolkit.globus.org/toolkit/docs/latest-stable/gridftp/
:researchers: http://www.globus.org/researchers/
:providers: http://www.globus.org/providers/
:provider_plans: http://www.globus.org/providers/provider-plans/
:commercial_plans: http://www.globus.org/providers/provider-plans/commercial-subscription-inquiry/
:sign_up: http://www.globus.org/signup/
:contact_us: http://www.globus.org/contact-us/
:transfer: http://www.globus.org/xfer/StartTransfer#/

// Other sites
:myproxy: http://grid.ncsa.illinois.edu/myproxy/

[doc-info]*Last Updated: {docdate}*

toc::[]

== Introduction

Globus allows you, as a resource provider, to easily offer reliable, secure,
high-performance research data management capabilities to your users
and their collaborators, directly from your own storage.
Globus is software as a service (SaaS), enabled by the cloud and
designed to let users manage their research files,
regardless of number and size,
as effortlessly as they manage their photos with popular cloud-based services.
Globus lets you provide authorized users with web, command line, and REST interfaces
for listing, transferring, replicating, and sharing
directories and files on your Globus-connected storage resources.
You can learn more about Globus capabilities and benefits from the
{researchers}[researcher]
and
{providers}[resource provider] overview pages.

This guide is written primarily for system administrators of multi-user Linux
systems who want to take full advantage of Globus capabilities and optimize 
the connection of their resources to the globus.org SaaS service.
Administrators who are installing Globus for the first time, as well as those with
considerable experience, should all find helpful information in this
document.

Starting with the basics, this guide covers the initial
installation of
_Globus Connect Server_ and the creation of a Globus _endpoint_ that
lets authorized users transfer files between your storage and other
Globus endpoints.
The Globus Connect Server installation downloads
(1) Globus versions of 'GridFTP', 'MyProxy', and 'OAuth for MyProxy';
(2) scripts for set up/configuration and integration into the globus.org SaaS service; 
and (3) Globus-maintained dependency packages needed by the other components.

.[go-icon-pp]#Provider Plan Features#
[NOTE]
====
Globus file transfer is free-of-charge for non-profit research and educational use.
Some premium Globus features described in this guide are only available to
{provider_plans}[Provider Plan subscribers].

Provider Plan subscriptions and 
{commercial_plans}[commercial Provider plans] help ensure that Globus can
continue to serve the research data management needs of
non-profit users for many years to come.
====

== Globus Connect Server Prerequisites

Confirm that the prerequisites listed in this section are met before you 
begin to install Globus Connect Server on your system.
Please {contact_us}[contact us] if you have problems understanding
or satisfying the prerequisites.

=== Supported Linux distributions
Globus Connect Server is currently supported on the following Linux
distributions:

- CentOS 5, 6, and 7
- Debian 6 and 7
- Fedora 19 and 20
- Red Hat Enterprise Linux 5, 6, and 7
- Scientific Linux 5, 6, and 7
- SuSE Linux Enterprise Server 11sp3
- Ubuntu 10.04 LTS, 12.04 LTS, 14.04 LTS and 14.10

=== Administrator privileges
You must have administrator (root) privileges on your system
to install Globus Connect Server;
`sudo` can be used to perform the installation.

=== System time synchronization
Ensure that `ntpd`, or another daemon for synchronizing
with standard time servers, is running on your system.

=== Internet-accessible system
Before you can install Globus Connect Server onto a server, you must ensure that 
other hosts on the Internet can initiate connections to your server. If your 
server is NATed then xref:nat_section[see below]. Otherwise, you must ensure that your server
is assigned a publicly resolvable DNS name that points to a public IP address that is properly assigned to your server. 

==== Check hostname local DNS resolution
To check accessibility, first execute this command
on the system where you plan to install Globus Connect Server:
----terminal
$ hostname -f
----terminal
Confirm that a fully qualified domain name (FQDN) is returned, e.g. ep1.transfer.globus.org.

==== Check hostname external DNS resolution
Next, use a public DNS server operated by a different organization to
verify that the returned FQDN is publicly resolvable.
More concretely, you could use `nslookup` to check that your server's 
FQDN resolves against one of Google's public DNS servers:
----terminal
$ nslookup [input]#'ep1.transfer.globus.org'# 8.8.4.4
----terminal
If you get a message of the form '`** server can't find ep1.transfer.globus.org: NXDOMAIN'',
your system's hostname is not resolvable via public DNS, and you need to 
resolve the issue before continuing with the installation. 
{contact_us}[Contact us] if you need assistance.

Some sites use network address translation (NAT) with a private
internal IP, private internal DNS, and a public DNS tied to a public
IP that gets forwarded to the private IP by the firewall/router.
Globus can be successfully installed at these sites, but, you will need to the edit the configuration file (a default config will not work). Please see the xref:nat_section[NAT] section if your site uses NAT.

[[open-tcp-ports]]
=== Open TCP ports
If your system is behind a firewall, TCP ports must be open as specified 
for Globus to work.
The default Globus Connect Server installation requires these TCP
ports be open:

- Port 2811 inbound from 184.73.189.163 and 174.129.226.69
* This is for GridFTP control channel traffic
- Ports 50000--51000 inbound and outbound to/from Any
* This is for GridFTP data channel traffic
* Data channel traffic is sent directly between endpoints, and is not
proxied/intermediated by Globus servers
* We strongly recommend the use of the default range (read why xref:data_channel_traffic[here])
- Port 2223 outbound to 184.73.255.160
* This is to pull cert info from our backend
- Port 443 outbound to nexus.api.globusonline.org and 174.129.226.69
* nexus.api.globusonline.org is a CNAME for an Amazon 
link:http://aws.amazon.com/elasticloadbalancing/[ELB], IP addresses 
in the ELB are subject to change
* This is to communicate with our REST API
- Port 80 outbound to 192.5.186.47
* This is to pull packages from our repo
- Port 7512 inbound from 174.129.226.69
* This is for MyProxy traffic
* Needed if server will run MyProxy service
- Port 443 inbound from Any
* This is for OAuth traffic
* Needed if server will run OAuth service
* OAuth traffic will come directly from clients using your OAuth 
service, and will not be proxied/intermediated by Globus servers

=== Globus account for your organization
You will need a Globus xref:organization-account-anchor[organization account] 
for your organization that is distinct from your personal Globus account.

[[install_section]]
== Globus Connect Server Installation and Endpoint Creation
This section covers the installation of Globus Connect Server and
the set up of a Globus endpoint with the default configuration--the
recommended starting point for new resource providers.
You will be able to fine-tune this configuration later without doing a
reinstall.

Before continuing, it is important to confirm that the prerequisites
detailed in the link:#globus_connect_server_prerequisites[previous section]
have been met.

=== Install Globus Connect Server
Skip to the appropriate section for your Linux distribution and
follow the instructions to install Globus Connect Server
on your system.

==== CentOS, Fedora, Red Hat Enterprise Linux, Scientific Linux
First, add the Globus Connect Server repository to your package management
system:

----terminal
$ sudo curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
$ sudo rpm --import http://toolkit.globus.org/ftppub/globus-connect-server/RPM-GPG-KEY-Globus
$ sudo yum install globus-connect-server-repo-latest.noarch.rpm
----terminal

Next, if you are running
CentOS 5, Red Hat Enterprise Linux 5, or Scientific Linux 5,
add the additional required repository:
----terminal
$ sudo curl -LOs http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm
$ sudo yum install epel-release-5-4.noarch.rpm
----terminal

Finally, install Globus Connect Server:
----terminal
$ sudo yum install globus-connect-server
----terminal

==== SuSE Linux Enterprise Server
First, add the Globus Connect Server repository to your package management
system:
----terminal
$ sudo curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
$ sudo rpm --import http://toolkit.globus.org/ftppub/globus-connect-server/RPM-GPG-KEY-Globus
$ sudo zypper install globus-connect-server-repo-latest.noarch.rpm
----terminal

Next, retrieve and install the additional required repositories:
----terminal
$ sudo zypper ar http://download.opensuse.org/repositories/Apache/SLE_11_SP3/Apache.repo
$ sudo zypper ar http://download.opensuse.org/repositories/Apache:/Modules/Apache_SLE_11_SP3/Apache:Modules.repo
$ sudo rpm --import http://download.opensuse.org/repositories/Apache/SLE_11_SP3/repodata/repomd.xml.key
$ sudo rpm --import http://download.opensuse.org/repositories/Apache:/Modules/Apache_SLE_11_SP3/repodata/repomd.xml.key
$ sudo zypper remove libapr1
----terminal

Finally, install Globus Connect Server:
----terminal
$ sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-Globus
$ sudo zypper install globus-connect-server
----terminal

==== Debian, Ubuntu
First, add the Globus Connect Server repository to your package management
system:
----terminal
$ sudo curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo_latest_all.deb
$ sudo dpkg -i globus-connect-server-repo_latest_all.deb
$ sudo apt-get update
----terminal

Then, install Globus Connect Server:
----terminal
$ sudo apt-get install globus-connect-server
----terminal

=== Create Globus Endpoint
Before creating your Globus endpoint,
edit the Globus Connect Server configuration file, installed at
+/etc/globus-connect-server.conf+,
and make two changes so that authorized users can find and access your endpoint.
The first thing you need to do is to choose a suitable xref:endpoint-name-anchor[endpoint name]. Next, edit the Globus Connect Server configuration file, installed at /etc/globus-connect-server.conf and set the Name to what you chose and set Public to true like in the example below:
----
[Endpoint]
Name = ep1
Public = True
----

After editing the configuration file, run:
----terminal
$ sudo globus-connect-server-setup
----terminal

When prompted, enter the Globus username and password for your
organization's Globus account.
When the +globus-connect-server-setup+ command completes, your Globus
endpoint is ready to be accessed by users with logins on your system.

=== Access Globus Endpoint

You (or any user on your system who has signed up for a Globus account) can now access the Globus endpoint you just created by navigating to the Globus link:https://www.globus.org/xfer/StartTransfer[Transfer Files] page. At this point, it's probably a good idea to run a couple of test transfers to ensure the functionality of your endpoint. For instructions on how to do this, click xref:testing_basic_endpoint_functionality[here].

== Globus Connect Server Configuration

From the initial (default) installation of Globus Connect Server,
you edited two configuration options in the
+/etc/globus-connect-server.conf+ file,
the +Name+ and +Public+ options in the +[Endpoint]+ section.
You probably noticed that there are many, many other options
that can be configured.
This section briefly covers a few of the most commonly changed
options in the +globus-connect-server.conf+ file. A detailed 
description of each option can be found 
link:https://github.com/globus/globus-connect-server/blob/master/source/globus-connect-server.conf[here]. After updating settings in the 
+/etc/globus-connect-server.conf+ file you must run the 
`globus-connect-server-setup` command (as root) before the settings
will take effect on your endpoint.

=== [Globus] section

==== +User+ and +Password+ options
These options can be used to set the username and password
of the Globus user that will be used when creating or updating
the endpoint definition.

=== [Endpoint] section

==== +Name+ option
This sets the name of the endpoint.

==== +Public+ option
This determines if the endpoint is publicly visible to all Globus users.

==== +DefaultDirectory+ option
This sets the default directory that users will be sent to when
first accessing an endpoint.

=== [Security] section

==== +IdentityMethod+ option
This option has three legal values: MyProxy, OAuth, and CILogon. For a graphical overview of the authentication flows each of these methods use, see link:https://support.globus.org/entries/27825216-Globus-Connect-Server-Authentication-Authorization-Flows[here].
If you wish to use MyProxy as your endpoint's identity method, then
you need to be sure to specify the +Server+ option in the [MyProxy]
section. If you wish to use OAuth as your endpoint's identity method, 
then you need to be sure to specify the +Server+ option in the [OAuth]
section, and may also need to specify the +Server+ option in the [MyProxy]
section if you are using MyProxy on the server to provide authentication 
for the OAuth service. If you are using CILogon, then you will also need to
specify the +CILogonIdentityProvider+ option in the [Security] section.

==== +CILogonIdentityProvider+ option
This option specifies the identity provider to use with CILogon. 
See https://cilogon.org/ for a list of valid providers.

=== [GridFTP] section

==== +Server+ option
This option specifies the hostname of the GridFTP server. This should
match the hostname of the server except, possibly, if NAT is being used. Can
be left blank if you don't want to configure a GridFTP server on this host.

==== +ServerBehindNAT+ option
This option specifies that the server is NATed. See the xref:nat_section[NAT] section 
for details.

==== +RestrictPaths+ option
This option can be used to prevent Globus users accessing the endpoint from 
accessing certain paths, or it can be used to restrict Globus users so that they 
can only access certain paths.

=== [MyProxy] section

==== +Server+ option
This option specifies the hostname of the MyProxy server. If you are running
the MyProxy server on this host, then this should match the hostname of this server 
except, possibly, if NAT is being used. If you are using a MyProxy server on a 
different host, then use the hostname of that host. Can be left blank if you don't 
want to configure a MyProxy server at all.

==== +ServerBehindNAT+ option
This option specifies that the server is NATed. See the xref:nat_section[NAT] section 
for details.

=== [OAuth] section

==== +Server+ option
This option specifies the hostname of the OAuth server. If you are running
the OAuth server on this host, then this should match the hostname of this server 
except, possibly, if NAT is being used. If you are using an OAuth server on a 
different host, then use the hostname of that host. Can be left blank if you don't 
want to configure an OAuth server at all.

==== +ServerBehindNAT+ option
This option specifies that the server is NATed. See the xref:nat_section[NAT] section 
for details.

[[nat_section]]
== NAT/Firewall support and configuration
The Globus Connect Server package provides configuration tools for several related services to enable administrators to easily configure a Globus endpoint. The globus-connect-server.conf file controls how the services used by Globus are configured, and includes configuration options to manage firewall-related configuration of services. Each service provided by the Globus Connect Server packages may be configured separately as described below.

Note that the descriptions below include examples of Globus Connect Server service configurations only. Configuring the firewalls themselves to allow the ports and host connections is not discussed. See the xref:open-tcp-ports[Open TCP ports] section for a discussions of 
the ports used by Globus Connect Server.

=== Configuring I/O Nodes
Globus Connect Server I/O nodes provide a GridFTP service to Globus. Options related to firewalls in the [GridFTP] section of the configuration file are: Server, ServerBehindNAT, IncomingPortRange, OutgoingPortRange, and DataInterface.

By default, Globus Connect Server configures the GridFTP server assuming that incoming TCP connections are allowed to port 2811, and the range 50000-51000 on the GridFTP server node.

==== Using GridFTP behind a NAT Firewall
To use a GridFTP behind a NAT firewall, set the Server option to the public name of the GridFTP server, and set the ServerBehindNAT option to True. This causes globus-connect-server-io-setup to generate GridFTP configuration for the node even if the Server name doesn't match the node's local hostname. This requires that the GridFTP server is visible from Globus at the address associated on the public internet with the name that is the Server value.

==== NAT Firewall Example
As an example, this configures the GridFTP server to run on the current host, using public-gridftp.example.org as its public name and listening on port 22811 instead of the default 2811. In order for this to work, the NAT firewall must allow connections to TCP port 22811 and the range 50000-51000 on the I/O node. By default, the Server name is used to construct the data interface name as well, but this behavior can be changed (see Using GridFTP with a Particular Data Interface).

----
[GridFTP]
Server = public-gridftp.example.org:22811
ServerBehindNAT = True
----

==== Using GridFTP with Firewall Port Restrictions
To use a GridFTP server with a firewall with incoming and/or outgoing port restrictions, use the IncomingPortRange and OutgoingPortRange configuration options. The former restricts the TCP port range that the GridFTP server listens on for ephemeral connections to a port range. The OutgoingPortRange restricts the TCP source port range that the GridFTP server uses when creating outgoing data connection sockets. For both of these items, the syntax of the port range is startport,endport, e.g. 50000,51000.

==== Port Restrictions Example
As an example, this configures the GridFTP server to listen for TCP connections on ports from 4000 to 5000 instead of the default 50000 to 51000. This will require configuration on the firewall to allow those ports to connect directly to the I/O node.

----
[GridFTP]
Server = public-gridftp.example.org:22811
IncomingPortRange = 4000,5000
----

==== Using GridFTP with a Particular Data Interface
The GridFTP server can also be configured to use a different IP address for its incoming data connections by setting the DataInterface option in the configuration file. By default, the GridFTP server will use the same IP address as that associated with the Server value. This can be altered, for example, to create a limited-use endpoint that uses a high-speed interconnect between I/O resources, but is not generally accessible from the internet.

==== Data Interface Example
As an example, this configures the GridFTP server to listen for TCP data connections on gig-e.example.org.

----
[GridFTP]
Server = public-gridftp.example.org:22811
DataInterface = gig-e.example.org
----

=== Configuring an ID Node
The Globus Connect Server ID node provides a MyProxy service. This service generates short-lived credentials which are used to authenticate with the GridFTP server. Globus may be configured to access this service directly, or access it via a web-based OAuth interface. This is chosen by the presence or absence of an [OAuth] section in the globus-connect-server.conf file.

By default, the MyProxy service listens on TCP port 7512. It makes no outgoing TCP connections. Like the GridFTP servers on the I/O nodes, the [MyProxy] section contains Server and ServerBehindNAT configuration options, which function like the ones in the GridFTP section.

If the MyProxy service is not being used directly by the Globus service (that is, if a OAuth server is being used), then the MyProxy service need only be reachable by the Web node and, during initial configuration, by the I/O nodes. No other nodes will require access the MyProxy service in normal operation.

==== Using MyProxy behind a NAT Firewall
To use a MyProxy server behind a NAT firewall, set the Server option to the public name of the MyProxy server, and set the ServerBehindNAT option to True. This causes globus-connect-server-id-setup to generate MyProxy configuration for the node even if the Server name doesn't match the node's local hostname. If you are configuring an OAuth server, the Server option must be accessible from the Web node and I/O nodes (during configuration); otherwise, it must be accessible from Globus.

==== NAT Firewall Example
As an example, this configures the MyProxy server to run on the current host, using public-myproxy.example.org as its public name and listening on port 17512 instead of the default 7512. In order for this to work, the NAT firewall must allow connections to the TCP port 17512 on the ID node.

----
[MyProxy]
Server = public-myproxy.example.org:17512
ServerBehindNAT = True
----

=== Configuring a Web Node
The Globus Connect Server Web node provides OAuth service to Globus. There are a few configuration options related to firewalls in the [OAuth] section of the configuration file. These are Server and ServerBehindNAT.

Unlike the other service nodes, the Web node is somewhat less configurable, as it relies on an external Apache server to accept TCP connections. Configuring the Apache server to listen on a different TCP port is out of scope of this note. The Server value may only contain a hostname, and the port 443 (https) is used. Globus does not support OAuth servers on alternate ports.

==== Using OAuth behind a NAT Firewall
To use an OAuth server behind a NAT firewall, set the Server option to the public name of the OAuth server, and set the ServerBehindNAT option to True. This causes globus-connect-server-web-setup to generate OAuth configuration for the node even if the Server name doesn't match the node's local hostname. This requires that the OAuth server is visible from Globus at the address associated on the public internet with the name that is the Server value.

==== NAT Firewall Example
As an example, this configures the OAuth server to run on the current host, using public-oauth.example.org as its public name. In order for this to work, the NAT firewall must allow connections to TCP port 433 on the web node.

----
[OAuth]
Server = public-oauth.example.org
ServerBehindNAT = True
----

== Generating and Monitoring Log Files

=== GridFTP Server Log Files

On recent versions of Globus Connect Server, the GridFTP log is located at:

`/var/log/gridftp.log`

On recent versions of Globus Connect Server, the configuration settings 
for the GridFTP log file are found at:

`/etc/gridftp.d/globus-connect-server-gridftp-logging`

On older versions of Globus Connect Server, logging for the GridFTP service is
 not enabled by default. In order to enable logging, it is necessary to specify 
the appropriate options in the GridFTP configuration files. One way to do this 
would be to create a text file named:

`/etc/gridftp.d/globus-connect-server-gridftp-logging`

Next, place the following options into the file:

----
log_single /var/log/gridftp.log
log_level ERROR,WARN
----

After saving the file, restart the GridFTP server with this command:

----terminal
$ sudo service globus-gridftp-server restart
----terminal

At this point, the GridFTP server will log all ERROR and WARN events to the
 `/var/log/gridftp.log` file. Additional details concerning logging for the 
GridFTP server are available in the `globus-gridftp-server` man page link:man/globus-gridftp-server/[here].

=== MyProxy Server Log Files

By default, the MyProxy server logs events to the LOG_DAEMON facility. This 
means that, by default, MyProxy events will be found in the following locations:

*CentOS, Fedora, Red Hat Enterprise Linux, Scientific Linux:*

`/var/log/messages`

*Debian/Ubuntu:*

`/var/log/syslog`

*SuSE Linux Enterprise Server:*

`/var/log/messages`

Please note that if the logging location for the LOG_DAEMON facility has been 
changed from the default in your syslogd config, then MyProxy events may be found 
in a different location. For further details concerning MyProxy please see the
 link:http://toolkit.globus.org/toolkit/docs/latest-stable/myproxy/[MyProxy Admin Guide].

=== MyProxy Delegation Service (myproxy­-oauth) Log Files

Events for myproxy­-oauth will be logged to the apache log file directory. By 
default, this will be found at the following locations:

*CentOS, Fedora, Red Hat Enterprise Linux, Scientific Linux:*

`/var/log/httpd/`

*Debian/Ubuntu:*

`/var/log/apache2/`

*SuSE Linux Enterprise Server:*

`/var/log/apache2/`

For further info on the MyProxy Delegation Service see the 
link:https://github.com/globus/globus-toolkit/blob/globus_6_branch/myproxy/oauth/source/README.md[README].

== Getting Help

=== Troubleshooting Common Problems
When experiencing problems with a transfer or an endpoint, it is a good idea
to run some basic tests to verify the basic functionality of the endpoint. This 
can help to narrow down the potential causes of the issue you are experiencing 
and simplify troubleshooting. 

[[testing_basic_endpoint_functionality]]
==== Testing Basic Endpoint Functionality
One important test to run to verify endpoint health is to check that the endpoint is able to properly conduct transfers to and from other endpoints. Globus maintains two test endpoints (go#ep1 and go#ep2) which are always available that users can leverage to test the functionality of their own endpoints. A good test is to attempt to transfer the contents of the `/share/godata/` directory on the go#ep1 endpoint to your own endpoint. After that, attempt to transfer those same files to the `/~/` directory on the go#ep2 endpoint. If these tests work, then you know that your endpoint is functional and is able to transfer files. For more detailed instructions on how to use the Globus service to transfer files, see link:https://www.globus.org/researchers/getting-started[here].

=== Support Tickets
When submitting a link:https://www.globus.org/contact-us[ticket] for an issue with Globus Connect Server please 
include the endpoint name, a description of your issue, and screenshot/text 
dumps of any errors you are seeing.

Please also include the outputs of the following commands, run as root 
from the server hosting the GCS endpoint:

----terminal
uname -a
ifconfig
ping $(hostname -f)
cat /etc/issue
cat /etc/gridftp.d/*
cat /etc/gridftp.conf
globus-gridftp-server --version
grep -v "\^$\|^;" /etc/globus-connect-server.conf
----terminal

:numbered!:

[appendix]
[[data_channel_traffic]]
== Understanding Data Channel Traffic
The data channel is where Globus Connect Server actually transmits the data that is 
being moved between endpoints. The default port range used for data channel connections 
is TCP 50000 to 51000. We strongly recommend that all endpoints be configured to use the 
default data port range, as this will provide maximum compatibility with other
endpoints that are also configured to use the default data port range and have
their firewall rules configured to allow traffic in this range. If your endpoint 
uses a non-default data port range, then you are - in effect - requiring other 
sites to potentially have to create additional firewall rules in order to be able
to communicate properly with your endpoint. Many sites will not want to do this, 
which will thus limit the ability of your endpoint to interoperate with the majority 
of endpoints which are configured to use the default port range. 

If two endpoints (ep1 and ep2) are to be able to successfully conduct
transfers, then those endpoints must each be able to connect to each other
in their configured data port ranges. For example, consider the following:

Globus Connect Server ep1 uses data port range 40000 to 41000 

Globus Connect Server ep2 uses data port range 50000 to 51000

When two Globus Connect Server endpoints attempt to conduct a transfer, the endpoint 
that will be the recipient in that transfer picks out a port (or ports) in its configured 
data port range that it will listen on to receive the the transfer from the sender endpoint. 
This port value gets communicated back from the receiver endpoint to the sender endpoint 
via GridFTP control channel data mediated by the Globus Service, which both the sender and 
recipient are listening to on port 2811. Once the sender endpoint receives the data port 
range info for the recipient endpoint, it then initiates an outbound connection to the 
recipient to that port (or ports) on the recipient to conduct the actual data transfer. 

To illustrate, consider the case of ep1 and ep2 mentioned above. If ep1 wanted to send ep2 a 
file, then ep2 would pick out a port (or ports) in its configured data port range of 50000 to 
51000. For the sake of example let's say that port 50021 has been chosen. This value would 
then get communicated from ep2 to ep1, via the Globus Service through the GridFTP control channel 
that both ep1 and ep2 are listening to. At that point, ep1 would then initiate a 
connection out to port 50021 on ep2. 

To further illustrate, consider again the case of ep1 and ep2 mentioned above. If ep2 wanted 
to send ep1 a file, then ep1 would pick out a port (or ports) in its configured data port 
range of 40000 to 41000. For the sake of example let's say that port 40331 has been chosen. 
This value would then get communicated from ep1 to ep2, via the Globus Service through the GridFTP 
control channel that both ep1 and ep2 are listening to. At that point, ep2 would 
then initiate a connection out to port 40331 on ep1.

It is also important to consider what happens in cases where one endpoint is a Globus Connect 
Server endpoint and the other endpoint is a Globus Connect Personal endpoint. In such cases, 
the Globus Connect Personal endpoint will always initiate the connection to the Globus 
Connect Server endpoint for the transfer. Thus, it will always be the Globus Connect Server 
endpoint that picks the port (or ports) on which it will listen for that connection. This is the 
case irrespective of which endpoint is the sender or the recipient. As discussed previously, this 
information gets communicated from the Globus Connect Server endpoint to the Globus Connect 
Personal endpoint via the Globus Service.  

After looking at the example given we can see that, in terms of firewall rules, the outbound
rules for ep1 must allow it to connect outbound to ep2 on ep2's configured data port range if 
ep1 is to be able to send files to ep2. In terms of inbound rules, the firewall rules for 
ep1 must be configured to allow it to accept inbound connections on its own configured data 
port range for it to be able to receive files from other endpoints. The firewall rules for the 
data port range of any endpoint will be similar, and must allow outbound connections to the 
configured data port range of a remote endpoint for the local endpoint to be able to send files to 
the remote endpoint, and must allow inbound connections to the configure data port range of the 
local endpoint for that endpoint to be able to receive files from other endpoints.

As illustrated, an endpoint must be able to receive inbound connections on its own configured 
data port range, as well as be able to make outbound connections to the data port range of any 
endpoint it wishes to communicate with. If all Globus Connect Server admins pick their own 
custom port ranges, then this quickly leads to a situation in which site firewall policies 
become littered with custom rules for these various port ranges and endpoints. However, if 
everyone uses the default data port range, then firewall rules are much more predictable and 
manageable. It is for this reason that we recommend that everyone use the default data port 
range for their endpoint. Those who use a custom data port range may find that they have 
problems with their endpoint being able to communicate with other endpoints, for the reasons 
detailed above. Those using custom data port ranges may also find that the admins of other 
sites and endpoints may not be willing to set up custom firewall rules to accommodate custom 
data port range choices.

[appendix]
== Globus Connect Server Configuration Packages
Globus Connect Server is delivered as a set of packages that may be used to configure and update services for use on a Globus endpoint. The most commonly used package is globus-connect-server. It is used to configure all services for a Globus endpoint on a server and creates configuration files for the various services based on a common Globus endpoint configuration file. Using the default configuration file will configure and enable all services needed to create a single-server endpoint (see configuration file example link:https://github.com/globus/globus-connect-server/blob/master/source/globus-connect-server.conf[here]).

The configuration file is parsed by globus-connect-server-setup (man page link:http://globus.github.io/globus-connect-server/globus-connect-server-setup.html[here]), which is run when an endpoint is initially created or its configuration is updated. This file is also parsed by globus-connect-server-cleanup (man page link:http://globus.github.io/globus-connect-server/globus-connect-server-cleanup.html[here]), which is run when it is desired to clean up the old endpoint configuration on the server. Both of these commands work by calling various component scripts that are sub-packages of the globus-connect-server package.

In addition to the consolidated globus-connect-server package, there are sub-packages, each with their own configuration programs which operate on the Globus Connect Server configuration file. Each sub-package operates on one of the services as described below, and depends on the packages needed to configure that service. The sub-packages are:

- globus-connect-server-io may be used to install a Globus GridFTP server that implements a file transfer service.
- globus-connect-server-id may be used to install a Globus MyProxy server that implements an identity provider service.
- globus-connect-server-web may be used to install a MyProxy OAuth server that integrates the MyProxy service with a branded web interface.

Installing one of these sub-packages does not configure the services. The administrator must run the setup program associated with that package in order to actually do the configuration. Likewise, when one of the sub-packages is removed, it does not disable the service that it was used to configure; this is done by running the cleanup program associated with the sub-package.

=== Globus Connect Server I/O

The *globus-connect-server-io* package configures a GridFTP server. The main actions executed by this package during setup and cleanup are described below. This package depends on the authorization callouts, MyProxy (client side) programs, and the GridFTP server program.

globus-connect-server-io-setup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-io-setup.html[here])

- Fetch a certificate from the Globus Connect CA and write GridFTP configuration to use it
- Write GridFTP configuration to enable sharing (note: sharing may only be enabled on managed endpoints with a valid Provider plan subscription)
- Fetch MyProxy trust roots (if configured to use a MyProxy server)
- Write GridFTP configuration for authorization callouts
* If using CILogon, install CILogon CA and CRLs in the globus-connect-server certificate directory and add a cron job to refresh the CRL
* If using a remote MyProxy server, fetch the MyProxy service certificate and trust roots and install them into the globus-connect-server certificate directory
- (Re)start the GridFTP server
- Enable the GridFTP server to start on reboots
- Bind the GridFTP server to a Globus endpoint

globus-connect-server-io-cleanup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-io-cleanup.html[here])

- Remove Globus Connect CA certificate if used
- Remove GridFTP service configuration
- Remove the Globus endpoint binding
- Remove CILogon CRL cron job
- Stop the GridFTP service
- Disable the GridFTP service

Please see the command line tools for managing an I/O node configuration for more information.

=== Globus Connect Server Identity

The *globus-connect-server-id* package is used to configure a MyProxy identity service. This service can be configured as an identity provider using system passwords or as a certificate store for certificates generated elsewhere. The default configuration method for Globus Connect Server is as an identity provider. As an identity provider it will generate short-lived certificates for users if they are able to authenticate with their login password. As a certificate store, certificates are generated by some process outside of MyProxy and may be added to the store by the normal MyProxy Commands. This package depends on the MyProxy server and globus-simple-ca.

globus-connect-server-id-setup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-id-setup.html[here])

- Fetch a certificate from the Globus Connect CA and write MyProxy server configuration to use it
- Set up the MyProxy CA if acting as an identity provider
- (Re)start the MyProxy server
- Enable the MyProxy server to start on reboots

globus-connect-server-id-cleanup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-id-cleanup.html[here])

- Stop the MyProxy CA service
- Disable the MyProxy CA service

=== Globus Connect Server Web

The *globus-connect-server-web* package is used to configure a MyProxyOAuth identity service. This service provides a web interface to a MyProxy service, which may be running on the same node or elsewhere. This web interface may be customized by adding site-specific style sheets and images to make it conform to the look of the organization running the service.

globus-connect-server-web-setup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-web-setup.html[here])

- Enable mod_ssl and the default SSL site if needed
- Copy the OAuth site configuration to /etc/httpd/conf.d (rpm) or /etc/apache2/conf.d (deb)
- Restart the web server
- Enable the web server to start on reboots

globus-connect-server-web-cleanup (link to man page link:http://globus.github.io/globus-connect-server/globus-connect-server-web-cleanup.html[here])

- Disable mod_ssl and the default SSL site if we enabled it during setup
- Remove the OAuth site configuration file from /etc/httpd/conf.d or /etc/apache2/conf.d
- Restart the web server

[appendix]
[[update_section]]
=== How to update a Globus Connect Server install
The Globus team is improving the Globus Connect Server software all
the time, occasionally, you should update your software to get all the
latest bug fixes and improvements.  

If you are using a version of Globus Connect Server released prior to GT 6,
then please see our upgrade instructions xref:upgrade_section[here].

If you are using a Globus Connect Server version based on GT 6 or later, then
follow these instructions to update your install:

.Red Hat Enterprise Linux, CentOS, Scientific Linux, Fedora
----terminal
$ sudo yum update globus-connect-server
----terminal

.SuSE Linux Enterprise Server
----terminal
$ sudo zypper refresh
$ sudo zypper update globus-connect-server
----terminal

.Debian, Ubuntu
----terminal
$ sudo apt-get update
$ sudo apt-get upgrade globus-connect-server
----terminal

[appendix]
[[upgrade_section]]
=== Upgrading from an older (<GT6) version of Globus Connect Server

If you have an old Globus Connect Server install that you want to upgrade, 
be sure to remove the old Globus Connect Server packages and config, as well 
as to delete your endpoint definition so that it can be recreated cleanly 
during the new install:

.All Distributions
----terminal
$ sudo globus-connect-server-cleanup -d
----terminal

After cleaning up your old endpoint definition (if appropriate) remove the old Globus packages like so:

.Red Hat Enterprise Linux, CentOS, Scientific Linux, Fedora
----terminal
$ sudo yum remove \\*globus\*
$ sudo yum remove \\*myproxy\*
----terminal

.SuSE Linux Enterprise Server
----terminal
$ sudo zypper remove \\*globus\*
$ sudo zypper remove \\*myproxy\*
----terminal

.Debian, Ubuntu
----terminal
$ sudo apt-get purge ".\*globus.\*"
$ sudo apt-get purge ".\*myproxy.*"
----terminal

Finally, ensure that you remove old config that might still be left behind after removing the packages:

.All Distributions
----terminal
$ sudo rm /etc/globus-connect-server.conf 
$ sudo rm -r /etc/grid-security 
$ sudo rm -r /var/lib/globus-connect-server
$ sudo rm /etc/gridftp.conf
----terminal

At this point, your environment is clean and you can follow the instructions 
xref:install_section[here] to put down a clean install of Globus Connect Server to recreate 
and upgrade your endpoint.

[appendix]
[[s3_setup_section]]
=== Setting up an Amazon S3 based endpoint
Organizations that have a Globus link:https://www.globus.org/providers/provider-plans[Provider Plan] can set up an Amazon S3 based endpoint by following the documentation provided at the following link:

https://www.globus.org/amazon-web-services/s3-endpoint-configuration

[glossary]
== Glossary
[[endpoint-anchor]]endpoint::
  This is general term used to refer to a specific service that Globus can use to perform 
  file transfers and other functions. For example:
* I transferred files to the endpoint
* I created a share for you on the endpoint
* The endpoint’s file system is fast
[[endpoint-definition-anchor]]endpoint definition::
  This term refers to the metadata about the endpoint, stored as an object in the 
  Globus.org database, used to simplify using and referring to the 
  xref:endpoint-anchor[endpoint] for 
  users.  Some such metadata includes the hostname, port, OAuth server, default directory, 
  etc... Much of the information in the endpoint definition is sent to Globus when the 
  globus-connect-server-setup command is run.
[[endpoint-name-anchor]]endpoint name::
  The name of your endpoint uniquely identifies it and allows others to 
  search for and find your endpoint via the Globus service. A full endpoint 
  name takes the form of: ORGANIZATION_ACCOUNT_NAME#UNIQUE_SHORT_NAME.
  As shown, the first part of an endpoint's full name is the name of the
  xref:organization-account-anchor[organization account] that was used to 
  create it. The first part of the name will be the same for all endpoints 
  in your organization. The second part of the endpoint name will be unique 
  within your organization to that particular endpoint. It is a good idea to 
  pick the second part of the name to be something descriptive to the purpose 
  of the endpoint, so as to make it easier for users to search for and find
  the endpoint they are looking for. For example, if ABC University (with an 
  organization account name of "abcu") had a geosciences related endpoint, they 
  might name it something such as: abcu#geosciences.
Globus Connect Server::
  add definition here
GridFTP::
  GridFTP is an extension of the standard File Transfer Protocol (FTP)
  for high-speed, reliable, and secure data transfer.
  See the {gridftp}[GridFTP documents] for more information.
MyProxy::
  MyProxy is open source software for managing X.509 Public Key
  Infrastructure (PKI) security credentials (certificates and private
  keys).
  See the {myproxy}[MyProxy website] for more information.
OAuth for MyProxy::
  OAuth for MyProxy provides an OAuth-compliant REST web interface to
  the MyProxy service for providing user certificates to Globus.
  See the 'OAuth' section of the {myproxy}[MyProxy webpage] for more
  information.
[[organization-account-anchor]]Organization account::
  This is the Globus account that will be used to create and manage endpoints
  for your organization. It is a good idea to pick a name that is easily
  recognized as being associated with your endpoint, as the name of your
  Organization account will be the first part of the 
  xref:endpoint-name-anchor[endpoint] name for every endpoint created for your 
  organization. For example, ABC University might register an organization 
  account of "abc" or "abcu". Please do not choose account names that 
  correspond to copyrighted or trademarked terms unless your organization has 
  rights to those terms. 
