= Select Group

== Overview
The Select Group helper page can be used to redirect your users to the Globus web app
and allow them to select one or more groups. The selected group(s) will be returned to
you by way of an HTML form `POST` action.

Select Group is located at `https://www.globus.org/app/select-group`

== Supported Query Parameters
* action
* cancelurl
* multiple

=== `action`
Used for the `<form>` element's `action` attribute value.

=== `cancelurl`
Used as the destination to redirect the client to in the event the "Cancel" button is clicked.

=== `multiple`
If set to `yes` (default) the user will be allowed to select multiple groups (checkboxes). If set to `no` or any value other than `yes` the user will be limited to selecting a single group (radio buttons).

== Response

When the user submits the form, the following data will be sent to the URL
specified by the `action` parameter:

* `groupUuid[0]`, `groupUuid[1]`, ... `groupUuid[n]`
* `groupName[0]`, `groupName[1]`, ... `groupName[n]`

If the user selects multiple groups, they will appear in the same order in
both lists such that, e.g., `groupName[2]` is the name and `groupUuid[2]` is
the UUID of the third group in the user's selection.
