= Site Docs
:imagesdir: .

== Other Site Docs
link:asciiguide[Adoc Guide] (link:raw/asciiguide.adoc[RAW])

link:highlight-test/index.html[Highlight Test]

== Custom Doc Site Styles
[go-icon-pp]#go-icon-pp class#

[uservars]#uservars class#

[yellow-background]#yellow-background class#

[underline]#underline class#

.Terminal Blocks
----terminal
example of a terminal block with [input]#input# and [output]#output# classes
----terminal

NOTE: To use a terminal block, instead of using "----" as you would for a normal listing block, you would use "----terminal"

== Customizing Order of the Sidebar Menu
The sidebar menu can be customized for adoc pages under /cli/ and /api/ by adding a "menu_weight" variable in a yaml format at the top of the file. So the top of your file should look like:

....
----
menu_weight: 2
----

= Page Title

Page content...

....

[role="terminal"]
----
test terminal block with [input]#input# and [output]#output# classes
----

[role="terminal"]
--
test terminal block 2 with [input]#input# and [output]#output# classes
--

----
testing staging
----

== [go-icon-pp]#Go icon pp usage#

=== [go-icon-pp]#Go icon pp usage on h3#

==== [go-icon-pp]#Go icon pp usage on h4#

.[go-icon-pp]#Provider Plan Features in a block title#
[NOTE]
====
Globus file transfer is free-of-charge for non-profit research and educational use.
Some premium Globus features described in this guide are only available to
{provider_plans}[Provider Plan subscribers].
====
