= Endpoint ACL Management
:toc:
:toclevels: 3
:numbered:

////
Note: We use asciidoc in some table cells for
1. labeled lists
2. source code (json) blocks.
You need to be careful to not have spaces between the a| and content, 
otherwise it shows up as monospace (?) in asciidoc.py.
Also, using 'a' type cells when not needed makes asciidoc slower; it executes
asciidoc for each cell of type 'a'.
////

== Overview

Shared endpoints and owner activated S3 endpoints have an associated Access
Control List (ACL), and the API provides methods for reading, creating,
updating and deleting access rules in the ACL. The ACL for each endpoint can
have at most 100 access rules.

The owner of the endpoint always has full read and write access to the endpoint.
This is not included as a rule in the ACL, as it is always present and can't
be removed.

Access rules are always additive, so permissions cannot be further restricted
in subdirectories. For example, if a rule gives the user read-write access to
"/projects/" and another rule gives read-only access to "/projects/study1/",
then the user is still granted full read-write access to "/projects/study1/".

NOTE: Access is still subject to the local filesystem or S3 bucket
permissions. Globus ACLs provide an additional layer on top of local
permissions to simplify collaboration among Globus users.

[[rest_access_delegation]]
== ACL Management Permission and Delegation

The owner always has permission to manage the ACL on an endpoint. The owner can
also delegate ACL management to other Globus users or groups. This is done by
the "access_manager" role on the endpoint. See the
link:../endpoint_roles[Endpoint Roles] documentation. Note that
users who have delegated ACL management permission can't further delegate to
other users; only the owner can configure the "access_manager" role on the
endpoint.

Users and groups with an "access_manager" role assignment on an endpoint also
have implicit "rw" permission on "/". This is visible in the
<<rest_access_get_list,access list>>, but the implicit rules can't be fetched,
updated or deleted using any other part of the acl API. The
link:../endpoint_roles[Endpoint Roles] API should be used to
manipulate role assignments. Note that access rules from roles can only have
+principal_type+ of "user" or "group", and will have +role_id+ set instead of
+id+, for use with the Endpoint Roles API. Access rule ids are not guaranteed
to be unique from role ids, so passing a +role_id+ to the acl API could result
in a "NotFound" error or in an unrelated access rule being returned.

== Document Type

All ACL management resources use the "access" document type, which represents
a single access rule in the ACL.

.Access Document Example
------------------------
{
    "DATA_TYPE": "access",
    "id": 12345,
    "role_id": null,
    "principal_type": "user",
    "principal": "bob",
    "path": "/",
    "permissions": "r"
}
------------------------

.Uniqueness
Attempting to create an access rule with the same (+principal_type+,
+principal+, +path+) as an existing rule in the endpoint's ACL will result in
an error in almost all cases. However this is not enforced 100%, so clients
must be able to display duplicates. Clients should not try to enforce
uniqueness themselves, as that would also be subject to race conditions and not
provide any additional functionality. Also note that this uniqueness is not
enforced between standard access rules and implicit rules associated with
an "access_manager" role assignment.

=== Fields

[cols="1,1,8",options="header"]
|===================
| Field Name     | JSON Type | Description
| DATA_TYPE      | string
                 | Always has value "access" to indicate this document type.
| id             | int
                 | Globally unique id for this access rule. Implicit access
                   rules from "access_manager" role assignments will have a
                   null +id+, see +role_id+.
| principal_type | string
                 | Type of principal that the rule applies to.
                   One of "user", "group", "email",
                   or "all_authenticated_users".
| principal      | string
                 a|The subject of the access rule; the interpretation
                   depends on +principal_type+:

                   Type "user":: a Globus username
                   Type "group":: a Globus group uuid
                   Type "email":: an email address
                   Type "all_authenticated_users":: an empty string

| path           | string
                 | Absolute path to a directory the access rule applies to.
                   The path must begin and end with a slash, and can't
                   contain un-normalized components "/../" or "/./".
                   GridFTP endpoints and shared endpoints hosted on GridFTP
                   endpoints also support home directory relative paths
                   beginning with "/~/". The path is limited to 2000
                   characters after encoding; in practice this means
                   2000 ascii characters and slightly less when unicode
                   is present and must be encoded.
| permissions    | string
                 | How much permission to grant the principal specified in
                   +principal_type+ and +principal+.
                   Either read-only, specified as "r",
                   or read-write, specified as "rw".
| role_id        | string
                 | For an implicit access rule from an "access_manager" role
                   assignment, this will be set to the id of the role.
                   +null+ for standard access rules. This can be used to
                   manipulate the corresponding role using the Endpoint Roles
                   API.
|===================


=== Access Rule Types

==== User Access Rule

User access rules apply to a single Globus user, indicated by Globus username.
The Nexus API provides resources for searching for users by full name and other
attributes.

When a user access rule is added, a notification email can optionally be sent
to the email address associated with that user's Globus account. The default
is to not send any notification. See the <<rest_access_create,Create>> section
below for details.

==== Group Access Rule

Group access rules apply to all Globus users in a Globus group. Groups can
be created and discovered with the Nexus API. In the access rules, they
are indicated by the group id, not by the group name which is not necessarily
unique.

NOTE: Group ids are not validated; it is the responsibility of the client to
ensure the id is correct via the Group API in Nexus. Also if the group is
deleted, the rule will no longer provide any access but will stay in the ACL
until deleted by the user or client application.

==== All Authenticated Users Access Rule

These rules grant access to all Globus users. This can be used to share data
with everyone, but still allows monitoring of how many people are accessing
the data.

==== Email Access Rule

If you're trying to share with someone and don't know their Globus user name or
they don't yet have an account, you may create an "email" access rule. When an
"email" rule is created, Globus sends an email invitation to the email address
specified in +principal+. 

// NB: This is duplication of rest_claim text
When the access rule is claimed, it will be updated as follows:

* +principal_type+ will be set to "user".
* +principal+ will be set to the username of the Globus user who claimed the
  access rule. 

Each email access rule can be claimed
by only one Globus user account.

Before the email access rule is claimed, it can be manipulated like any other
access rule - the permission can be updated and it can be deleted. If deleted
before claimed, any attempt to claim it will fail with an error.

See the <<rest_claim,Claim>> section below for details on how to claim an email
access rule.  In most cases this will be handled by the user following a link
in the invitation email to the http://www.globus.org[Globus] website.

If the recipient of an email access rule did not receive the email, it's
recommended that the old rule be deleted and a new rule for the same email
and path be added to resend a new invitation. This will revoke the original
invitation which is presumed to have been lost. If the user eventually receives
both, they should attempt to claim the newer one.

NOTE: If an email access rule is claimed by a user who already has a user
access rule on the same path, the duplicate will be allowed. This is an
important exception to the uniqueness enforcement.


== URL Arguments

The operations below make use of the following arguments in the URL,
delimited by <> in the descriptions.

[cols="1,1,8",options="header"]
|===================
| Name              | Type  | Description
| endpoint_name   | string
| Canonical name of an endpoint, of the form user#endpoint. For backward
  compatibility, a bare endpoint name is also supported and the user portion
  is assumed to be the user accessing the API. This behavior is deprecated
  and should not be relied upon - all new code should use a full
  canonical endpoint name. Also note that the endpoint name must be percent
  escaped; in particular +#+ is a reserved character.
                                
| id  | int | Integer id of an access rule.

| token  | string | A token included in the email sent to a user for email
                    access rules. This token is never exposed directly by
                    the API.
|===================


== Common Query Parameters

[cols="1,8",options="header"]
|===================
| Name   | Description
| fields | Comma separated list of fields to include in the response. This can
           be used to save bandwidth on large list responses when not all
           fields are needed.
| format | "json" or "html". Note that the "html" format is subject to change
           and should not be relied upon for programs. It is used to render
           the self-hosted, auto-generated API documentation.
|===================


== Common Errors

[cols="1,1,8",options="header"]
|===================
| Code              | HTTP Status  | Description
| EndpointNotFound  |404  | If <endpoint_name> not found
| AccessRuleNotFound|404  | If access rule specified by <id> is not found
| NotSupported      |409  | If <endpoint_name> does not support ACLs.
                            See the +acl_available+ field of +endpoint+ to
                            determine if an endpoint supports ACLs.
| PermissionDenied  |403  | If you do not have permissions to view or modify
                            ACLs on <endpoint_name>.
| ServiceUnavailable|503  | If the service is down for maintenance.
|===================


== Operations

[[rest_access_get_list]]
=== Get list of access rules

Get the list of access rules in the ACL for a specified endpoint.

NOTE: This list includes implicit rules from "access_manager" roles, which
can't be manipulated directly with other operations in the acl API. The
endpoint owner also has full read-write permission and this is not included in
the list. See <<rest_access_delegation,ACL Management Permissions and
Delegation>>.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_name>/access_list

| Method
| GET

| Response Body a| 
------------------------------------
{
    "length": 2,
    "endpoint": "alice#myshare",
    "DATA": [
        {
            "DATA_TYPE": "access",
            "principal_type": "user",
            "path": "/",
            "principal": "bob",
            "id": 12345,
            "role_id": null,
            "permissions": "r"
        },
        {
            "DATA_TYPE": "access",
            "principal_type": "group",
            "path": "/project1",
            "principal": "a2e662ac-d4bc-4ab7-aceb-8a12d2205326",
            "id": 743565,
            "role_id": null,
            "permissions": "rw"
        }
    ],
    "DATA_TYPE": "access_list"
}
------------------------------------
|============


=== Get access rule by id

Get a single access rule for a specified endpoint by id.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_name>/access/<id>

| Method
| GET

| Response Body | Access document (see above).
|============


[[rest_access_create]]
=== Create access rule

Create a new access rule. The response contains the id of the newly created
rule in the +access_id+ field. Returns http status 201 and a +result+ document
with code "Created" on success.

The +send_email+ field is optional and not persisted as part of the +access+
document. For email access rules, +send_email+ defaults to true and passing
false will result in a +BadRequest+ error. For user access rules, both true and
false are allowed and the default is false. For all other +principal_type+
values, the default is false, and passing a true value will result in
+BadRequest+.

NOTE: The +id+ field of the access document must be omitted in create requests.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_name>/access

| Method
| POST

| Request Body a|
------------------------
{
    "DATA_TYPE": "access",
    "principal_type": "user",
    "principal": "bob",
    "path": "/",
    "permissions": "r"
    "send_email": true,
}
------------------------

| Response Body a|
---------------------------------------------------
{
    "code": "Created",
    "resource": "/endpoint/epname/access",
    "DATA_TYPE": "access_create_result",
    "request_id": "abc123",
    "access_id": 12345,
    "message": "Access rule created successfully."
}
---------------------------------------------------
|============

==== Errors

[cols="1,1,8",options="header"]
|===================
| Code     | HTTP Status | Description
| InvalidPath   | 400  | If the path specified in the access rule is not
                            valid or too long.
| LimitExceeded | 409 | If the endpoint ACL already has the maximum of 100
                        access rules.
| Exists        | 409 | If an access rule with the same
                        (+principal_type+, +principal+, +path+) already
                        exists in the endpoint's ACL.
| UserNotFound  | 404 | If the username specified in +principal+ when
                        +principal_type+ is "user" can't be found.
|===================


=== Update access rule

Update the permissions on an existing access rule. Other fields (besides
+DATA_TYPE+ which must always be present) may be omitted. If the id is present
it must match the id in the URL.

Returns a +result+ document with code "Updated" on success, but checking that
the HTTP status code is 2xx is sufficient to verify success.

NOTE: This may support updating +path+ or other fields in the future, so
clients should make sure to use the correct value for the other fields
or omit them entirely.

NOTE: If an email access rule has been claimed since the client fetched
it and become a user access rule, this will update the user access rule,
which has the same id.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_name>/access/<id>

| Method
| PUT

| Request Body
| Access document

| Response Body a|
-------------------------------------------------------------------
{
    "message": "Access rule '123' permissions updated successfully",
    "code": "Updated",
    "resource": "/endpoint/user#ep1/access/123",
    "DATA_TYPE": "result",
    "request_id": "ABCdef789"
}
-------------------------------------------------------------------
|============


=== Delete access rule

Delete a single access rule, specified by id.

Returns a +result+ document with code "Deleted" on success and HTTP status code
200, and an "AccessRuleNotFound" error if the rule has already been deleted. If
the client is using a retry loop, both should be accepted as success in case
the first successful attempt is disconnected after the request is processed but
before the response is received by the client.

NOTE: If an +email+ access rule has been claimed since the client fetched
it and become a +user+ access rule, this will delete the +user+ access rule,
which has the same id.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_name>/access/<id>

| Method
| DELETE

| Request Body  | Empty
| Response Body a|
-------------------------------------------------------------------
{
    "message": "Access rule '123' deleted successfully",
    "code": "Deleted",
    "resource": "/endpoint/user#ep1/access/123",
    "DATA_TYPE": "result",
    "request_id": "ABCdef789"
}
-------------------------------------------------------------------
|============


[[rest_claim]]
=== Claim email access rule

Claim an email access rule as the authenticated user. The email access rule
will be converted to a user access rule. Returns the user access rule, with an
additional +endpoint_name+ field which can be used to redirect the user to
that endpoint with the access rule path displayed in a file browser.

Once claimed, the user who claimed the access rule can continue to call this
method and get the same success response. This can be used to generate
the redirect URL if the user loads the link from the email again
after claiming the access rule.

NOTE: The access rule id does not change when claiming, but the
+principal_type+ and +principal+ will change to "user" and
"<username of claimant>".

NOTE: The owner of the endpoint (creator of the email access rule)
can't claim it for themselves.

[cols="h,5"]
|============
| URL
| /claim_access/<token>

| Method
| POST

| Response Body a| 
------------------------------------
{
    "DATA_TYPE": "claim_response",
    "endpoint_name": "alice#myshare",
    "id": 12345,
    "role_id": null,
    "principal_type": "user",
    "principal": "bob",
    "path": "/",
    "permissions": "r"
}
------------------------------------
|============

==== Errors

[cols="1,1,8",options="header"]
|===================
| Code             | HTTP Status | Description

| Conflict | 409 
| If <token> has already been claimed by a different user.

| Conflict | 409
| If the authenticated user is the endpoint owner.

| EndpointNotFound | 404
| If the endpoint containing the access rule has been deleted.

| AccessRuleNotFound | 404
| If the owner of the endpoint has deleted the access rule
  (basically revoking the email invitation).

| BadRequest | 400
| If <token> is invalid, e.g. if the user's email client
  corrupts it or if the end got chopped off. This won't
  catch all possible corruptions - AccessRuleNotFound
  may be returned in some cases.
|===================


== Change History

[[changes_42]]
=== 4.2 (target)

- access rule document: add +role_id+ field, update doc for +id+
- doc: add delegation section with link to new "Endpoint Roles" document

=== 3.7 (2014-07-28)

- add new access rule principal type "email"
- add "send_email" option for type "user" access rules
