---
menu_weight: 5
---

= Endpoint Management
:toc:
:toclevels: 3
:numbered:
// use outfilesuffic in relative links to make them work on github
ifdef::env-github[:outfilesuffix: .adoc]

// See https://github.com/jbake-org/jbake/issues/80, github requires
// going through hoops to get the TOC to render.
ifdef::env-github[]
toc::[]
endif::[]

////
Note: We use asciidoc in some table cells for
1. labeled lists
2. source code (json) blocks.
You need to be careful to not have spaces between the a| and content, 
otherwise it shows up as monospace (?) in asciidoc.py.
Also, using 'a' type cells when not needed makes asciidoc slower; it executes
asciidoc for each cell of type 'a'.
////

== Overview

Endpoints are named entities that represent a gridftp or other file transfer
service server. They have a globally unique id, and a not necessarily unique
display name. The API for manipulating endpoint definitions is located under
+/endpoint/+.

NOTE: Endpoints used to be identified by a globally unique username qualified
name, called the canonical name. These names still exist but are deprecated
and will be removed in the future.

For operations that can be performed on an endpoint's filesystem, see
link:../file_operations[File Operations].

For delegating rights for managing various aspects of the endpoint's
administration to other users, see link:../endpoint_roles[Endpoint
Roles].

For getting list of endpoints matching a name or other categories, see
link:../endpoint_search[Endpoint Search].

=== Endpoint Visibility and Management

A private endpoint will be visible if any of the linked identities
associated with the Globus Auth token used to authenticate to the REST API
own the endpoint.

The client will have update and delete permissions on an endpoint if any of
the linked identities associated with the Globus Auth token own the endpoint
(see the +owner_id+ field). When creating an endpoint, it will have the
+owner_id+ and +owner_string+ set based on the primary identity.

[[document_types]]
== Document Types

[[endpoint_document]]
=== Endpoint Document

The "endpoint" document type represents a single transfer endpoint, and
contains a list of "server" documents in the "DATA" section, representing the
GridFTP server or servers used to access the endpoint.

==== Types of Endpoints

.Globus Connect Server endpoints
This category includes manually configured GridFTP servers, and servers
configured using the Globus Connect Server package. These endpoints will
have +is_globus_connect+ set to "false", +host_endpoint+ equal to "null",
and +s3_url+ equal to "null". To function, they must have at least one
+server+ sub-document.

.Globus Connect Personal endpoints
Globus Connect Personal endpoints have +is_globus_connect+ set to "true",
and the server sub-documents are virtual and can't be set by the user. The
+is_connected+ field of the virtual server sub-document can be used to
determine if the Globus Connect Personal client is currently running and
connected to Globus.

.Shared endpoints
Shared endpoints will have +host_endpoint+ set to a non-null value. They have
no server sub-documents, and must always be +public+.

.S3 endpoints
S3 endpoints will have +s3_url+ set to a non-null value. They have no server
sub-documents.


.Endpoint Document Example
------------------------
{
  "DATA_TYPE": "endpoint", 
  "display_name": "myserver", 
  "organization": "My Org",
  "username": "auser", 
  "description": "Example gridftp endpoint.", 
  "public": false, 
  "is_globus_connect": false, 
  "globus_connect_setup_key": null, 
  "s3_url": null, 
  "s3_owner_activated": false, 
  "host_endpoint": null, 
  "host_path": null
  "disable_verify": false, 
  "force_encryption": false, 
  "myproxy_server": null, 
  "myproxy_dn": null, 
  "oauth_server": null, 
  "default_directory": null, 
  "activated": false, 
  "expires_in": 0, 
  "expire_time": "2000-01-02 03:45:06+00:00", 
  "shareable": true, 
  "acl_available": false, 
  "acl_editable": false, 
  "in_use": false, 
  "DATA": [
    {
      "is_paused": false, 
      "DATA_TYPE": "server", 
      "hostname": "gridftp.example.org", 
      "uri": "gsiftp://gridftp.example.org:2811", 
      "port": 2811, 
      "scheme": "gsiftp", 
      "is_connected": true, 
      "id": 985, 
      "subject": "/O=Grid/OU=Example/CN=host/girdftp.example.org"
    }
  ], 
}
------------------------

[[endpoint_fields]]
==== Endpoint Fields

[cols="1,1,8",options="header"]
|===================
| Field Name     | JSON Type | Description
| DATA_TYPE      | string
                 | Always has value "endpoint" to indicate this document type.
| id             | string
                 | 36 character unique identifier string for the endpoint.
| display_name   | string
                 | Friendly name for the endpoint, not unique.
                   Unicode string, max 128 characters, no new lines (\r or \n).
                   If not specified, will default to +canonical_name+, but
                   that is deprecated and all new clients hould use id and
                   +display_name+. Searchable.
| organization   | string
                 | Organization that runs the server(s) represented by the
                   endpoint. Optional to preserve backward compatibility, but
                   will eventually be required and all clients are encouraged
                   to require users to specify it. Unicode string, max 1024
                   characters, no new lines. Searchable.
| department     | string
                 | Department within organization that runs the server(s).
                   Searchable. Optional. Unicode string, max 1024 characters,
                   no new lines. Searchable.
| keywords       | string
                 | Comma separated list of alternative names for the endpoint.
                   Optional. Unicode string, max 1024 characters. Searchable.
| name           | string
                 | [DEPRECATED] Legacy friendly name for the endpoint. Limited
                   to 128 characters, and must match the regex
                   `^[0-9a-zA-Z][-0-9a-zA-Z_.]*$`. If not specified, will
                   default to the unique +id+.
| canonical_name | string
                 | [DEPRECATED] The username qualified endpoint name, of the
                   form USERNAME#ENDPOINTNAME. The username portion must match
                   the current user. Use +id+ instead in API requests, and
                   use +display_name+ to display to users. Will be searchable
                   until it is removed.
| username       | string
                 | [DEPRECATED] Use +owner_id+ or +owner_string+ instead.
                   The Globus username of the endpoint owner.
                   For non-globusid.org identities, this will be a
                   meaningless string starting with 'u_', and for
                   globusid.org identities it will be the globusid.org
                   username.
| owner_id       | string
                 | Identity id of the endpoint owner. Can't be updated.
| owner_string   | string
                 | Identity name of the endpoint owner. Can't be updated.
                   Will be included in the fulltext query index used by
                   the link:../endpoint_search API.
| description    | string
                 | A description of the endpoint. Unicode string, max length
                   4096 characters.
                   Included in fulltext search.
| contact_email  | string
                 | Email address of the support contact for the server(s)
                   represented by the endpoint. Optional. ASCII string,
                   must be a valid email address.
| contact_info   | string
                 | Other non-email contact information for the endpoint, e.g.
                   phone and mailing address. Optional. Unicode string, can
                   contain new lines, max 4096 characters.
| info_link      | string
                 | Link to a web page with more information about the endpoint.
                   ASCII string with an http or https URL. Basic checking is
                   done to make sure this is a valid URL, but the administrator
                   is responsible for running a website at this URL and
                   verifying that it's accepting public connections.
| public         | boolean
                 | True if the endpoint definition should be visible to other
                   Globus users.
| subscription_id | string
                 | If the endpoint is "managed", this will be a UUID string,
                   otherwise it will be null. Currently this is set by Globus
                   service administrators and can't be changed
                   via the REST API. It will be silently ignored on update.
                   Note that certain features like setting +network_use+ and
                   in most cases hosting shared endpoints require a
                   managed endpoint, so this field is useful for checking that
                   state.
| default_directory
                 | string
                 | Default directory to display when an endpoint is first
                   accessed on the globus.org web interface. The default
                   is `/~/` for GridFTP endpoints, and `/` for shared endpoints
                   and S3 endpoints. The mapping of `/~/` depends on the
                   configuration of the GridFTP server but is typically the
                   local user's home directory on Linux systems.
| force_encryption
                 | boolean
                 | Forces encryption of all network data for transfers to and
                   from the endpoint. If this is set, all transfer jobs will
                   have the encryption option automatically turned on
                   regardless of the user's initial submission options. If
                   this is not set, users can decide whether or not to enable
                   encryption. Default: false.
| disable_verify
                 | boolean
                 | This option indicates that the endpoint does not support
                   computing MD5 checksums, needed for the verify_checksum
                   option of transfer. When this is set, new job submissions
                   will default to not use the verify_checksum option.
| expire_time    | string
                 | Date and time the endpoint activation expires, or null if
                   not activated. Formatted as ISO 9660 but with space instead
                   of "T" separating the date and time portions.
| expires_in     | int
                 | Seconds until the endpoint expires, 0 if the endpoint is
                  expired or not activated, or -1 if the endpoint never expires
                  (for endpoints that use globus online credentials).
| activated      | boolean
                 | "true" if the endpoint is activated, "false" otherwise.
| myproxy_server | string
                 | The default MyProxy server to use when activating this
                   endpoint, or "null" if no associated proxy server.
| myproxy_dn     | string
                 | A non-standard subject DN to use with the default MyProxy
                   server. This is only necessary if the subject DN in the
                   server's certificate does not match its hostname. Can
                   be "null".
| oauth_server   | string
                 | hostname of server for getting credentials via oauth. For
                   this to work, the oauth server must be registered with
                   Globus Nexus and have the appropriate paths set up. Contact
                   support@globus.org for more information.
| is_globus_connect
                 | boolean
                 | "true" if the endpoint was created for Globus Connect
                   Personal, "false" otherwise. Note that this will be "false"
                   for Globus Connect Server endpoints.
| globus_connect_setup_key
                 | string
                 | Key needed to complete Globus Connect Personal installation.
                   "null" when installation/setup is complete. The key can
                   only be used once. Always "null" for non personal endpoints.
| host_endpoint  | string
                 | [DEPRECATED] Standard endpoint hosting the shared
                   endpoint; "null" for non-shared endpoints. Use
                   +host_endpoint_id+ and +host_endpoint_display_name+ instead.
| host_endpoint_id | string
                 | Id of standard endpoint hosting the shared
                   endpoint; "null" for non-shared endpoints.
| host_endpoint_display_name | string
                 | If the user has permission to view the host endpoint,
                   this will be set to the +display_name+ of the host, or
                   to the +canonical_name+ if the +display_name+ is not set.
                   "null" if the user does not have permission or if the
                   endpoint is not a shared endpoint.
| host_path      | string
                 | Root path being shared on the host endpoint; "null" for
                   non-shared endpoints. Only visible by the owner of the
                   endpoint, "null" for other users even if the ACL gives
                   them access to the files on the endpoint.
| s3_url         | string
                 | [ALPHA] For S3 endpoints, the url to the S3 bucket
| s3_owner_activated
                 | boolean
                 | [ALPHA] For S3 endpoints, true if the endpoint is activated
                   by the owner with Amazon credentials, and can be
                   auto-activated by other users.
| acl_available  | boolean
                 | [ALPHA] "true" for endpoints that support the ACL resources
| acl_editable   | boolean
                 | [DEPRECATED] True if the user has the "access_manager"
                   role on the endpoint. This is deprecated, and
                   +my_effective_roles+ should be used instead.
| in_use         | boolean
                 | "true" if any active tasks owned by the user are using the
                   endpoint
| my_effective_roles | list of string
                 | [ALPHA] List of roles the current user has on the endpoint.
| gcp_connected  | boolean
                 | If +is_globus_connect+ is "true", this indicates if the
                   Globus Connect Personal (GCP) software is running and
                   connected to Globus. "null" for other endpoint types.
| gcp_paused     | boolean
                 | If +is_globus_connect+ is "true", this indicates if the
                   Globus Connect Personal (GCP) has been paused.
                   "null" for other endpoint types.
| network_use    | string
                a|This field may only be changed on managed endpoints. If a
                  managed endpoint becomes unmanaged, the "normal" level will
                  be automatically used. On shared endpoints, this field will
                  be null. Allowed values for +network_use+ are:

                   "normal"::
                       The default setting. Uses an average level of
                       concurrency and parallelism. The levels depend on the
                       number of physical servers in the endpoint; use
                       endpoint-details to display the exact values.
                   "minimal"::
                       Uses a minimal level of concurrency and parallelism.
                   "aggressive"::
                       Uses a high level of concurrency and parallelism.
                   "custom"::
                       Uses custom values of concurrency and parallelism set by
                       the endpoint admin. When setting this level, you must
                       also set the +max_concurrency+, +preferred_concurrency+,
                       +max_parallelism+, and +preferred_parallelism+ options.
                       (Note: the parallelism options must be set to null
                       for S3 endpoints)
| location       | string
                 | "Automatic" or comma separated floats in the form
                   "LATITUDE,LONGITUDE". "null" for shared endpoints.
| min_concurrency | integer
                 | Can be +network_use+ "custom", otherwise will contain the
                   preset value for the specified +network_use+. Will be
                   "null" for shared endpoints.
| preferred_concurrency | integer
                 | Can be +network_use+ "custom", otherwise will contain the
                   preset value for the specified +network_use+. Will be
                   "null" for shared endpoints.
| min_parallelism | integer
                 | Can be +network_use+ "custom", otherwise will contain the
                   preset value for the specified +network_use+. Will be
                   "null" for shared endpoints.
| preferred_parallelism | integer
                 | Can be +network_use+ "custom", otherwise will contain the
                   preset value for the specified +network_use+. Will be
                   "null" for shared endpoints.
|===================


[[server_document]]
=== Server Document

The server document represents a network service that provides access to
a filesystem. The most common type is a GridFTP server, which is
represented by +scheme+ "gsiftp". This is also the default +scheme+.

.Server Document Example
-----------------------
{
  "DATA_TYPE": "server", 
  "id": 985, 
  "scheme": "gsiftp", 
  "hostname": "gridftp.example.org", 
  "port": 2811, 
  "subject": "/O=Grid/OU=Example/CN=host/girdftp.example.org"
  "uri": "gsiftp://gridftp.example.org:2811", 
  "is_paused": false, 
  "is_connected": true, 
}
-----------------------

==== Server Fields

Only +hostname+ is required on create.

[cols="1,1,8",options="header"]
|===================
| Field Name     | JSON Type | Description
| DATA_TYPE      | string
                 | Always has value "server" to indicate this document type.
| id             | int
                 | Unique identifier for a server in an endpoint.
| hostname       | string
                 | Hostname of the server.
| port           | int
                 | Port the server is listening on. Default: 2811.
| scheme         | string
                 | URI scheme (protocol) used by the endpoint. Must be
                   "gsiftp" or "ftp". Default: "gsiftp".
| subject        | string
                 | subject of the x509 certificate of the server. If not
                   specified, the CN in the subject must match its hostname.
| uri            | string
                 | URI of the server. This is a derived field combining the
                   scheme, hostname, and port, and is not used when creating
                   servers.
| is_connected   | boolean
                 | [DEPRECATED] Use +gcp_connected+ in the +endpoint+ document
                   instead.
                   For globus connect personal endpoints, indicates if the
                   endpoint is available for operations; always true
                   for other endpoints. When false, check the value of
                   +is_paused+ to determine if the user requested a
                   temporary disconnect, or if globus connect is not
                   running or not connected to a network.
| is_paused      | boolean
                 | [DEPRECATED] Use +gcp_paused+ in the +endpoint+ document
                   instead.
                   For globus connect endpoints, indicates if the
                   endpoint has been paused by the user. Note that
                   when this is true, is_connected will always be
                   false, because the endpoint is not available for
                   any operations when paused. For non globus connect
                   endpoints, +is_paused+ will always be false.
|===================


[[shared_endpoint_document]]
=== Shared Endpoint Document

The shared endpoint document is used to create shared endpoints only. Once
created, a shared endpoint is accessed and updated using the standard endpoint
resources. Shared endpoints can be distinguished from other endpoints by
checking that the +host_endpoint+ field is set to a non-null value. +server+
documents can't be added or removed from shared endpoints; the server used
depends entirely on the +host_endpoint+.

.Shared Endpoint Document Example
-----------------------
{
  "DATA_TYPE": "shared_endpoint",
  "display_name": "myshare",
  "organization": "my org",
  "host_endpoint": "go#ep1",
  "host_path": "/~/",
  "description": "Share my home directory on go ep1"
}
-----------------------

==== Shared Endpoint Fields

+description+ is optional, other fields are required.

[cols="1,1,8",options="header"]
|===================
| Field Name     | JSON Type | Description
| DATA_TYPE      | string
                 | Always has value "shared_endpoint" to indicate this
                   document type.
| host_endpoint  | string
                 | Standard endpoint hosting the shared endpoint. Required.
| host_path      | string
                 | Path to share on the host endpoint. Required. On the shared
                   endpoint this path will appear to be the root of the
                   endpoint, and nothing outside this path will be accessible.
                   In Unix parlance, this is called a chroot or change root.
| display_name   | string
                 | See +endpoint+ document.
| name           | string
                 | [DEPRECATED] See +name+ for the endpoint document.
| description    | string
                 | See +endpoint+ document.
| organization   | string
                 | See +endpoint+ document.
| department     | string
                 | See +endpoint+ document.
| alternatives_names | string
                 | See +endpoint+ document.
| description    | string
                 | See +endpoint+ document.
| endpoint_info_link | string
                 | See +endpoint+ document.
| contact_email  | string
                 | See +endpoint+ document.
| contact_info   | string
                 | See +endpoint+ document.
|===================


[[path_arguments]]
== Path Arguments

[cols="1,1,8",options="header"]
|===================
| Name              | Type  | Description
| endpoint_xid      | string
| The +id+ field of the endpoint, or for backward compatibility the
  +canonical_name+ of the endpoint. The latter is deprecated, and all clients
  should be updated to use +id+.
|===================


[[common_query_parameters]]
== Common Query Parameters

[cols="1,1,8",options="header"]
|===================
| Name   | Type | Description

| fields | string
| Comma separated list of fields to include in the response. This can
  be used to save bandwidth on large list responses when not all
  fields are needed.
|===================


[[common_errors]]
== Common Errors

The resources in this document use old error codes conventions, with a dotted
code hierarchy.

[cols="1,1,8",options="header"]
|===================
| Code                  | HTTP Status  | Description

| EndpointNotFound  |404
| If <endpoint_xid> not found

| PermissionDenied  |403
| If user does not have privileges to get, modify, or delete the specified
  endpoint(s).

| EndpointDeleted   |409
| See <<get_endpoint_by_id,Get endpoint by id>>.
  The error document contains a +deleted_time+ field indicating when the
  endpoint was deleted, in addition to the standard error fields.

| ClientError.Conflict  |409
| If an endpoint with the same name already exists or if a role assignment
  with the same principal and role already exists.

| ServiceUnavailable    |503
| If the service is down for maintenance.
|===================


== Operations

[[get_endpoint_by_id]]
=== Get endpoint by id

Get a single endpoint by id. All fields are included by default, including the
+server+ subdocuments, but the +fields+ query parameter can be used to fetch
only specific fields.  Use "server" in the fields list to include server
subdocuments in a limited field list. For backward compatibility, an endpoint
canonical_name can be specified instead of the endpoint id, but this feature is
deprecated and all clients should migrate to using the id.

NOTE: Returns an "EndpointDeleted" error instead of "EndpointNotFound" for
deleted endpoints, but only when using id in the URL <endpoint_xid>
argument. If an endpoint canonical_name is used for the <endpoint_xid>,
it will return "EndpointNotFound" for deleted endpoints.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>

| Method
| GET

| Response Body
| <<endpoint_document,Endpoint document>>
|============


[[create_endpoint]]
=== Create endpoint

Create an endpoint. Which fields are required depends on the type of endpoint.
Note that +name+ and +canonical_name+ are deprecated and supported only for
backward compatibility; +display_name+ should be used instead of, or in
addition to, these fields. If +canonical_name+ is not set, it will default to
"USERNAME#ENDPOINT_UUID". At least one of them must be specified.

The result will include an +id+ field containing the globally unique endpoint
id, which should be used to further manipulate the endpoint document, and to
perform transfers and other operations on the endpoint's filesystem.

.Globus Connect Server endpoints
At least one of +display_name+ and +canonical_name+ is required, but at least
one "server" sub document must be created for it to function.

.Globus Connect Personal endpoints
Requires +display_name+ or +canonical_name+, and +is_globus_connect+ must be
set to "true".
Once created, the setup key can be obtained from the endpoint document
in field +globus_connect_setup_key+.

.Shared endpoints
Shared endpoints are created using a different resource, see
<<Create shared endpoint>>.

.S3 endpoints
The REST API does not yet support creating S3 endpoints, this must be done
using the CLI.

[cols="h,5"]
|============
| URL
| /endpoint

| Method
| POST

| Request Body
| <<endpoint_document,Endpoint document>>

| Response Body | Result document, including an +id+ field containing the
                  system generated id of the new endpoint.
|============


[[create_shared_endpoint]]
=== Create shared endpoint

Create a shared endpoint.

[cols="h,5"]
|============
| URL
| /shared_endpoint

| Method
| POST

| Request Body
| <<shared_endpoint_document,Shared endpoint document>>

| Response Body | Result document, including an +id+ field containing the
                  system generated id of the new endpoint.
|============


[[update_endpoint_by_id]]
=== Update endpoint by id

Update an endpoint. This can be done using a partial document by specifying
only +DATA_TYPE+ and the fields to be updated, or doing a +GET+ on the
endpoint, changing the appropriate fields, and doing a +PUT+ of the full
document. Using a partial document is preferred.

NOTE: For backward compatibility, endpoint PUT can also be used to update
the servers on the endpoint, in the form of total replacement of the list
of subdocuments. Using this is deprecated, and the server APIs should be used
instead. New code should not pass a "DATA" key at all when doing endpoint
update.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>

| Method
| PUT

| Request Body
| Partial <<endpoint_document,endpoint document>>

| Response Body | Result document
|============

Which fields can be updated depends on the type of endpoint:

[cols="h,5"]
|============
| Type | Updatable fields
| Globus Connect Server
| +display_name+, +description+, +public+,
  +default_directory+, +force_encryption+, +disable_verify+,
  +myproxy_server+, +myproxy_dn+, +oauth_server+,
  +organization+, +department+, +alternative_names+,
  +contact_email+, +contact_info+, +endpoint_info_link+,
  DEPRECATED: +name+/+canonical_name+

| Globus Connect Personal
| +display_name+, +description+,
  +organization+, +department+, +alternative_names+,
  +contact_email+, +contact_info+, +endpoint_info_link+
  DEPRECATED: +name+/+canonical_name+

| Shared endpoint
| +display_name+, +description+,
  +organization+, +department+, +alternative_names+,
  +contact_email+, +contact_info+, +endpoint_info_link+
  DEPRECATED: +name+/+canonical_name+

| S3 endpoint
| +display_name+, +description+,
  +organization+, +department+, +alternative_names+,
  +contact_email+, +contact_info+, +endpoint_info_link+
  DEPRECATED: +name+/+canonical_name+
|============


[[delete_endpoint_by_id]]
=== Delete endpoint by id

Delete an endpoint by id or canonical name (the latter is deprecated). Only the
owner can delete the endpoint.  Note that all data associated with the
endpoint, including roles and the ACL, will be deleted as well. If the hostname
of the server has changed, the +server+ document(s) in the endpoint should be
changed rather than deleting and recreating the endpoint with different
servers.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>

| Method
| DELETE

| Response Body | Result document
|============


[[get_endpoint_pause_rules]]
=== Get my effective endpoint pause rules

Get all pause rules on an endpoint that affect the current user, with
sensitive administrator only fields removed.

See also: link:../task#limited_pause_rule_document[pause_rule_limited document].

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>/my_effective_pause_rule_list

| Method
| GET

| Response Body | List of "pause_rule_limited" documents
|============


[[get_endpoint_server_list]]
=== Get endpoint server list

Get a list of all servers belonging to the specified endpoint. Note that
this is the same as the server list included under the "DATA" key of the
endpoint document.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>/server_list

| Method
| GET

| Response Body | List of server documents
|============


[[get_endpoint_server_by_id]]
=== Get endpoint server by id

Get a specific server belonging to the specified endpoint.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>/server/<server_id>

| Method
| GET

| Response Body | A "server" document
|============


[[add_endpoint_server]]
=== Add endpoint server

Add a server to the specified endpoint. The +hostname+ field is required,
+scheme+ and +port+ default to "gsiftp" and 2811, and +subject+ defaults
to "null". The derived fields and boolean status fields are ignored, and
should not be included in the request body.

Returns a result document containing the +id+ of the newly added server.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>/server

| Method
| POST

| Response Body | Server document without the id.

| Response Body a|
-------------------------------------------------------------------
{
    "DATA_TYPE": "endpoint_server_add_result",
    "id": 123,
    "code": "Created",
    "message": "Server added to endpoint successfully",
    "resource": "/endpoint/347a942d-3bf6-4d43-98e0-16e29cfb1d82/server",
    "request_id": "ABCdef789"
}
-------------------------------------------------------------------
|============


[[update_endpoint_server_by_id]]
=== Update endpoint server by id

Update a server belonging to the specified endpoint. Include only the
fields to be updated in the request body - any of +hostname+, +scheme+,
+port+, and +subject+ can be updated.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>/server/<server_id>

| Method
| PUT

| Request Body | Partial server document.

| Response Body | Result document
|============


[[delete_endpoint_server_by_id]]
=== Delete endpoint server by id

Delete a server belonging to the specified endpoint.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>/server/<server_id>

| Method
| DELETE

| Response Body | Result document
|============


[[get_shared_endpoint_list]]
=== Get shared endpoint list

Get a list of shared endpoints owned by the current user and hosted by a given
GridFTP or Globus Connect Personal endpoint. Returns a "BadRequest" error if
called on an endpoint that can't host shared endpoints.

[cols="h,5"]
|============
| URL
| /endpoint/<endpoint_xid>/my_shared_endpoint_list

| Method
| GET

| Response Body | An "endpoint_list" document
|============


[[get_endpoint_list]]
=== [DEPRECATED] Get endpoint list

NOTE: The endpoint_list API is deprecated, use
link:../endpoint_search[Endpoint Search] instead.

Get a paged list of all endpoints visible to the current user. Most fields are
returned by default, but some more expensive fields are omitted by default (see
the fields list above). Specific fields can be requested using the +fields+
query parameter, and the value "ALL" can be used to fetch all fields. The
+limit+ and +offset+ parameters are used for paging, with a default of
+offset+ 0 and +limit+ 10. The maximum allowed limit is 1000.

[cols="h,5"]
|============
| URL
| /endpoint_list

| Method
| GET

| Response Body a| 
------------------------------------
{

    "DATA_TYPE": "endpoint_list",
    "length": 1,
    "limit": 1,
    "offset": 0,
    "total": 125,
    "DATA": [
        {
            "DATA_TYPE": "endpoint",
            "activated": false,
            "disable_verify": false,
            "myproxy_server": null,
            "sharing_target_root_path": null,
            "DATA": [
                {
                    "is_paused": false,
                    "DATA_TYPE": "server",
                    "hostname": "gridftp.example.org",
                    "uri": "gsiftp://gridftp.example.org:2811",
                    "port": 2811,
                    "scheme": "gsiftp",
                    "is_connected": true,
                    "id": 985,
                    "subject": "/O=Grid/OU=Example/CN=host/girdftp.example.org"
                }
            ],
            "expires_in": 0,
            "canonical_name": "auser#myserver",
            "sharing_target_endpoint": null,
            "acl_available": false,
            "s3_url": null,
            "public": false,
            "default_directory": null,
            "username": "auser",
            "globus_connect_setup_key": null,
            "description": "Example gridftp endpoint.",
            "in_use": false,
            "is_go_storage": false,
            "force_encryption": false,
            "myproxy_dn": null,
            "expire_time": "2000-01-02 03:45:06+00:00",
            "acl_editable": false,
            "oauth_server": null,
            "host_endpoint": null,
            "name": "myserver",
            "is_globus_connect": false,
            "s3_owner_activated": false,
            "shareable": true,
            "host_path": null
        }
    ]

}
------------------------------------
|============

==== Ordering

The +orderby+ query parameter supports the following values, optionally
followed by a space and "ASC" or "DESC" for ascending or descending.
Ascending is the default. If no order is specified, "canonical_name ASC"
is used.

[cols="1,8",options="header"]
|===================
| Name     | Description
| name     | Sort by the bare endpoint name.
| canonical_name
           | Sort by the username qualified canonical name.
             This is the default.
| username | Sort by the owner of the endpoint.
| public   | Sort by whether the endpoint is public or private.
             In ascending order, "false" is sorted before "true".
| expire_time
           | Sort by the expire time of the credential used to activate
             the endpoint. In "ASC" order, expired and not activated endpoints
             will be listed first ("null" is treated like 0).
|===================

