= Transfer API Documentation
:revdate: May 13, 2016

[doc-info]*Last Updated: {revdate}*

// use outfilesuffic in relative links to make them work on github
ifdef::env-github[:outfilesuffix: .adoc]

This API provides a REST-style interface to the
link:https://www.globus.org[Globus] reliable file transfer service.
The Transfer API supports monitoring the progress of a user's file transfer
tasks, managing file transfer endpoints, listing remote directories, and
submitting new transfer and delete tasks. The API is ideal for integration into
Portals or Gateways to provide complex reliable file transfer capabilities
without having to develop and support these features on your own. It is also
easy to use for scripting, using any standard HTTPS or REST client
library in scripting languages like Python and Ruby.

== Contents

* link:overview[API Overview] -
  overview of API with authentication instructions and examples
* link:endpoint_activation[Endpoint Activation] -
  associate user credentials with an endpoint
* link:task_submit[Task Submission] - submit transfer and
  delete tasks
* link:task[Task Management] - monitor and cancel
  background transfer and delete tasks
* link:file_operations[File Operations] - foreground filesystem
  operations, including directory listing (ls), creating directories (mkdir),
  and renaming files (rename)
* link:endpoint[Endpoint Management] -
  create, update, and delete endpoint definitions and servers
* link:endpoint_search[Endpoint Search] -
  find endpoints matching a search query, by display_name and other
  endpoint fields
* link:endpoint_roles[Endpoint Roles] -
  control which users have different administrator rights or 'roles' on an
  endpoint
* link:endpoint_bookmarks[Endpoint Bookmarks] -
  list, create, rename, and delete bookmarks for an endpoint and path
* link:acl[Endpoint ACL Management] -
  view and modify access rules on endpoints that support an ACL
* link:advanced_endpoint_management[Advanced Endpoint Management] -
  endpoint administrators can monitor and operate on tasks to and from their
  endpoints
* link:change_history[Change History]

== Mailing List

The link:https://www.globus.org/mailing-lists[developer-discuss@globus.org]
mailing list is the best place to get help using the Transfer API.
Announcements about new features and deprecations are also sent to the list, so
all users of the API are encouraged to subscribe.

NOTE: The developer-discuss@globus.org list replaces the old transfer-api list.
The archives for the old list may still be useful, and is available and
searchable link:http://lists.globusonline.org/pipermail/transfer-api/[here].

== Example Clients

The client libraries are hosted on github:

* link:https://github.com/globusonline/transfer-api-client-python[Python client]
* link:https://github.com/globusonline/transfer-api-client-java[Java client]

The Python client is also link:http://pypi.python.org/pypi/globusonline-transfer-api-client/[available on PyPI], and can be installed with +easy_install+ or +pip+,
e.g. +easy_install globusonline-transfer-api-client+. This will install the
client library, but not the examples and the CA certificate.
