= Transfer API Documentation

// use outfilesuffic in relative links to make them work on github
ifdef::env-github[:outfilesuffix: .adoc]

This API provides a REST-style interface to the
link:https://www.globus.org[globus] reliable file transfer service.
The Transfer API supports monitoring the progress of a user's file transfer
tasks, managing file transfer endpoints, listing remote directories, and
submitting new transfer and delete tasks. The API is ideal for integration into
Portals or Gateways to provide complex reliable file transfer capabilities
without having to develop and support these features on your own.

== Contents

* link:overview[API Overview] - overview of API with authentication instructions and examples

This API provides a REST-style interface to the
link:https://www.globus.org[globus] reliable file transfer service.
The Transfer API supports monitoring the progress of a user's file transfer
tasks, managing file transfer endpoints, listing remote directories, and
submitting new transfer and delete tasks. The API is ideal for integration into
Portals or Gateways to provide complex reliable file transfer capabilities
without having to develop and support these features on your own.

== Contents

* link:overview[API Overview] - overview of API with authentication instructions and examples
* link:task[Task Management] - create, monitor, and cancel
  background transfer and delete tasks
* link:file_operations[File Operations] - foreground filesystem
  operations, including directory listing (ls), creating directories (mkdir),
  and renaming
  files (rename)
* link:endpoint[Endpoint Management] -
  create, update, and delete endpoint definitions
* link:endpoint_roles[Endpoint Roles] -
  control which users have different administrator rights or 'roles' on an
  endpoint
* link:acl[Endpoint ACL Management] -
  view and modify access rules on endpoints that support an ACL
* link:advanced_endpoint_management[Advanced Endpoint Management] -
  endpoint administrators can monitor and operate on tasks to and from their
  endpoints
* link:s3[S3 Integration] -
  information about S3 integration support in Globus, currently accessible
  via the API but requires the CLI to set up
* link:change_history[Change History]

== Mailing List

The
link:http://lists.globusonline.org/mailman/listinfo/transfer-api[mailing list]
is the best place to get help using the Transfer API. Announcements about new
features and deprecations are also sent to the list, so all users of the API
are encouraged to subscribe.

== Example Clients

The client libraries are hosted on github:

* link:https://github.com/globusonline/transfer-api-client-python[Python client]
* link:https://github.com/globusonline/transfer-api-client-java[Java client]

The Python client is also link:http://pypi.python.org/pypi/globusonline-transfer-api-client/[available on PyPI], and can be installed with +easy_install+ or +pip+,
e.g. +easy_install globusonline-transfer-api-client+. This will install the
client library, but not the examples and the CA certificate.

== Legacy Reference Documentation

The old API reference documentation is still exposed via dynamically generated
documentation resources. This can be browsed conveniently using the HTML
representation. It is accurate, but lacking explanations and can be hard to
follow. It's recommended to check the new documentation first, and use
the old documenation if it's not yet available in the new docs.

* link:https://transfer.api.globusonline.org/v0.10/resource_list?format=html&fields=name,method,self_link,url_patterns,description[Resources] -
a list of all the resources in the API, describing their purpose, what
document types they take as input and return as output, what query
parameters they accept, and what errors they can return.
* link:https://transfer.api.globusonline.org/v0.10/document_type_list?format=html[Document Types] -
a list of all the document types used in the API, describing their purpose, and
linking to a list of their fields and example representations.
